'use client';
import {useEffect,useState} from 'react';
type Order={id:string;stationId:string;status:string;paymentMode:string;paymentStatus:string;total:number;createdAt:string;paidAt:string|null;items:Array<{name:string;qty:number;unitPrice:number}>};
const money=(n:number)=>`₹${Math.round(n).toLocaleString('en-IN')}`;
const badge=(s:string)=>s==='PAID'||s==='DELIVERED'?'green':s==='CANCELLED'||s==='FAILED'?'red':'amber';
export default function CustomerOrders(){
 const[orders,setOrders]=useState<Order[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const load=async()=>{try{const r=await fetch('/api/customer/orders',{cache:'no-store'}),j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'Unable to load orders');setOrders(j.orders||[])}catch(e){setError(e instanceof Error?e.message:'Unable to load orders')}finally{setLoading(false)}};
 useEffect(()=>{void load();const t=window.setInterval(()=>void load(),15000);let es:EventSource|undefined;if(typeof EventSource!=='undefined'){es=new EventSource('/api/customer/events');es.onmessage=e=>{try{const d=JSON.parse(e.data);if(d.type==='ORDER_CREATED'||d.type==='ORDER_STATUS_CHANGED'||d.type==='PAYMENT_CAPTURED')void load()}catch{}};es.onerror=()=>{}}return()=>{clearInterval(t);es?.close()}},[]);
 return <main className="customerPage"><section className="customerHero"><div className="eyebrow">GENZ CAFE · CUSTOMER</div><div className="title">My food orders</div><p className="muted">Track your recent food orders and payment status.</p><div className="actions"><button className="btn" onClick={()=>location.href='/customer'}>Back to GenZ</button><button className="btn" onClick={()=>location.href='/customer/security'}>Account security</button></div>{error&&<div className="loginError" style={{marginTop:16}}>{error}</div>}{loading?<div className="card" style={{marginTop:16}}>Loading orders…</div>:orders.length===0?<div className="card" style={{marginTop:16}}>No food orders yet.</div>:<div style={{display:'grid',gap:12,marginTop:16}}>{orders.map(o=><article className="card" key={o.id}><div className="sectionHead"><div><div className="sectionTitle">{o.id}</div><div className="muted">{o.stationId} · {new Date(o.createdAt).toLocaleString('en-IN')}</div></div><div style={{display:'grid',justifyItems:'end',gap:5}}><span className={'badge '+badge(o.status)}>{o.status}</span><span className={'badge '+badge(o.paymentStatus)}>{o.paymentStatus}</span></div></div><div style={{display:'grid',gap:6,marginTop:12}}>{o.items.map((i,n)=><div className="priceLine" key={`${o.id}-${n}`}><span>{i.qty}× {i.name}</span><span>{money(i.qty*i.unitPrice)}</span></div>)}</div><div className="sectionHead" style={{marginTop:12}}><span className="muted">{o.paymentMode==='PAY_NOW'?'Online payment':'Pay at counter'}</span><b>{money(o.total)}</b></div></article>)}</div>}</section></main>}
