import {NextResponse} from 'next/server';
import {cookies} from 'next/headers';
import {COOKIE,requireStaff,audit} from '../../../../lib/staff-auth';
import {listInventoryMaterials,upsertMaterial,setMaterialActive,setRecipe,getRecipe,receiveMaterial,listBatches,inventoryValuation,createStocktake,completeStocktake,approveStocktake,rejectStocktake,listStocktakes,listWasteReasons,wasteMaterial,supplierList,supplierUpsert,purchaseHistory,inventoryHistory,inventoryReports} from '../../../../lib/inventory-materials';
import {adjustMaterialStock,setMaterialSettings} from '../../../../lib/inventory-actions';
const auth=async(p:string)=>requireStaff((await cookies()).get(COOKIE)?.value,p);
const fail=(e:unknown)=>{const m=e instanceof Error?e.message:'Inventory request failed';const status=m==='STAFF_FORBIDDEN'?403:m==='STAFF_UNAUTHORIZED'?401:400;return NextResponse.json({ok:false,error:m},{status});};
export async function GET(req:Request){try{await auth('inventory:read');const u=new URL(req.url),action=u.searchParams.get('action')||'materials';if(action==='recipe')return NextResponse.json({ok:true,recipe:await getRecipe(u.searchParams.get('menuItemId')||'')});if(action==='batches')return NextResponse.json({ok:true,batches:await listBatches(u.searchParams.get('materialId')||undefined)});if(action==='valuation')return NextResponse.json({ok:true,valuation:await inventoryValuation()});if(action==='stocktakes')return NextResponse.json({ok:true,stocktakes:await listStocktakes()});if(action==='waste-reasons')return NextResponse.json({ok:true,reasons:await listWasteReasons()});if(action==='suppliers')return NextResponse.json({ok:true,suppliers:await supplierList()});if(action==='purchases')return NextResponse.json({ok:true,purchases:await purchaseHistory()});if(action==='history')return NextResponse.json({ok:true,history:await inventoryHistory()});if(action==='reports')return NextResponse.json({ok:true,reports:await inventoryReports()});return NextResponse.json({ok:true,materials:await listInventoryMaterials()},{headers:{'Cache-Control':'no-store'}})}catch(e){return fail(e)}}
export async function POST(req:Request){try{const staff=await auth('inventory:write');const b=await req.json(),action=String(b?.action||'');if(action==='material'){const id=await upsertMaterial({id:b.id,name:String(b.name||''),category:b.category,unit:b.unit,reorderLevel:b.reorderLevel,staffId:staff.id});await audit(staff.id,'INVENTORY_MATERIAL_SAVED','inventory_material',id,{});return NextResponse.json({ok:true,id})}if(action==='material-status'){await setMaterialActive(String(b.materialId),Boolean(b.active),staff.id);return NextResponse.json({ok:true})}if(action==='recipe'){await setRecipe(String(b.menuItemId),Array.isArray(b.components)?b.components.map((x:any)=>({materialId:String(x.materialId),qtyPerItem:Number(x.qtyPerItem)})):[],staff.id);return NextResponse.json({ok:true})}if(action==='receive'){const id=await receiveMaterial({materialId:String(b.materialId),qty:Number(b.qty),unitCost:Number(b.unitCost),supplier:b.supplier,supplierId:b.supplierId,batchNumber:b.batchNumber,expiryAt:b.expiryAt,staffId:staff.id,note:b.note});await audit(staff.id,'INVENTORY_RECEIVED','inventory_batch',id,{materialId:b.materialId,qty:b.qty});return NextResponse.json({ok:true,batchId:id})}if(action==='adjust'){const raw=Number(b.qty);if(!Number.isFinite(raw)||raw<=0)throw Error('INVALID_STOCK_QUANTITY');await adjustMaterialStock(String(b.materialId),raw,'ADJUST',staff.id,b.note);return NextResponse.json({ok:true})}if(action==='waste'){const raw=Number(b.qty);if(!Number.isFinite(raw)||raw<=0)throw Error('INVALID_WASTE_QTY');const reasonId=String(b.reasonId||'');if(!reasonId)throw Error('WASTE_REASON_REQUIRED');await wasteMaterial({materialId:String(b.materialId),qty:raw,reasonId,staffId:staff.id,note:b.note});return NextResponse.json({ok:true})}if(action==='settings'){await setMaterialSettings(String(b.materialId),Number(b.reorderLevel),String(b.unit||'unit'),staff.id);return NextResponse.json({ok:true})}if(action==='stocktake')return NextResponse.json({ok:true,id:await createStocktake(staff.id,b.notes)});if(action==='stocktake-complete'){await completeStocktake(String(b.stocktakeId),Array.isArray(b.lines)?b.lines.map((x:any)=>({materialId:String(x.materialId),countedQty:Number(x.countedQty),note:x.note})):[],staff.id);return NextResponse.json({ok:true})}if(action==='stocktake-approve'){await approveStocktake(String(b.stocktakeId),staff.id);return NextResponse.json({ok:true})}if(action==='stocktake-reject'){await rejectStocktake(String(b.stocktakeId),staff.id,String(b.reason||''));return NextResponse.json({ok:true})}if(action==='supplier'){const id=await supplierUpsert({id:b.id,name:String(b.name||''),phone:b.phone,email:b.email,address:b.address,staffId:staff.id});return NextResponse.json({ok:true,id})}throw Error('Invalid inventory action')}catch(e){return fail(e)}}
