import {NextResponse} from 'next/server';
import {cookies} from 'next/headers';
import {findMember,listMembers,createMember,updateMember} from '../../../lib/members';
import {COOKIE,requireStaff,audit} from '../../../lib/staff-auth';
export const dynamic='force-dynamic';
const auth=async(p:string)=>requireStaff((await cookies()).get(COOKIE)?.value,p);
const fail=(e:unknown)=>{const m=e instanceof Error?e.message:'';const status=m==='STAFF_UNAUTHORIZED'?401:m==='STAFF_FORBIDDEN'?403:m==='MEMBER_NOT_FOUND'?404:400;return NextResponse.json({ok:false,error:m||'Invalid request'},{status})};
export async function GET(request:Request){try{await auth('members:read');const params=new URL(request.url).searchParams;const id=params.get('id')?.trim()||'';if(id){if(id.length>64)return NextResponse.json({ok:false,error:'Membership ID is required'},{status:400});return NextResponse.json({ok:true,member:await findMember(id)},{headers:{'Cache-Control':'no-store'}})}return NextResponse.json({ok:true,members:await listMembers(params.get('q')||'')},{headers:{'Cache-Control':'no-store'}})}catch(e){return fail(e)}}
export async function POST(req:Request){try{const actor=await auth('members:write');if(actor.role!=='OWNER')throw Error('STAFF_FORBIDDEN');const b=await req.json();const member=await createMember({id:String(b.id||''),name:String(b.name||''),mobile:String(b.mobile||''),governmentIdType:b.governmentIdType,governmentIdNumber:String(b.governmentIdNumber||''),expiresAt:String(b.expiresAt||'')});await audit(actor.id,'MEMBER_CREATED','MEMBER',member?.id);return NextResponse.json({ok:true,member},{status:201})}catch(e){return fail(e)}}
export async function PATCH(req:Request){try{const actor=await auth('members:write');const b=await req.json();const id=String(b.id||'').trim();if(!id)return NextResponse.json({ok:false,error:'Member ID is required'},{status:400});const member=await updateMember(id,{name:b.name===undefined?undefined:String(b.name),mobile:b.mobile===undefined?undefined:String(b.mobile),governmentIdType:b.governmentIdType,governmentIdNumber:b.governmentIdNumber===undefined?undefined:String(b.governmentIdNumber),expiresAt:b.expiresAt===undefined?undefined:String(b.expiresAt),active:b.active===undefined?undefined:Boolean(b.active)});await audit(actor.id,'MEMBER_UPDATED','MEMBER',id);return NextResponse.json({ok:true,member})}catch(e){return fail(e)}}
