'use client';
import {useMemo,useState} from 'react';

type Receipt={receiptId:string;sessionId:string;stationId:string;customerName:string;issuedAt:string;gaming:{total:number;participants:Array<{name:string;charge:number;memberTier?:string}>};food:Array<{orderId:string;status:string;paymentMode:string;paymentStatus:string;createdAt:string;total:number;items:Array<{name:string;qty:number;unitPrice:number;participantName?:string}>}>;totals:{gaming:number;food:number;depositApplied:number;groupAllocatedGaming:number;groupAllocatedFood:number;adjustments:number;creditApplied:number;paid:number;refunded:number;outstanding:number};payments:Array<{id:string;method:string;amount:number;status:string;createdAt:string;voidedAt?:string;voidReason?:string}>;refunds:Array<{id:string;settlementId:string;amount:number;method:string;status:string;reference?:string;reason:string;createdAt:string}>};
const money=(n:number)=>`₹${Number(n||0).toLocaleString('en-IN')}`;
const newKey=()=>typeof crypto!=='undefined'&&'randomUUID'in crypto?crypto.randomUUID():`${Date.now()}-${Math.random()}`;
export default function Receipts(){
 const[id,setId]=useState(''),[receipt,setReceipt]=useState<Receipt|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[refundPayment,setRefundPayment]=useState<Receipt['payments'][number]|null>(null),[refundAmount,setRefundAmount]=useState(''),[refundMethod,setRefundMethod]=useState('CASH'),[refundReason,setRefundReason]=useState(''),[refundBusy,setRefundBusy]=useState(false);
 const load=async()=>{const sessionId=id.trim();if(!sessionId)return setError('Enter a session ID.');setBusy(true);setError('');try{const r=await fetch(`/api/sessions/receipt?sessionId=${encodeURIComponent(sessionId)}`,{cache:'no-store'}),j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'Unable to load receipt');setReceipt(j.receipt)}catch(e){setReceipt(null);setError(e instanceof Error?e.message:'Unable to load receipt')}finally{setBusy(false)}};
 const refundedByPayment=useMemo(()=>{const m=new Map<string,number>();for(const r of receipt?.refunds||[])m.set(r.settlementId,(m.get(r.settlementId)||0)+r.amount);return m},[receipt]);
 const submitRefund=async()=>{if(!refundPayment||!receipt)return;const amount=Number(refundAmount);if(!Number.isSafeInteger(amount)||amount<=0)return setError('Enter a valid refund amount.');if(amount>(refundPayment.amount-(refundedByPayment.get(refundPayment.id)||0)))return setError('Refund exceeds the remaining payment balance.');if(!refundReason.trim())return setError('Refund reason is required.');setRefundBusy(true);setError('');try{const r=await fetch('/api/session-refunds',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({settlementId:refundPayment.id,amount,method:refundMethod,reason:refundReason.trim(),idempotencyKey:newKey()})}),j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'Unable to refund payment');setRefundPayment(null);setRefundAmount('');setRefundReason('');await load()}catch(e){setError(e instanceof Error?e.message:'Unable to refund payment')}finally{setRefundBusy(false)}};
 return <><div className="top"><div><div className="eyebrow">Payments / Receipts</div><div className="title">Combined receipt</div><div className="muted">One auditable view of gaming, food, credits, deposits and payment reversals.</div></div>{receipt&&<button className="btn" onClick={()=>window.print()}>Print</button>}</div>{error&&<div className="loginError" role="alert">{error}</div>}
 <section className="section card"><div className="sectionHead"><div className="sectionTitle">Find session receipt</div><span className="muted">Staff only</span></div><div style={{display:'flex',gap:10}}><input style={{flex:1}} placeholder="Session ID" value={id} onChange={e=>setId(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')load()}}/><button className="btn primary" disabled={busy} onClick={load}>{busy?'Loading…':'Open receipt'}</button></div></section>
 {receipt&&<section className="section card" id="receipt"><div className="sectionHead"><div><div className="eyebrow">{receipt.receiptId}</div><div className="sectionTitle">GenZ Gaming Cafe</div><div className="muted">{receipt.customerName} · {receipt.stationId} · Session {receipt.sessionId}</div></div><span className="badge green">RECEIPT</span></div>
 <div className="grid4"><div><div className="statLabel">Gaming</div><b>{money(receipt.totals.gaming)}</b></div><div><div className="statLabel">Food</div><b>{money(receipt.totals.food)}</b></div><div><div className="statLabel">Paid</div><b>{money(receipt.totals.paid)}</b></div><div><div className="statLabel">Refunded</div><b>{money(receipt.totals.refunded)}</b></div></div>
 <div className="sectionTitle" style={{marginTop:18}}>Gaming</div><div className="tableWrap"><table className="table"><thead><tr><th>Participant</th><th>Tier</th><th>Charge</th></tr></thead><tbody>{receipt.gaming.participants.map((p,i)=><tr key={i}><td>{p.name}</td><td>{p.memberTier||'Regular'}</td><td>{money(p.charge)}</td></tr>)}{!receipt.gaming.participants.length&&<tr><td colSpan={3} className="muted">Session-level gaming charge</td></tr>}</tbody></table></div>
 <div className="sectionTitle" style={{marginTop:18}}>Food</div><div className="tableWrap"><table className="table"><thead><tr><th>Order</th><th>Items</th><th>Payment</th><th>Total</th></tr></thead><tbody>{receipt.food.map(o=><tr key={o.orderId}><td>{o.orderId}<br/><span className="muted">{o.status}</span></td><td>{o.items.map((x,i)=><div key={i}>{x.qty} × {x.name} {x.participantName?`· ${x.participantName}`:''}</div>)}</td><td>{o.paymentStatus}<br/><span className="muted">{o.paymentMode}</span></td><td>{money(o.total)}</td></tr>)}{!receipt.food.length&&<tr><td colSpan={4} className="muted">No food orders.</td></tr>}</tbody></table></div>
 <div className="sectionTitle" style={{marginTop:18}}>Adjustments & payments</div><div className="tableWrap"><table className="table"><tbody><tr><td>Deposit applied</td><td>{money(receipt.totals.depositApplied)}</td></tr><tr><td>Group gaming allocation</td><td>{money(receipt.totals.groupAllocatedGaming)}</td></tr><tr><td>Group food allocation</td><td>{money(receipt.totals.groupAllocatedFood)}</td></tr><tr><td>Billing adjustments</td><td>{money(receipt.totals.adjustments)}</td></tr><tr><td>Monthly credit</td><td>{money(receipt.totals.creditApplied)}</td></tr><tr><td>Outstanding</td><td><b>{money(receipt.totals.outstanding)}</b></td></tr></tbody></table></div>
 <div className="sectionTitle" style={{marginTop:18}}>Session payments</div><div className="tableWrap"><table className="table"><thead><tr><th>Time</th><th>Method</th><th>Status</th><th>Amount</th><th></th></tr></thead><tbody>{receipt.payments.map(p=>{const refunded=refundedByPayment.get(p.id)||0,remaining=Math.max(0,p.amount-refunded);return <tr key={p.id}><td>{new Date(p.createdAt).toLocaleString('en-IN')}</td><td>{p.method}</td><td>{p.status}{p.voidReason?` · ${p.voidReason}`:''}{refunded>0&&<><br/><span className="muted">Refunded {money(refunded)}</span></>}</td><td>{money(p.amount)}</td><td>{p.status==='CAPTURED'&&remaining>0&&<button className="btn" onClick={()=>{setRefundPayment(p);setRefundAmount(String(remaining));setRefundMethod(p.method);setRefundReason('')}}>Refund</button>}</td></tr>})}{!receipt.payments.length&&<tr><td colSpan={5} className="muted">No session payments.</td></tr>}</tbody></table></div>
 <div className="sectionTitle" style={{marginTop:18}}>Refunds</div><div className="tableWrap"><table className="table"><thead><tr><th>Time</th><th>Payment</th><th>Method</th><th>Reason</th><th>Amount</th></tr></thead><tbody>{receipt.refunds.map(r=><tr key={r.id}><td>{new Date(r.createdAt).toLocaleString('en-IN')}</td><td>{r.settlementId}</td><td>{r.method}</td><td>{r.reason}</td><td>{money(r.amount)}</td></tr>)}{!receipt.refunds.length&&<tr><td colSpan={5} className="muted">No refunds.</td></tr>}</tbody></table></div>
 </section>}
 {refundPayment&&<div className="section card" style={{border:'1px solid currentColor'}}><div className="sectionHead"><div><div className="eyebrow">Payment refund</div><div className="sectionTitle">Refund {refundPayment.id}</div><div className="muted">Maximum remaining refund: {money(Math.max(0,refundPayment.amount-(refundedByPayment.get(refundPayment.id)||0)))}</div></div><button className="btn" onClick={()=>setRefundPayment(null)}>Cancel</button></div><div style={{display:'grid',gap:10,maxWidth:620}}><input type="number" min="1" step="1" value={refundAmount} onChange={e=>setRefundAmount(e.target.value)} placeholder="Refund amount (₹)"/><select value={refundMethod} onChange={e=>setRefundMethod(e.target.value)}><option value="CASH">Cash</option><option value="UPI">UPI</option><option value="CARD">Card</option><option value="RAZORPAY">Razorpay</option><option value="OTHER">Other</option></select><input value={refundReason} onChange={e=>setRefundReason(e.target.value)} placeholder="Reason (required)" maxLength={255}/><button className="btn primary" disabled={refundBusy} onClick={submitRefund}>{refundBusy?'Processing…':'Confirm refund'}</button></div></div>}
 </>}
