'use client';
import {useCallback,useEffect,useState} from 'react';
type R={date:string;status:string;approvalStatus:string;tenderGross:number;tenderNet:number;refundTotal:number;operatingExpenseTotal:number;cashDrawerNet:number;actualCash:number|null;cashVariance:number|null;earnedRevenue:number;creditSales:number;creditRepayments:number;bookingDeposits:number;reconciliationDifference:number;unresolvedExceptions:number;unresolvedExceptionReasons:string[];tenders:Record<string,number>;refunds:Record<string,number>};
const money=(n:number)=>`₹${Number(n||0).toLocaleString('en-IN')}`,methods=['CASH','UPI','CARD','RAZORPAY','OTHER'];const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
export default function DailyClose(){const[date,setDate]=useState(today),[data,setData]=useState<R|null>(null),[cash,setCash]=useState(''),[notes,setNotes]=useState(''),[events,setEvents]=useState<any[]>([]),[period,setPeriod]=useState('day'),[periodReport,setPeriodReport]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{setBusy(true);try{const r=await fetch(`/api/daily-close?date=${date}`,{cache:'no-store'}),j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'Unable to load');setData(j.report);setCash(j.report.actualCash===null?'':String(j.report.actualCash));const e=await fetch(`/api/daily-close?date=${date}&action=events`),ej=await e.json();setEvents(ej.events||[])}catch(e){setError(e instanceof Error?e.message:'Unable to load')}finally{setBusy(false)}},[date]);useEffect(()=>{load()},[load]);
 const post=async(action:string)=>{setError('');try{const r=await fetch('/api/daily-close',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,date,countedCash:Number(cash),notes})}),j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'Operation failed');setData(j.report);await load()}catch(e){setError(e instanceof Error?e.message:'Operation failed')}};
 const save=()=>{if(!Number.isSafeInteger(Number(cash))||Number(cash)<0)return setError('Enter a valid cash count.');return post('count')};
 const loadReport=async()=>{try{const r=await fetch(`/api/finance/reports?date=${date}&period=${period}`),j=await r.json();if(!r.ok||!j.ok)throw Error(j.error);setPeriodReport(j.report)}catch(e){setError(e instanceof Error?e.message:'Unable to load report')}};
 return <><div className="top"><div><div className="eyebrow">Finance / Reconciliation</div><div className="title">Daily close</div><div className="muted">Cash count → reconciliation → OWNER approval → locked period.</div></div><div className="actions"><input type="date" value={date} onChange={e=>setDate(e.target.value)}/><button className="btn" onClick={load} disabled={busy}>Refresh</button><a className="btn" href={`/api/daily-close?date=${date}&format=csv`}>Export CSV</a></div></div>{error&&<div className="loginError">{error}</div>}{data&&<>
 <div className="grid4">{[['Tender gross',data.tenderGross],['Tender net',data.tenderNet],['Cash drawer net',data.cashDrawerNet],['Cash variance',data.cashVariance??0]].map(([k,v])=><div className="card" key={String(k)}><div className="statLabel">{k}</div><div className="stat">{data.cashVariance===null&&k==='Cash variance'?'—':money(Number(v))}</div></div>)}</div>
 <section className="section card"><div className="sectionHead"><div><div className="sectionTitle">Close control</div><div className="muted">MANAGER records the physical count. OWNER approves or reopens. Approved periods are database-locked.</div></div><span className="badge">{data.status}</span></div>{data.unresolvedExceptions>0&&<div className="danger">Closing blocked: {data.unresolvedExceptionReasons.join(' • ')}</div>}<div style={{display:'grid',gap:10,maxWidth:620,marginTop:12}}><input type="number" min="0" step="1" placeholder="Counted cash ₹" value={cash} onChange={e=>setCash(e.target.value)} disabled={data.approvalStatus==='APPROVED'}/><input placeholder="Cash count / reopen notes" maxLength={500} value={notes} onChange={e=>setNotes(e.target.value)}/><div className="actions"><button className="btn primary" onClick={save} disabled={data.approvalStatus==='APPROVED'}>Record cash count</button>{data.status==='BALANCED'&&<button className="btn primary" onClick={()=>post('approve')}>Approve close (OWNER)</button>}{data.approvalStatus==='APPROVED'&&<button className="btn" onClick={()=>post('reopen')}>Reopen close (OWNER)</button>}</div></div></section>
 <section className="section card"><div className="sectionTitle">Accounting checks</div><table className="table"><tbody>{[['Earned revenue',data.earnedRevenue],['Tender net',data.tenderNet],['Credit sales',data.creditSales],['Credit repayments',data.creditRepayments],['Booking deposits',data.bookingDeposits],['Reconciliation difference',data.reconciliationDifference],['Refunds / reversals',data.refundTotal],['Operating expenses',data.operatingExpenseTotal]].map(([k,v])=><tr key={String(k)}><td>{k}</td><td><b>{money(Number(v))}</b></td></tr>)}</tbody></table></section>
 <section className="section card"><div className="sectionTitle">Tender breakdown</div><table className="table"><thead><tr><th>Method</th><th>Captured</th><th>Refunds</th><th>Net</th></tr></thead><tbody>{methods.map(m=><tr key={m}><td>{m}</td><td>{money(data.tenders[m])}</td><td>{money(data.refunds[m])}</td><td>{money(data.tenders[m]-data.refunds[m])}</td></tr>)}</tbody></table></section>
 <section className="section card"><div className="sectionHead"><div><div className="sectionTitle">Daily / weekly / monthly reports</div><div className="muted">Management reporting with CSV export.</div></div><div className="actions"><select value={period} onChange={e=>setPeriod(e.target.value)}><option value="day">Daily</option><option value="week">Weekly</option><option value="month">Monthly</option></select><button className="btn" onClick={loadReport}>Load</button><a className="btn" href={`/api/finance/reports?date=${date}&period=${period}&format=csv`}>Export</a></div></div>{periodReport&&<div className="grid4">{[['Revenue',periodReport.totals.revenue],['Expenses',periodReport.totals.expenses],['Refunds',periodReport.totals.refunds],['Credit sales',periodReport.totals.creditSales]].map(([k,v])=><div className="card" key={String(k)}><div className="statLabel">{k}</div><div className="stat">{money(Number(v))}</div></div>)}</div>}</section>
 <section className="section card"><div className="sectionTitle">Cash drawer audit trail</div><table className="table"><thead><tr><th>Time</th><th>Action</th><th>Staff</th><th>Count</th><th>Variance</th><th>Notes</th></tr></thead><tbody>{events.map(e=><tr key={e.id}><td>{new Date(e.created_at).toLocaleString()}</td><td>{e.action}</td><td>{e.staff_id||'—'}</td><td>{e.counted_cash==null?'—':money(Number(e.counted_cash))}</td><td>{e.cash_variance==null?'—':money(Number(e.cash_variance))}</td><td>{e.notes||'—'}</td></tr>)}{!events.length&&<tr><td colSpan={6} className="muted">No close events yet.</td></tr>}</tbody></table></section></>}</>}
