'use client';
import {useCallback,useEffect,useState} from 'react';
type Report={date:string;status:string;approvalStatus:string;approvedBy?:string;approvedAt?:string;tenders:Record<string,number>;tenderGross:number;refunds:Record<string,number>;refundTotal:number;tenderNet:number;operatingExpenses:Record<string,number>;operatingExpenseTotal:number;cashDrawerNet:number;actualCash:number|null;cashVariance:number|null;earnedRevenue:number;creditSales:number;creditRepayments:number;bookingDeposits:number;reconciliationDifference:number;categoryBreakdown:Array<{category:string;method:string;amount:number}>};
const money=(n:number)=>`₹${Number(n||0).toLocaleString('en-IN')}`,methods=['CASH','UPI','CARD','RAZORPAY','OTHER'];
const localDate=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
export default function DailyClose(){const[date,setDate]=useState(localDate),[data,setData]=useState<Report|null>(null),[countedCash,setCountedCash]=useState(''),[notes,setNotes]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[saveBusy,setSaveBusy]=useState(false),[approveBusy,setApproveBusy]=useState(false);
 const load=useCallback(async()=>{setBusy(true);setError('');try{const r=await fetch(`/api/daily-close?date=${encodeURIComponent(date)}`,{cache:'no-store'}),j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'Unable to load daily close');setData(j.report);setCountedCash(j.report.actualCash===null?'':String(j.report.actualCash))}catch(e){setError(e instanceof Error?e.message:'Unable to load daily close')}finally{setBusy(false)}},[date]);useEffect(()=>{load()},[load]);
 const saveCount=async()=>{const amount=Number(countedCash);if(!Number.isSafeInteger(amount)||amount<0)return setError('Enter a valid counted cash amount.');setSaveBusy(true);setError('');try{const r=await fetch('/api/daily-close',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'count',date,countedCash:amount,notes})}),j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'Unable to save cash count');setData(j.report)}catch(e){setError(e instanceof Error?e.message:'Unable to save cash count')}finally{setSaveBusy(false)}};
 const approve=async()=>{setApproveBusy(true);setError('');try{const r=await fetch('/api/daily-close',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'approve',date})}),j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'Unable to approve close');setData(j.report)}catch(e){setError(e instanceof Error?e.message:'Unable to approve close')}finally{setApproveBusy(false)}};
 return <><div className="top"><div><div className="eyebrow">Finance / Reconciliation</div><div className="title">Daily close</div><div className="muted">Tender, refund, expense and earned-revenue view for one business day.</div></div><div className="actions"><input type="date" value={date} onChange={e=>setDate(e.target.value)}/><button className="btn" onClick={load} disabled={busy}>{busy?'Refreshing…':'Refresh'}</button></div></div>{error&&<div className="loginError" role="alert">{error}</div>}{data&&<>
 <div className="grid4"><div className="card"><div className="statLabel">Tender gross</div><div className="stat">{money(data.tenderGross)}</div><div className="delta">All captured tenders</div></div><div className="card"><div className="statLabel">Refunds / reversals</div><div className="stat">{money(data.refundTotal)}</div><div className="danger">Outflows</div></div><div className="card"><div className="statLabel">Tender net</div><div className="stat">{money(data.tenderNet)}</div><div className="delta">Gross − refunds</div></div><div className="card"><div className="statLabel">Cash drawer net</div><div className="stat">{money(data.cashDrawerNet)}</div><div className="delta">Cash tenders − cash outflows</div></div></div>
 <section className="section card"><div className="sectionHead"><div><div className="sectionTitle">Cash count & approval</div><div className="muted">A close can only be approved after the counted drawer and ledger timing reconcile exactly. Approval is OWNER-only.</div></div><span className={`badge ${data.approvalStatus==='APPROVED'?'green':data.cashVariance===0?'yellow':'yellow'}`}>{data.approvalStatus==='APPROVED'?'APPROVED':data.cashVariance===null?'COUNT REQUIRED':data.cashVariance===0?'READY FOR APPROVAL':`VARIANCE ${money(data.cashVariance)}`}</span></div><div style={{display:'grid',gap:10,maxWidth:620}}><input type="number" min="0" step="1" placeholder="Counted cash ₹" value={countedCash} onChange={e=>setCountedCash(e.target.value)} disabled={data.approvalStatus==='APPROVED'}/><input placeholder="Close notes (optional)" maxLength={255} value={notes} onChange={e=>setNotes(e.target.value)} disabled={data.approvalStatus==='APPROVED'}/><div className="actions"><button className="btn primary" disabled={saveBusy||data.approvalStatus==='APPROVED'} onClick={saveCount}>{saveBusy?'Saving…':'Save cash count'}</button>{data.status==='BALANCED'&&data.approvalStatus!=='APPROVED'&&<button className="btn primary" disabled={approveBusy} onClick={approve}>{approveBusy?'Approving…':'Approve daily close'}</button>}</div>{data.approvalStatus==='APPROVED'&&data.approvedAt&&<div className="muted">Approved {new Date(data.approvedAt).toLocaleString()}</div>}</div></section>
 <section className="section card"><div className="sectionHead"><div><div className="sectionTitle">Reconciliation</div><div className="muted">Earned revenue excludes booking-deposit advances and credit repayments. Credit sales are earned revenue without same-day tender.</div></div><span className={`badge ${data.status==='BALANCED'||data.status==='APPROVED'?'green':'yellow'}`}>{data.status}</span></div><table className="table"><tbody><tr><td>Earned revenue</td><td>{money(data.earnedRevenue)}</td></tr><tr><td>Tender net</td><td>{money(data.tenderNet)}</td></tr><tr><td>Timing difference</td><td><b>{money(data.reconciliationDifference)}</b></td></tr><tr><td>Credit sales (non-cash)</td><td>{money(data.creditSales)}</td></tr><tr><td>Credit repayments (tender)</td><td>{money(data.creditRepayments)}</td></tr><tr><td>Booking deposits (advance)</td><td>{money(data.bookingDeposits)}</td></tr></tbody></table></section>
 <section className="section card"><div className="sectionTitle">Tender breakdown</div><table className="table"><thead><tr><th>Method</th><th>Captured</th><th>Refunds / reversals</th><th>Net</th></tr></thead><tbody>{methods.map(m=><tr key={m}><td>{m}</td><td>{money(data.tenders[m])}</td><td>{money(data.refunds[m])}</td><td><b>{money(data.tenders[m]-data.refunds[m])}</b></td></tr>)}</tbody></table></section>
 <section className="section card"><div className="sectionTitle">Operating expenses</div><table className="table"><thead><tr><th>Method</th><th>Amount</th></tr></thead><tbody>{methods.map(m=><tr key={m}><td>{m}</td><td>{money(data.operatingExpenses[m])}</td></tr>)}<tr><td><b>Total</b></td><td><b>{money(data.operatingExpenseTotal)}</b></td></tr></tbody></table></section>
 <section className="section card"><div className="sectionTitle">Revenue source breakdown</div><table className="table"><thead><tr><th>Category</th><th>Method</th><th>Amount</th></tr></thead><tbody>{data.categoryBreakdown.map((x,i)=><tr key={i}><td>{x.category}</td><td>{x.method}</td><td>{money(x.amount)}</td></tr>)}{!data.categoryBreakdown.length&&<tr><td colSpan={3} className="muted">No earned-revenue entries for this date.</td></tr>}</tbody></table></section></>}</>}
