'use client';
import {useCallback,useEffect,useState} from 'react';

type Report={date:string;status:string;tenders:Record<string,number>;tenderGross:number;refunds:Record<string,number>;refundTotal:number;tenderNet:number;operatingExpenses:Record<string,number>;operatingExpenseTotal:number;cashDrawerNet:number;earnedRevenue:number;creditSales:number;creditRepayments:number;bookingDeposits:number;reconciliationDifference:number;categoryBreakdown:Array<{category:string;method:string;amount:number}>};
const money=(n:number)=>`₹${Number(n||0).toLocaleString('en-IN')}`;
const methods=['CASH','UPI','CARD','RAZORPAY','OTHER'];
export default function DailyClose(){
 const today=new Date().toISOString().slice(0,10);const[date,setDate]=useState(today),[data,setData]=useState<Report|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{setBusy(true);setError('');try{const r=await fetch(`/api/daily-close?date=${encodeURIComponent(date)}`,{cache:'no-store'}),j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'Unable to load daily close');setData(j.report)}catch(e){setError(e instanceof Error?e.message:'Unable to load daily close')}finally{setBusy(false)}},[date]);
 useEffect(()=>{load()},[load]);
 return <><div className="top"><div><div className="eyebrow">Finance / Reconciliation</div><div className="title">Daily close</div><div className="muted">Tender, refund, expense and earned-revenue view for one business day.</div></div><div className="actions"><input type="date" value={date} onChange={e=>setDate(e.target.value)}/><button className="btn" onClick={load} disabled={busy}>{busy?'Refreshing…':'Refresh'}</button></div></div>{error&&<div className="loginError" role="alert">{error}</div>}{data&&<>
 <div className="grid4"><div className="card"><div className="statLabel">Tender gross</div><div className="stat">{money(data.tenderGross)}</div><div className="delta">All captured tenders</div></div><div className="card"><div className="statLabel">Refunds / reversals</div><div className="stat">{money(data.refundTotal)}</div><div className="danger">Outflows</div></div><div className="card"><div className="statLabel">Tender net</div><div className="stat">{money(data.tenderNet)}</div><div className="delta">Gross − refunds</div></div><div className="card"><div className="statLabel">Cash drawer net</div><div className="stat">{money(data.cashDrawerNet)}</div><div className="delta">Cash tenders − cash outflows</div></div></div>
 <section className="section card"><div className="sectionHead"><div><div className="sectionTitle">Reconciliation</div><div className="muted">Earned revenue excludes booking-deposit advances and credit repayments. Credit sales are earned revenue without same-day tender.</div></div><span className={`badge ${data.status==='BALANCED'?'green':'yellow'}`}>{data.status}</span></div><table className="table"><tbody><tr><td>Earned revenue</td><td>{money(data.earnedRevenue)}</td></tr><tr><td>Tender net</td><td>{money(data.tenderNet)}</td></tr><tr><td>Timing difference</td><td><b>{money(data.reconciliationDifference)}</b></td></tr><tr><td>Credit sales (non-cash)</td><td>{money(data.creditSales)}</td></tr><tr><td>Credit repayments (tender)</td><td>{money(data.creditRepayments)}</td></tr><tr><td>Booking deposits (advance)</td><td>{money(data.bookingDeposits)}</td></tr></tbody></table></section>
 <section className="section card"><div className="sectionTitle">Tender breakdown</div><table className="table"><thead><tr><th>Method</th><th>Captured</th><th>Refunds / reversals</th><th>Net</th></tr></thead><tbody>{methods.map(m=><tr key={m}><td>{m}</td><td>{money(data.tenders[m])}</td><td>{money(data.refunds[m])}</td><td><b>{money(data.tenders[m]-data.refunds[m])}</b></td></tr>)}</tbody></table></section>
 <section className="section card"><div className="sectionTitle">Operating expenses</div><table className="table"><thead><tr><th>Method</th><th>Amount</th></tr></thead><tbody>{methods.map(m=><tr key={m}><td>{m}</td><td>{money(data.operatingExpenses[m])}</td></tr>)}<tr><td><b>Total</b></td><td><b>{money(data.operatingExpenseTotal)}</b></td></tr></tbody></table></section>
 <section className="section card"><div className="sectionTitle">Revenue source breakdown</div><table className="table"><thead><tr><th>Category</th><th>Method</th><th>Amount</th></tr></thead><tbody>{data.categoryBreakdown.map((x,i)=><tr key={i}><td>{x.category}</td><td>{x.method}</td><td>{money(x.amount)}</td></tr>)}{!data.categoryBreakdown.length&&<tr><td colSpan={3} className="muted">No earned-revenue entries for this date.</td></tr>}</tbody></table></section>
 </>}</>;
}
