'use client';
import {useCallback,useEffect,useState} from 'react';
type Item={itemId:string;name:string;qty:number;unitPrice:number};type Order={id:string;sessionId:string;stationId:string;items:Item[];status:'NEW'|'ACCEPTED'|'PREPARING'|'READY'|'DELIVERED'|'CANCELLED';paymentMode:string;paymentStatus:string;createdAt:string;total:number};
const columns:Order['status'][]=['NEW','ACCEPTED','PREPARING','READY'];
const nextLabel:Record<string,string>={NEW:'Accept',ACCEPTED:'Start preparing',PREPARING:'Mark ready',READY:'Deliver'};
export default function Kitchen(){const[orders,setOrders]=useState<Order[]>([]);const[error,setError]=useState('');const[busy,setBusy]=useState('');
 const load=useCallback(async()=>{const r=await fetch('/api/orders',{cache:'no-store'});const j=await r.json();if(!r.ok)throw Error(j.error||'Unable to load kitchen orders');setOrders(j.orders||[])},[]);
 useEffect(()=>{load().catch(e=>setError(e.message));const t=setInterval(()=>load().catch(()=>{}),5000);return()=>clearInterval(t)},[load]);
 async function advance(id:string){setBusy(id);setError('');try{const r=await fetch('/api/orders',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({orderId:id})});const j=await r.json();if(!r.ok)throw Error(j.error||'Unable to update order');setOrders(old=>old.map(o=>o.id===id?{...o,status:j.order.status}:o))}catch(e){setError(e instanceof Error?e.message:'Unable to update order')}finally{setBusy('')}}
 async function cancel(id:string){if(!confirm('Cancel this food order?'))return;setBusy(id);setError('');try{const r=await fetch('/api/orders',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({orderId:id,action:'cancel'})});const j=await r.json();if(!r.ok)throw Error(j.error||'Unable to cancel order');setOrders(old=>old.map(o=>o.id===id?{...o,status:'CANCELLED'}:o))}catch(e){setError(e instanceof Error?e.message:'Unable to cancel order')}finally{setBusy('')}}
 const active=orders.filter(o=>columns.includes(o.status));const newCount=orders.filter(o=>o.status==='NEW').length;return <><div className="top"><div><div className="eyebrow">Kitchen / KDS</div><div className="title">Kitchen queue</div><div className="muted">Live orders from every active gaming session.</div></div><div className="actions"><span className="badge red">● {newCount} NEW</span><button className="btn" onClick={()=>load().catch(e=>setError(e.message))}>Refresh</button></div></div>{error&&<div className="card" style={{marginBottom:16}} role="alert">{error}</div>}<div style={{display:'grid',gridTemplateColumns:'repeat(4,minmax(240px,1fr))',gap:12,overflowX:'auto'}}>{columns.map(status=>{const items=orders.filter(o=>o.status===status);return <section className="card" key={status}><div className="sectionHead"><div className="sectionTitle">{status}</div><span className={'badge '+(status==='NEW'?'red':status==='READY'?'green':'amber')}>{items.length}</span></div>{items.map(o=><article className="order" key={o.id} style={{display:'block',marginBottom:10}}><div style={{display:'flex',justifyContent:'space-between',gap:8}}><div><div className="orderName">{o.items.map(i=>`${i.qty}× ${i.name}`).join(' · ')}</div><div className="orderSub">{o.id.slice(-8)} · {o.stationId} · ₹{o.total}</div><div className="muted">{new Date(o.createdAt).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'})} · {o.paymentStatus}</div></div><button className="btn primary" disabled={busy===o.id} onClick={()=>advance(o.id)}>{busy===o.id?'…':nextLabel[status]}</button></div>{status==='NEW'&&<button className="btn" style={{marginTop:8}} disabled={busy===o.id} onClick={()=>cancel(o.id)}>Cancel</button>}</article>)}{!items.length&&<div className="muted" style={{padding:'20px 4px'}}>Nothing here.</div>}</section>})}</div>{orders.some(o=>o.status==='DELIVERED')&&<div className="muted" style={{marginTop:12}}>Delivered orders remain in history; {orders.filter(o=>o.status==='DELIVERED').length} delivered today.</div>}{!active.length&&<div className="card" style={{marginTop:12}}>No active kitchen orders.</div>}</>}
