import {NextResponse} from 'next/server';
import {cookies} from 'next/headers';
import {createSessionGroup,getSessionGroup,listSessionGroups,closeSessionGroup} from '../../../lib/session-groups';
import {getGroupSettlement,settleGroup} from '../../../lib/session-group-settlement';
import {COOKIE,requireStaff,audit} from '../../../lib/staff-auth';
const authError=(e:unknown)=>{const m=e instanceof Error?e.message:'';return NextResponse.json({ok:false,error:m==='STAFF_FORBIDDEN'?'Permission denied':'Staff authorization required'},{status:m==='STAFF_FORBIDDEN'?403:401});};
export async function GET(req:Request){try{await requireStaff((await cookies()).get(COOKIE)?.value,'sessions:read');const id=new URL(req.url).searchParams.get('id');if(id&&new URL(req.url).searchParams.get('settlement')==='1')return NextResponse.json({ok:true,settlement:await getGroupSettlement(id)},{headers:{'Cache-Control':'no-store'}});return NextResponse.json({ok:true,groups:id?[await getSessionGroup(id)]:await listSessionGroups()},{headers:{'Cache-Control':'no-store'}})}catch(e){return authError(e)}}
export async function POST(req:Request){try{const staff=await requireStaff((await cookies()).get(COOKIE)?.value,'sessions:write');const b=await req.json();if(b?.action==='settle'){if(typeof b.groupId!=='string'||!['CASH','UPI','CARD','RAZORPAY','OTHER'].includes(b.method))return NextResponse.json({ok:false,error:'Invalid settlement request'},{status:400});const result=await settleGroup({groupId:b.groupId,method:b.method,staffId:staff.id,payers:Array.isArray(b.payers)?b.payers:[],allocations:Array.isArray(b.allocations)?b.allocations:undefined});await audit(staff.id,'GROUP_SETTLEMENT_CAPTURED','session_group',b.groupId,{settlementId:result.settlementId,amount:result.amount,method:result.method});return NextResponse.json({ok:true,settlement:result},{status:201});}
 if(!Array.isArray(b?.sessionIds))return NextResponse.json({ok:false,error:'sessionIds required'},{status:400});const group=await createSessionGroup(b.sessionIds,typeof b.name==='string'?b.name:undefined);await audit(staff.id,'SESSION_GROUP_CREATED','session_group',group.id,{sessionIds:group.sessionIds});return NextResponse.json({ok:true,group},{status:201})}catch(e){if(e instanceof Error&&(e.message==='STAFF_UNAUTHORIZED'||e.message==='STAFF_FORBIDDEN'))return authError(e);return NextResponse.json({ok:false,error:e instanceof Error?e.message:'Unable to update group'},{status:400})}}
export async function PATCH(req:Request){try{const staff=await requireStaff((await cookies()).get(COOKIE)?.value,'sessions:write');const b=await req.json();if(typeof b?.groupId!=='string')return NextResponse.json({ok:false,error:'groupId required'},{status:400});const group=await closeSessionGroup(b.groupId);await audit(staff.id,'SESSION_GROUP_CLOSED','session_group',b.groupId);return NextResponse.json({ok:true,group})}catch(e){if(e instanceof Error&&(e.message==='STAFF_UNAUTHORIZED'||e.message==='STAFF_FORBIDDEN'))return authError(e);return NextResponse.json({ok:false,error:e instanceof Error?e.message:'Unable to close group'},{status:400})}}
