'use client';
import {useEffect,useState} from 'react';
import QRCode from 'qrcode';

type Station={id:string;name:string;type:string;status:string;hourlyRate:number;slotMinutes:number};
const base=()=>typeof window==='undefined'?'':window.location.origin;
const money=(n:number)=>`₹${Number(n||0).toLocaleString('en-IN')}`;

export default function StationsPage(){
 const[stations,setStations]=useState<Station[]>([]);const[qr,setQr]=useState<Record<string,string>>({});const[loading,setLoading]=useState(true);const[error,setError]=useState('');
 useEffect(()=>{(async()=>{try{const r=await fetch('/api/stations',{cache:'no-store'});const j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'Unable to load stations');setStations(j.stations||[])}catch(e){setError(e instanceof Error?e.message:'Unable to load stations')}finally{setLoading(false)}})()},[]);
 useEffect(()=>{if(!stations.length)return;let cancelled=false;(async()=>{try{const entries=await Promise.all(stations.map(async s=>[s.id,await QRCode.toDataURL(`${base()}/customer?stationId=${encodeURIComponent(s.id)}`,{width:320,margin:2,errorCorrectionLevel:'M'})] as const));if(!cancelled)setQr(Object.fromEntries(entries))}catch(e){if(!cancelled)setError(e instanceof Error?e.message:'Unable to generate QR codes')}})();return()=>{cancelled=true}},[stations]);
 const print=()=>window.print();
 return <main className="page"><div className="pageHeader"><div><div className="eyebrow">ADMIN · STATIONS</div><h1>Stations & QR</h1><p className="muted">Permanent QR labels identify equipment only. They cannot bind a customer to a session; the station must display a live, short-lived QR from the trusted station agent.</p></div><div className="actions"><button className="btn primary" onClick={print} disabled={!stations.length}>Print QR sheet</button></div></div>{error&&<div className="card loginError">{error}</div>}{loading?<div className="card">Loading stations…</div>:<section className="stationQrGrid">{stations.map(s=><article className="card stationQr" key={s.id}><div className="sectionHead"><div><div className="stationId">{s.name}</div><div className="muted">{s.type} · {s.id}</div></div><span className={'badge '+(s.status==='AVAILABLE'?'green':s.status==='ACTIVE'?'cyan':'red')}>{s.status}</span></div>{qr[s.id]?<img src={qr[s.id]} className="qrImage" alt={`Permanent identification QR for ${s.name}`}/>:<div className="qrPlaceholder">Generating QR…</div>}<div className="qrLabel">STATION ID · {s.name.toUpperCase()}</div><div className="muted">Not an authorization QR · Gaming rate: {money(s.hourlyRate)}/hour · Slot: {s.slotMinutes} min</div></article>)}</section>}{!loading&&!stations.length&&<div className="card muted">No stations configured.</div>}<style jsx>{`@media print{.pageHeader,.loginError{display:none!important}.page{padding:0}.stationQrGrid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.stationQr{break-inside:avoid;box-shadow:none;border:1px solid #ddd;color:#000}.stationQr .muted{color:#333}.badge{display:none}}.stationQrGrid{display:grid;grid-template-columns:repeat(auto-fill,minmax(260px,1fr));gap:16px}.stationQr{text-align:center}.qrImage{width:min(260px,100%);height:auto;display:block;margin:16px auto}.qrPlaceholder{height:260px;display:grid;place-items:center;margin:16px;border:1px dashed #666}.qrLabel{font-weight:800;letter-spacing:1px;margin-bottom:8px}`}</style></main>;
}
