'use client';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {useEffect,useMemo,useState} from 'react';
type Role='OWNER'|'MANAGER'|'DEVELOPER';
type Staff={name:string;username:string;role:Role};
type NavItem={href:string;label:string;permission?:string;ownerOnly?:boolean;developerOnly?:boolean;feature?:string};
const nav:NavItem[]=[{href:'/',label:'Dashboard',permission:'sessions:read',feature:'dashboard'},{href:'/sessions',label:'Sessions',permission:'sessions:read',feature:'sessions'},{href:'/settlements',label:'Settlements',permission:'finance:read',feature:'finance'},{href:'/receipts',label:'Receipts',permission:'finance:read',feature:'receipts'},{href:'/daily-close',label:'Daily Close',permission:'daily_close:count',feature:'finance'},{href:'/reconciliation',label:'Reconciliation',permission:'finance:read',feature:'finance'},{href:'/provider-reconciliation',label:'Provider Reconciliation',permission:'finance:read',feature:'finance'},{href:'/bookings',label:'Bookings',permission:'bookings:read',feature:'bookings'},{href:'/orders',label:'Food Orders',permission:'orders:read',feature:'food_orders'},{href:'/kitchen',label:'Kitchen',permission:'orders:read',feature:'kitchen'},{href:'/inventory',label:'Inventory',permission:'inventory:read',feature:'inventory'},{href:'/finance',label:'Finance',permission:'finance:read',feature:'finance'},{href:'/members',label:'Members',permission:'members:read',feature:'members'},{href:'/stations',label:'Stations',permission:'sessions:read',feature:'stations'},{href:'/staff',label:'Staff',ownerOnly:true,feature:'staff_management'},{href:'/admin',label:'Admin',ownerOnly:true,feature:'admin_configuration'},{href:'/developer',label:'Developer Console',developerOnly:true}];
const permissions:Record<Role,Set<string>>={OWNER:new Set(['*']),MANAGER:new Set(['sessions:read','sessions:write','orders:read','orders:write','bookings:read','bookings:write','members:read','finance:read','daily_close:count','inventory:read','inventory:write','payments:read','payments:write','credit:read','credit:write']),DEVELOPER:new Set(['sessions:read','orders:read','bookings:read','finance:read','inventory:read','members:read','payments:read','audit:read','developer:manage'])};
function canSee(item:NavItem,role:Role,flags:Record<string,boolean>){if(item.ownerOnly)return role==='OWNER'&&flags[item.feature||'']!==false;if(item.developerOnly)return role==='OWNER'||role==='DEVELOPER';return (role==='OWNER'||(!item.ownerOnly&&(!item.permission||permissions[role].has(item.permission))))&&flags[item.feature||'']!==false}
export default function StaffShell({children}:{children:React.ReactNode}){const pathname=usePathname();const[staff,setStaff]=useState<Staff|null>(null);const[flags,setFlags]=useState<Record<string,boolean>>({});const publicSurface=pathname.startsWith('/customer')||pathname.startsWith('/staff-login');useEffect(()=>{if(publicSurface){setStaff(null);return}let cancelled=false;Promise.all([fetch('/api/staff/me',{cache:'no-store'}),fetch('/api/features',{cache:'no-store'})]).then(async([s,f])=>{const sd=s.ok?(await s.json()).staff:null;const fd=f.ok?(await f.json()).features:{};if(!cancelled){setStaff(sd||null);setFlags(fd||{})}}).catch(()=>{if(!cancelled){setStaff(null);setFlags({})}});return()=>{cancelled=true}},[publicSurface]);const visible=useMemo(()=>staff?nav.filter(item=>canSee(item,staff.role,flags)):nav.filter(item=>!item.ownerOnly&&!item.developerOnly&&flags[item.feature||'']!==false),[staff,flags]);const gated=nav.find(item=>item.href!=='/developer'&&(pathname===item.href||pathname.startsWith(`${item.href}/`)));if(publicSurface)return <>{children}</>;if(gated&&flags[gated.feature||'']===false)return <div className="app"><aside className="side"><div className="brand">GenZ <span>Gaming Cafe</span></div><nav className="nav">{visible.map(item=><Link className={pathname===item.href||pathname.startsWith(`${item.href}/`)?'active':''} key={item.href} href={item.href}>{item.label}</Link>)}</nav></aside><main className="main"><div className="card danger"><div className="sectionTitle">Feature disabled</div><p className="muted">This feature has been temporarily disabled by an Owner/Developer. Existing data has not been deleted.</p><Link className="btn" href="/developer">Open Developer Console</Link></div></main></div>;return <div className="app"><aside className="side"><div className="brand">GenZ <span>Gaming Cafe</span></div><nav className="nav">{visible.map(item=><Link className={pathname===item.href||pathname.startsWith(`${item.href}/`)?'active':''} key={item.href} href={item.href}>{item.label}</Link>)}</nav><div className="sideBottom">{staff&&<><b>{staff.name}</b><br/><span className="muted">{staff.role} · {staff.username}</span><br/><br/></>}<b className="yellow">● LAN MODE</b><br/>Core operations are designed to keep working locally when the internet is unavailable.<br/><br/><span className="badge green">SYSTEM ONLINE</span></div></aside><main className="main">{children}</main></div>}
