'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';
import StartSessionButton from './StartSessionButton';
import ParticipantManager from './ParticipantManager';
type Session={id:string;stationId:string;customerName:string;status:'ACTIVE'|'PAUSED'|'ENDED';startedAt:string;scheduledEndAt?:string;balance:number};
type Station={id:string;name:string;type:string;status:'AVAILABLE'|'BOOKED'|'ACTIVE'|'MAINTENANCE'|'BLOCKED';hourlyRate:number;slotMinutes:number};
type Group={id:string;name:string;sessionCount:number;total:number;sessionIds?:string[]};
type Source={sourceType:'GAMING_SESSION'|'FOOD_ORDER_ITEM';sourceId:string;sessionId:string;orderId?:string;label:string;outstanding:number};
const money=(n:number)=>`₹${Number(n||0).toLocaleString('en-IN')}`;const time=(v?:string)=>v?new Date(v).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'}):'—';const cls=(s:string)=>s==='ACTIVE'?'green':s==='MAINTENANCE'||s==='BLOCKED'?'red':'';
export default function Sessions(){
 const[sessions,setSessions]=useState<Session[]>([]),[stations,setStations]=useState<Station[]>([]),[groups,setGroups]=useState<Group[]>([]),[selected,setSelected]=useState<string[]>([]),[grouping,setGrouping]=useState(false),[manage,setManage]=useState<string|null>(null),[settleGroup,setSettleGroup]=useState<Group|null>(null),[sources,setSources]=useState<Source[]>([]),[strategy,setStrategy]=useState('ONE'),[payerCount,setPayerCount]=useState(2),[method,setMethod]=useState('CASH'),[payerNames,setPayerNames]=useState<string[]>(['Payer 1','Payer 2']),[busy,setBusy]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 const load=useCallback(async()=>{try{const[a,b,c]=await Promise.all([fetch('/api/sessions',{cache:'no-store'}),fetch('/api/stations',{cache:'no-store'}),fetch('/api/session-groups',{cache:'no-store'})]);const[sj,stj,gj]=await Promise.all([a.json(),b.json(),c.json()]);if(!a.ok||!sj.ok)throw Error(sj.error||'Unable to load sessions');setSessions(sj.sessions||[]);setStations(stj.ok?stj.stations||[]:[]);setGroups(gj.ok?gj.groups||[]:[])}catch(e){setError(e instanceof Error?e.message:'Unable to load live floor')}finally{setLoading(false)}},[]);
 useEffect(()=>{load();const id=window.setInterval(load,10000);return()=>window.clearInterval(id)},[load]);
 const groupIds=useMemo(()=>new Set(groups.flatMap(g=>g.sessionIds||[])),[groups]),active=sessions.filter(s=>s.status==='ACTIVE'||s.status==='PAUSED'),ungrouped=active.filter(s=>!groupIds.has(s.id)),occupancy=stations.length?Math.round(active.length/stations.length*100):0,outstanding=active.reduce((n,s)=>n+Number(s.balance||0),0);
 const openSettlement=async(g:Group)=>{setBusy(true);setError('');try{const r=await fetch(`/api/session-groups?id=${encodeURIComponent(g.id)}&settlement=1`,{cache:'no-store'}),j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'Unable to load group balance');setSettleGroup(g);setSources(j.settlement.sources||[]);setStrategy('ONE');setPayerCount(2);setPayerNames(['Payer 1','Payer 2']);}catch(e){setError(e instanceof Error?e.message:'Unable to load settlement')}finally{setBusy(false)}};
 const total=sources.reduce((n,s)=>n+s.outstanding,0);const amounts=useMemo(()=>{if(!total)return[];if(strategy==='EQUAL'||strategy==='PERCENT')return Array.from({length:payerCount},(_,i)=>strategy==='EQUAL'?Math.floor(total/payerCount)+(i<total%payerCount?1:0):Math.floor(total/payerCount)+(i<total%payerCount?1:0));if(strategy==='BY_SOURCE'||strategy==='BY_ITEM')return sources.map(s=>s.outstanding);return[total]},[strategy,payerCount,total,sources]);
 const saveGroup=async()=>{if(!settleGroup||!total)return;setBusy(true);setError('');try{const names=(strategy==='BY_SOURCE'||strategy==='BY_ITEM')?sources.map((s,i)=>s.label):payerNames.slice(0,payerCount);const payers=amounts.map((amount,i)=>({label:names[i]||`Payer ${i+1}`,amount}));const r=await fetch('/api/session-groups',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'settle',groupId:settleGroup.id,method,payers})});const j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'Unable to settle group');setSettleGroup(null);await load();}catch(e){setError(e instanceof Error?e.message:'Unable to settle group')}finally{setBusy(false)}};
 const toggle=(id:string)=>setSelected(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);
 const createGroup=async()=>{if(selected.length<2)return setError('Select at least 2 active sessions.');setBusy(true);setError('');try{const r=await fetch('/api/session-groups',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessionIds:selected})}),j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'Unable to create group');setSelected([]);setGrouping(false);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to create group')}finally{setBusy(false)}};
 const end=async(id:string)=>{if(!confirm('End this session?'))return;setBusy(true);setError('');try{const r=await fetch('/api/sessions',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessionId:id})}),j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'Unable to end session');setManage(null);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to end session')}finally{setBusy(false)}};
 const startStation=(id:string)=>window.dispatchEvent(new CustomEvent('genz:start-session',{detail:id}));
 return <><div className="top"><div><div className="eyebrow">Operations / Live floor</div><div className="title">Sessions</div><div className="muted">Start, pause, group and settle gaming sessions.</div></div><div className="actions"><button className="btn" onClick={()=>{setGrouping(!grouping);setSelected([]);setError('')}}>{grouping?'Cancel':'Group billing'}</button><StartSessionButton stations={stations} onStarted={load}/></div></div>
 {error&&<div className="loginError" role="alert">{error}</div>}
 {grouping&&<section className="section card"><div className="sectionHead"><div><div className="sectionTitle">Create billing group</div><div className="muted">Select 2 or more ungrouped active equipment sessions.</div></div><button className="btn primary" disabled={busy||selected.length<2} onClick={createGroup}>{busy?'Creating…':`Group ${selected.length} sessions`}</button></div><div className="stationGrid">{ungrouped.map(s=>{const st=stations.find(x=>x.id===s.stationId);return <button className="card station" key={s.id} onClick={()=>toggle(s.id)} style={{textAlign:'left',outline:selected.includes(s.id)?'2px solid #ffd400':'none'}}><div className="stationTop"><span className="stationId">{st?.name||s.stationId}</span><span className="badge green">{selected.includes(s.id)?'SELECTED':s.status==='PAUSED'?'PAUSED':'PLAYING'}</span></div><div className="muted">{s.customerName} · {s.id}</div><div className="price">{money(s.balance)}</div></button>})}</div>{!ungrouped.length&&<div className="muted">No ungrouped active sessions are available.</div>}</section>}
 {groups.length>0&&<section className="section card"><div className="sectionHead"><div className="sectionTitle">Open billing groups</div><span className="badge cyan">LIVE TOTAL</span></div>{groups.map(g=><div className="order" key={g.id}><div><div className="orderName">{g.name}</div><div className="orderSub">{g.sessionCount} equipment sessions · {g.id}</div></div><div className="actions"><b>{money(g.total)}</b><button className="btn primary" onClick={()=>openSettlement(g)} disabled={busy}>Settle</button></div></div>)}</section>}
 <div className="grid4"><div className="card"><div className="statLabel">Active</div><div className="stat">{active.length} <span className="muted">/ {stations.length}</span></div><div className="delta">{occupancy}% occupancy</div></div><div className="card"><div className="statLabel">Current tabs</div><div className="stat">{money(outstanding)}</div><div className="delta">Live session totals</div></div><div className="card"><div className="statLabel">Open tabs</div><div className="stat">{active.length}</div><div className="delta">{money(outstanding)} outstanding</div></div><div className="card"><div className="statLabel">Bookings next</div><div className="stat">—</div><div className="delta">Booking feed not connected</div></div></div>
 <section className="section card"><div className="sectionHead"><div className="sectionTitle">Live floor</div><span className="badge green">{loading?'LOADING…':'LIVE · 10S'}</span></div><table className="table"><thead><tr><th>Station</th><th>Customer / Group</th><th>Status</th><th>Started</th><th>Current tab</th><th>Action</th></tr></thead><tbody>{loading?<tr><td colSpan={6}>Loading live sessions…</td></tr>:stations.map(st=>{const s=sessions.find(x=>x.stationId===st.id&&x.status!=='ENDED'),g=s&&groups.find(x=>x.sessionIds?.includes(s.id));return <>{<tr key={st.id}><td><b>{st.name}</b><div className="muted">{st.type} · {st.slotMinutes} min</div></td><td>{s?(g?<>{g.name}<div className="muted">{s.customerName}</div></>:s.customerName):'—'}</td><td><span className={'badge '+cls(s?.status||st.status)}>{s?.status||st.status}</span></td><td>{time(s?.startedAt)}</td><td><b>{s?money(s.balance):'₹0'}</b></td><td>{s?<div className="actions"><button className="btn" onClick={()=>setManage(manage===s.id?null:s.id)}>{manage===s.id?'Close':'People'}</button><button className="btn" disabled={busy} onClick={()=>end(s.id)}>End</button></div>:<button className="btn" disabled={st.status!=='AVAILABLE'} onClick={()=>startStation(st.id)}>Start</button>}</td></tr>}{s&&manage===s.id&&<tr key={`${st.id}-participants`}><td colSpan={6}><ParticipantManager sessionId={s.id} onChanged={load}/></td></tr>}</>})}</tbody></table>{!stations.length&&!loading&&<div className="muted">No stations returned by the server.</div>}</section>
 {settleGroup&&<div style={{position:'fixed',inset:0,background:'rgba(0,0,0,.78)',display:'grid',placeItems:'center',zIndex:30}}><div className="card" style={{width:'min(720px,94vw)',maxHeight:'90vh',overflow:'auto',display:'grid',gap:14}}><div className="sectionHead"><div><div className="sectionTitle">Settle {settleGroup.name}</div><div className="muted">Live outstanding balance: {money(total)}</div></div><button className="btn" onClick={()=>setSettleGroup(null)}>Close</button></div><label>Payment method<select value={method} onChange={e=>setMethod(e.target.value)}><option value="CASH">Cash</option><option value="UPI">UPI</option><option value="CARD">Card</option><option value="RAZORPAY">Razorpay</option><option value="OTHER">Other</option></select></label><label>Split strategy<select value={strategy} onChange={e=>{setStrategy(e.target.value);if(e.target.value==='EQUAL'||e.target.value==='PERCENT')setPayerNames(Array.from({length:payerCount},(_,i)=>payerNames[i]||`Payer ${i+1}`))}}><option value="ONE">One payer</option><option value="EQUAL">Equal split</option><option value="BY_SOURCE">By PC / session</option><option value="BY_ITEM">By food item</option><option value="PERCENT">Percentage / custom amount</option></select></label>{(strategy==='EQUAL'||strategy==='PERCENT')&&<label>Payers<select value={payerCount} onChange={e=>{const n=Number(e.target.value);setPayerCount(n);setPayerNames(Array.from({length:n},(_,i)=>payerNames[i]||`Payer ${i+1}`))}}>{Array.from({length:10},(_,i)=><option key={i+1} value={i+1}>{i+1}</option>)}</select></label>}{(strategy==='EQUAL'||strategy==='PERCENT'||strategy==='ONE')&&amounts.map((amount,i)=><div key={i} style={{display:'grid',gridTemplateColumns:'1fr 150px',gap:8}}><input value={strategy==='ONE'?'Payer 1':payerNames[i]||`Payer ${i+1}`} disabled={strategy==='ONE'} onChange={e=>setPayerNames(v=>v.map((x,j)=>j===i?e.target.value:x))}/><input type="number" min="0" value={amount} readOnly/></div>)}{(strategy==='BY_SOURCE'||strategy==='BY_ITEM')&&<div style={{display:'grid',gap:8}}>{sources.map((s,i)=><div className="order" key={`${s.sourceType}:${s.sourceId}`}><span>{s.label}</span><b>{money(amounts[i]||0)}</b></div>)}</div>}<div className="sectionHead"><b>Total payment</b><b>{money(amounts.reduce((n,a)=>n+a,0))}</b></div><button className="btn primary" disabled={busy||!total} onClick={saveGroup}>{busy?'Saving…':'Capture settlement'}</button></div></div>}
 </>;
}
