'use client';
import {useEffect,useState} from 'react';

type Participant={id:string;customerId?:string;charge:number;joinedAt:string;leftAt?:string};
type Customer={id:string;name:string;mobile:string;memberId?:string;member?:{active:true}};

type Props={sessionId:string;onChanged?:()=>void};
const money=(n:number)=>`₹${Math.round(n).toLocaleString('en-IN')}`;
const time=(v:string)=>new Date(v).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'});

export default function ParticipantManager({sessionId,onChanged}:Props){
 const[billing,setBilling]=useState<{participants:Participant[];gamingTotal:number}|null>(null);
 const[q,setQ]=useState('');const[customers,setCustomers]=useState<Customer[]>([]);const[open,setOpen]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState('');
 const load=async()=>{const r=await fetch(`/api/sessions/billing?sessionId=${encodeURIComponent(sessionId)}`,{cache:'no-store'});const j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'Unable to load participants');setBilling(j.billing)};
 useEffect(()=>{load().catch(e=>setError(e.message));const t=window.setInterval(()=>load().catch(()=>{}),10000);return()=>window.clearInterval(t)},[sessionId]);
 useEffect(()=>{if(q.trim().length<3){setCustomers([]);return}const t=window.setTimeout(async()=>{try{const r=await fetch(`/api/customers?q=${encodeURIComponent(q.trim())}`,{cache:'no-store'});const j=await r.json();if(r.ok&&j.ok)setCustomers(j.customers||[])}catch{}},250);return()=>window.clearTimeout(t)},[q]);
 const add=async(customerId:string)=>{setBusy(true);setError('');try{const r=await fetch('/api/sessions/billing',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessionId,action:'add-participant',customerId})});const j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'Unable to add participant');setQ('');setCustomers([]);setOpen(false);setBilling(j.billing);onChanged?.()}catch(e){setError(e instanceof Error?e.message:'Unable to add participant')}finally{setBusy(false)}};
 const leave=async(id:string)=>{if(!confirm('Remove this participant from the active session? Their billing stops now.'))return;setBusy(true);setError('');try{const r=await fetch('/api/sessions/billing',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessionId,action:'leave-participant',participantId:id})});const j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'Unable to remove participant');setBilling(j.billing);onChanged?.()}catch(e){setError(e instanceof Error?e.message:'Unable to remove participant')}finally{setBusy(false)}};
 return <section className="card" style={{marginTop:12}}><div className="sectionHead"><div><div className="sectionTitle">Participants</div><div className="muted">Individual membership and billing are tracked separately.</div></div><button className="btn primary" onClick={()=>{setOpen(!open);setError('')}}>{open?'Close':'Add participant'}</button></div>{error&&<div className="loginError">{error}</div>}{open&&<div style={{marginBottom:12}}><input className="customerInput" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search customer by name, mobile or member ID" autoFocus/>{customers.length>0&&<div className="card" style={{marginTop:8,padding:0,overflow:'hidden'}}>{customers.map(c=><button key={c.id} className="order" style={{width:'100%',border:0,background:'transparent',textAlign:'left',cursor:'pointer'}} disabled={busy} onClick={()=>add(c.id)}><div><div className="orderName">{c.name}</div><div className="orderSub">{c.mobile}{c.member?' · Member':''}</div></div><span className="badge cyan">ADD</span></button>)}</div>}{q.length>=3&&!customers.length&&<div className="muted" style={{marginTop:8}}>No matching customers.</div>}</div>}{billing?.participants?.length?<div>{billing.participants.map(p=><div className="order" key={p.id}><div><div className="orderName">{p.displayName}</div><div className="orderSub">Joined {time(p.joinedAt)}{p.leftAt?` · Left ${time(p.leftAt)}`:' · ACTIVE'}</div></div><div className="actions"><b>{money(p.charge)}</b>{!p.leftAt&&<button className="btn" disabled={busy} onClick={()=>leave(p.id)}>Leave</button>}</div></div>)}</div>:<div className="muted">No participants yet.</div>}<div className="sectionHead" style={{marginTop:8}}><span className="muted">Live gaming total</span><b>{money(billing?.gamingTotal||0)}</b></div></section>;
}
