'use client';
import {useEffect,useState} from 'react';
type Station={id:string;name:string;type:string;status:string;hourlyRate:number;slotMinutes:number};
export default function StartSessionButton({stations,onStarted}:{stations:Station[];onStarted:()=>void}){
 const [open,setOpen]=useState(false),[stationId,setStationId]=useState(''),[customerName,setCustomerName]=useState(''),[memberId,setMemberId]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const available=stations.filter(s=>s.status==='AVAILABLE');
 useEffect(()=>{const handler=(e:Event)=>{const id=(e as CustomEvent<string>).detail;if(available.some(s=>s.id===id)){setStationId(id);setError('');setOpen(true)}};window.addEventListener('genz:start-session',handler);return()=>window.removeEventListener('genz:start-session',handler)},[stations]);
 const start=async()=>{if(!stationId||!customerName.trim())return setError('Select equipment and enter the customer name.');setBusy(true);setError('');try{const r=await fetch('/api/sessions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({stationId,customerName:customerName.trim(),...(memberId.trim()?{memberId:memberId.trim()}: {})})});const j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'Unable to start session');setOpen(false);setStationId('');setCustomerName('');setMemberId('');onStarted()}catch(e){setError(e instanceof Error?e.message:'Unable to start session')}finally{setBusy(false)}};
 return <><button className="btn primary" onClick={()=>{setError('');setStationId(available[0]?.id||'');setOpen(true)}}>+ Start session</button>{open&&<div style={{position:'fixed',inset:0,background:'rgba(0,0,0,.65)',display:'grid',placeItems:'center',zIndex:50,padding:20}}><div className="card" style={{width:'min(520px,100%)',padding:24}}><div className="sectionHead"><div><div className="sectionTitle">Start gaming session</div><div className="muted">Create a live tab for one available equipment station.</div></div><button className="btn" disabled={busy} onClick={()=>setOpen(false)}>Close</button></div>{error&&<div className="loginError">{error}</div>}<div style={{display:'grid',gap:14,marginTop:18}}><label><div className="muted">Equipment</div><select value={stationId} onChange={e=>setStationId(e.target.value)} style={{width:'100%',padding:12,marginTop:6}}><option value="">Select equipment</option>{available.map(s=><option key={s.id} value={s.id}>{s.name} · {s.type} · {s.slotMinutes} min · ₹{Number(s.hourlyRate).toLocaleString('en-IN')}/hr</option>)}</select></label><label><div className="muted">Customer name</div><input value={customerName} onChange={e=>setCustomerName(e.target.value)} placeholder="Customer / group name" maxLength={120} style={{width:'100%',padding:12,marginTop:6}}/></label><label><div className="muted">Membership ID <span className="muted">(optional)</span></div><input value={memberId} onChange={e=>setMemberId(e.target.value)} placeholder="e.g. GZ-1042" maxLength={64}/></label><div className="muted">Duration uses the equipment&apos;s configured slot: {stations.find(s=>s.id===stationId)?.slotMinutes||'—'} minutes.</div><button className="btn primary" disabled={busy||!stationId||!customerName.trim()} onClick={start}>{busy?'Starting…':'Start session'}</button></div></div></div>}</>;
}
