'use client';
import {useEffect,useState} from 'react';
type Member={id:string;name:string;mobile:string;tier:string;expiresAt:string;active:boolean};
type Tx={id:string;type:string;amount:number;method:string;status:string;previousExpiresAt:string|null;newExpiresAt:string;createdAt:string};
const roles=['REGULAR','GOLD','VIP'];
const methods=['CASH','UPI','CARD','OTHER'];
export default function MembersPage(){
 const[members,setMembers]=useState<Member[]>([]);const[q,setQ]=useState('');const[form,setForm]=useState({id:'',name:'',mobile:'',tier:'REGULAR',expiresAt:''});
 const[selected,setSelected]=useState<Member|null>(null);const[renew,setRenew]=useState({newExpiresAt:'',amount:''});const[history,setHistory]=useState<Tx[]>([]);const[paymentMethod,setPaymentMethod]=useState('CASH');const[busy,setBusy]=useState(false);const[error,setError]=useState('');
 const load=async()=>{const r=await fetch(`/api/members?q=${encodeURIComponent(q)}`,{cache:'no-store'});const j=await r.json();if(!r.ok)throw Error(j.error||'Unable to load members');setMembers(j.members||[])};
 useEffect(()=>{load().catch(e=>setError(e.message))},[q]);
 const save=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/members',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const j=await r.json();if(!r.ok)throw Error(j.error||'Unable to create membership');setForm({id:'',name:'',mobile:'',tier:'REGULAR',expiresAt:''});await load()}catch(e){setError(e instanceof Error?e.message:'Unable to create membership')}finally{setBusy(false)}};
 const toggle=async(m:Member)=>{try{const r=await fetch('/api/members',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:m.id,active:!m.active})});const j=await r.json();if(!r.ok)throw Error(j.error||'Unable to update member');await load()}catch(e){setError(e instanceof Error?e.message:'Unable to update member')}};
 const openRenew=async(m:Member)=>{setSelected(m);setRenew({newExpiresAt:'',amount:''});setPaymentMethod('CASH');setError('');try{const r=await fetch(`/api/membership-transactions?memberId=${encodeURIComponent(m.id)}`,{cache:'no-store'});const j=await r.json();if(!r.ok)throw Error(j.error||'Unable to load payment history');setHistory(j.transactions||[])}catch(e){setError(e instanceof Error?e.message:'Unable to load payment history')}};
 const doRenew=async(e:React.FormEvent)=>{e.preventDefault();if(!selected)return;setBusy(true);setError('');try{const r=await fetch('/api/membership-transactions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({memberId:selected.id,newExpiresAt:renew.newExpiresAt,amount:Number(renew.amount),method:paymentMethod})});const j=await r.json();if(!r.ok)throw Error(j.error||'Unable to renew membership');await load();const updated=(await (await fetch(`/api/members?id=${encodeURIComponent(selected.id)}`,{cache:'no-store'})).json()).member;setSelected(updated);setRenew({newExpiresAt:'',amount:''});const h=await (await fetch(`/api/membership-transactions?memberId=${encodeURIComponent(selected.id)}`,{cache:'no-store'})).json();setHistory(h.transactions||[])}catch(e){setError(e instanceof Error?e.message:'Unable to renew membership')}finally{setBusy(false)}};
 return <main className="page"><div className="pageHeader"><div><div className="eyebrow">ADMIN · MEMBERSHIP</div><h1>Members</h1><p className="muted">Manage member identity, tier and expiry. Membership payments are recorded in the finance ledger.</p></div></div>{error&&<div className="card loginError">{error}</div>}
 <section className="card" style={{marginBottom:20}}><div className="sectionTitle">Create membership</div><form onSubmit={save} className="formGrid"><input className="customerInput" placeholder="Membership ID (optional)" value={form.id} onChange={e=>setForm({...form,id:e.target.value})}/><input className="customerInput" placeholder="Full name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/><input className="customerInput" placeholder="Mobile number" inputMode="tel" value={form.mobile} onChange={e=>setForm({...form,mobile:e.target.value})} required/><select className="customerInput" value={form.tier} onChange={e=>setForm({...form,tier:e.target.value})}>{roles.map(r=><option key={r}>{r}</option>)}</select><input className="customerInput" type="date" value={form.expiresAt} onChange={e=>setForm({...form,expiresAt:e.target.value})} required/><button className="btn primary" disabled={busy}>{busy?'Saving…':'Create member'}</button></form></section>
 <section className="card"><div className="sectionHead"><div className="sectionTitle">Member directory</div><input className="customerInput" style={{maxWidth:300}} placeholder="Search ID, name or mobile" value={q} onChange={e=>setQ(e.target.value)}/></div><div className="tableWrap"><table><thead><tr><th>ID</th><th>Name</th><th>Mobile</th><th>Tier</th><th>Expires</th><th>Status</th><th>Actions</th></tr></thead><tbody>{members.map(m=><tr key={m.id}><td>{m.id}</td><td>{m.name}</td><td>{m.mobile}</td><td><span className="badge cyan">{m.tier}</span></td><td>{m.expiresAt}</td><td>{m.active?<span className="memberPill">ACTIVE</span>:<span className="guestPill">INACTIVE</span>}</td><td><button className="btn" onClick={()=>openRenew(m)}>Renew / History</button>{' '}<button className="btn" onClick={()=>toggle(m)}>{m.active?'Disable':'Enable'}</button></td></tr>)}</tbody></table></div></section>
 {selected&&<div className="card" style={{marginTop:20}}><div className="sectionHead"><div><div className="sectionTitle">{selected.name} · Membership</div><div className="muted">{selected.id} · {selected.tier} · current expiry {selected.expiresAt}</div></div><button className="btn" onClick={()=>setSelected(null)}>Close</button></div><form onSubmit={doRenew} className="formGrid" style={{marginTop:16}}><input className="customerInput" type="date" min={selected.expiresAt} value={renew.newExpiresAt} onChange={e=>setRenew({...renew,newExpiresAt:e.target.value})} required/><input className="customerInput" type="number" min="1" step="1" placeholder="Amount ₹" value={renew.amount} onChange={e=>setRenew({...renew,amount:e.target.value})} required/><select className="customerInput" value={paymentMethod} onChange={e=>setPaymentMethod(e.target.value)}>{methods.map(m=><option key={m}>{m}</option>)}</select><button className="btn primary" disabled={busy}>{busy?'Processing…':'Record renewal payment'}</button></form><div className="sectionTitle" style={{marginTop:24}}>Payment history</div><div className="tableWrap"><table><thead><tr><th>Date</th><th>Type</th><th>Amount</th><th>Method</th><th>Previous expiry</th><th>New expiry</th><th>Status</th></tr></thead><tbody>{history.length?history.map(t=><tr key={t.id}><td>{new Date(t.createdAt).toLocaleString()}</td><td>{t.type}</td><td>₹{t.amount}</td><td>{t.method}</td><td>{t.previousExpiresAt||'—'}</td><td>{t.newExpiresAt}</td><td>{t.status}</td></tr>):<tr><td colSpan={7} className="muted">No membership payments recorded.</td></tr>}</tbody></table></div></div>}
 </main>
}
