'use client';
import {useEffect,useState} from 'react';
type Member={id:string;name:string;mobile:string;active:boolean};
type Tx={id:string;type:string;amount:number;method:string;status:string;previousExpiresAt:string|null;newExpiresAt:string|null;createdAt:string};
type Staff={role:'OWNER'|'MANAGER'};
const idTypes=[['AADHAAR','Aadhaar'],['PAN','PAN'],['PASSPORT','Passport'],['DRIVING_LICENSE','Driving Licence'],['VOTER_ID','Voter ID'],['OTHER','Other']];
export default function MembersPage(){
 const[members,setMembers]=useState<Member[]>([]);const[q,setQ]=useState('');const[form,setForm]=useState({id:'',name:'',mobile:'',governmentIdType:'AADHAAR',governmentIdNumber:''});
 const[selected,setSelected]=useState<Member|null>(null);const[history,setHistory]=useState<Tx[]>([]);const[staff,setStaff]=useState<Staff|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState('');
 const load=async()=>{const r=await fetch(`/api/members?q=${encodeURIComponent(q)}`,{cache:'no-store'});const j=await r.json();if(!r.ok)throw Error(j.error||'Unable to load members');setMembers(j.members||[])};
 useEffect(()=>{load().catch(e=>setError(e.message));fetch('/api/staff/me',{cache:'no-store'}).then(async r=>r.ok?(await r.json()).staff:null).then(s=>setStaff(s||null)).catch(()=>{})},[q]);
 const generateId=async()=>{setError('');try{const r=await fetch('/api/members?nextId=1',{cache:'no-store'}),j=await r.json();if(!r.ok)throw Error(j.error||'Unable to generate membership ID');setForm(f=>({...f,id:j.nextId}))}catch(e){setError(e instanceof Error?e.message:'Unable to generate membership ID')}};
 const save=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/membership-transactions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'NEW',...form,amount:0,method:'CASH'})});const j=await r.json();if(!r.ok)throw Error(j.error||'Unable to create membership');setForm({id:'',name:'',mobile:'',governmentIdType:'AADHAAR',governmentIdNumber:''});await load()}catch(e){setError(e instanceof Error?e.message:'Unable to create membership')}finally{setBusy(false)}};
 const toggle=async(m:Member)=>{try{const r=await fetch('/api/members',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:m.id,active:!m.active})});const j=await r.json();if(!r.ok)throw Error(j.error||'Unable to update member');await load()}catch(e){setError(e instanceof Error?e.message:'Unable to update member')}};
 const openHistory=async(m:Member)=>{setSelected(m);setError('');try{const r=await fetch(`/api/membership-transactions?memberId=${encodeURIComponent(m.id)}`,{cache:'no-store'});const j=await r.json();if(!r.ok)throw Error(j.error||'Unable to load payment history');setHistory(j.transactions||[])}catch(e){setError(e instanceof Error?e.message:'Unable to load payment history')}};
 return <main className="page"><div className="pageHeader"><div><div className="eyebrow">ADMIN · MEMBERSHIP</div><h1>Members</h1><p className="muted">One membership type. No tiers. Members are identified by a GENZFAM### membership ID and mobile number.</p></div></div>{error&&<div className="card loginError">{error}</div>}
 {staff?.role==='OWNER'&&<section className="card" style={{marginBottom:20}}><div className="sectionTitle">Add member manually</div><p className="muted">Owner-only registration. Government ID details are stored for membership verification and are not shown in the member directory.</p><form onSubmit={save} className="formGrid"><div style={{display:'flex',gap:8}}><input className="customerInput" placeholder="Membership ID · GENZFAM001" value={form.id} onChange={e=>setForm({...form,id:e.target.value.toUpperCase()})} pattern="GENZFAM[0-9]{3}" required/><button type="button" className="btn" onClick={generateId}>Generate</button></div><input className="customerInput" placeholder="Full name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/><input className="customerInput" placeholder="Mobile number" inputMode="tel" value={form.mobile} onChange={e=>setForm({...form,mobile:e.target.value})} required/><select className="customerInput" value={form.governmentIdType} onChange={e=>setForm({...form,governmentIdType:e.target.value})}>{idTypes.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><input className="customerInput" placeholder="Government ID number" value={form.governmentIdNumber} onChange={e=>setForm({...form,governmentIdNumber:e.target.value.trim()})} required/><button className="btn primary" disabled={busy}>{busy?'Saving…':'Add member'}</button></form></section>}
 <section className="card"><div className="sectionHead"><div><div className="sectionTitle">Member directory</div><div className="muted">Active membership remains active until an owner disables it.</div></div><input className="customerInput" style={{maxWidth:300}} placeholder="Search ID, name or mobile" value={q} onChange={e=>setQ(e.target.value)}/></div><div className="tableWrap"><table><thead><tr><th>Membership ID</th><th>Name</th><th>Mobile</th><th>Status</th><th>Actions</th></tr></thead><tbody>{members.map(m=><tr key={m.id}><td><b>{m.id}</b></td><td>{m.name}</td><td>{m.mobile}</td><td>{m.active?<span className="memberPill">ACTIVE</span>:<span className="guestPill">INACTIVE</span>}</td><td><button className="btn" onClick={()=>openHistory(m)}>History</button>{' '}<button className="btn" onClick={()=>toggle(m)}>{m.active?'Disable':'Enable'}</button></td></tr>)}</tbody></table></div></section>
 {selected&&<div className="card" style={{marginTop:20}}><div className="sectionHead"><div><div className="sectionTitle">{selected.name} · Membership history</div><div className="muted">{selected.id} · {selected.mobile}</div></div><button className="btn" onClick={()=>setSelected(null)}>Close</button></div><div className="tableWrap" style={{marginTop:16}}><table><thead><tr><th>Date</th><th>Type</th><th>Amount</th><th>Method</th><th>Status</th></tr></thead><tbody>{history.length?history.map(t=><tr key={t.id}><td>{new Date(t.createdAt).toLocaleString()}</td><td>{t.type}</td><td>₹{t.amount}</td><td>{t.method}</td><td>{t.status}</td></tr>):<tr><td colSpan={5} className="muted">No membership payments recorded.</td></tr>}</tbody></table></div></div>}
 </main>
}
