import {NextResponse} from 'next/server';
import {cookies} from 'next/headers';
import {COOKIE,getStaffByToken,loginStaff,logoutStaff} from '../../../../lib/staff-auth';
export const dynamic='force-dynamic';
const cookieOptions={httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax' as const,path:'/',maxAge:60*60*12};
const roleCookieOptions={httpOnly:false,secure:process.env.NODE_ENV==='production',sameSite:'lax' as const,path:'/',maxAge:60*60*12};
export async function GET(){const token=(await cookies()).get(COOKIE)?.value;const staff=await getStaffByToken(token);return NextResponse.json({ok:true,authenticated:!!staff,staff},{headers:{'Cache-Control':'no-store'}});}
export async function POST(req:Request){try{const len=Number(req.headers.get('content-length')||0);if(len>16_384)return NextResponse.json({ok:false,error:'Request body too large'},{status:413});const b=await req.json();if(typeof b?.username!=='string'||typeof b?.password!=='string'||b.username.length>80||b.password.length<8||b.password.length>200)return NextResponse.json({ok:false,error:'Invalid credentials'},{status:400});const sourceKey=process.env.GENZ_TRUST_PROXY==='true'?(req.headers.get('x-forwarded-for')?.split(',')[0]?.trim()||req.headers.get('x-real-ip')?.trim()||'unknown'):'unknown';const result=await loginStaff(b.username,b.password,sourceKey);if(!result)return NextResponse.json({ok:false,error:'Invalid username or password'},{status:401});const response=NextResponse.json({ok:true,staff:result.staff});response.cookies.set(COOKIE,result.token,cookieOptions);response.cookies.set('genz_staff_role',result.staff.role,roleCookieOptions);return response;}catch(e){if(e instanceof Error&&e.message==='STAFF_RATE_LIMITED')return NextResponse.json({ok:false,error:'Too many sign-in attempts. Try again later.'},{status:429});return NextResponse.json({ok:false,error:'Unable to sign in'},{status:500});}}
export async function DELETE(){const c=await cookies();await logoutStaff(c.get(COOKIE)?.value);const response=NextResponse.json({ok:true});response.cookies.set(COOKIE,'',{...cookieOptions,maxAge:0});response.cookies.set('genz_staff_role','',{...roleCookieOptions,maxAge:0});return response;}
