import { createHash, randomBytes, randomInt, randomUUID } from 'node:crypto';
import type { PoolConnection, RowDataPacket } from 'mysql2/promise';
import { pool, transaction } from './mysql';

const OTP_TTL_MINUTES=5;
const MAX_ATTEMPTS=5;
const SESSION_DAYS=30;
const RATE_KEY='__genz_customer_otp_rate__';
const rateStore=globalThis as typeof globalThis & {[RATE_KEY]?:Map<string,number[]>};
const otpRates=rateStore[RATE_KEY]??(rateStore[RATE_KEY]=new Map());
const hash=(value:string)=>createHash('sha256').update(value).digest('hex');
const id=(prefix:string)=>`${prefix}-${randomUUID()}`;
const rateLimit=(key:string,max:number,windowMs:number)=>{const now=Date.now(),values=(otpRates.get(key)||[]).filter((t:number)=>t>now-windowMs);if(values.length>=max){otpRates.set(key,values);return false;}values.push(now);otpRates.set(key,values);if(otpRates.size>5000){for(const[k,v]of otpRates){if(!v.some((t:number)=>t>now-60*60*1000))otpRates.delete(k);}}return true;};
type CustomerRow={id:string;mobile:string;name:string|null;member_id:string|null};

export function normalizeMobile(value:string){const digits=value.replace(/\D/g,'');if(digits.length===10)return `+91${digits}`;if(digits.length===12&&digits.startsWith('91'))return `+${digits}`;if(value.trim().startsWith('+')&&/^\+?[1-9]\d{9,14}$/.test(value.trim()))return value.trim();return '';}
async function sendOtpSms(mobile:string,otp:string){const authkey=process.env.GENZ_OTP_MSG91_AUTHKEY;const sender=process.env.GENZ_OTP_MSG91_SENDER_ID;if(!authkey||!sender){if(process.env.NODE_ENV!=='production'&&process.env.GENZ_OTP_DEV_MODE==='true')return;throw new Error('OTP provider is not configured');}const params=new URLSearchParams({authkey,mobile:mobile.replace('+',''),message:`Your GenZ Cafe verification code is ${otp}. It expires in ${OTP_TTL_MINUTES} minutes.`,sender,otp,otp_expiry:String(OTP_TTL_MINUTES),otp_length:'6'});const response=await fetch(`https://api.msg91.com/api/sendotp.php?${params.toString()}`,{method:'GET',cache:'no-store'});if(!response.ok)throw new Error('OTP delivery failed');const result=await response.json() as {type?:string};if(result.type&&result.type!=='success')throw new Error('OTP delivery failed');}
export async function requestCustomerOtp(rawMobile:string,sourceKey='unknown'){const mobile=normalizeMobile(rawMobile);if(!mobile)throw new Error('Invalid mobile number');if(!rateLimit(`ip:${sourceKey}`,10,60*60*1000)||!rateLimit(`ip5:${sourceKey}`,3,5*60*1000)||!rateLimit(`mobile:${mobile}`,5,60*60*1000)||!rateLimit(`mobile5:${mobile}`,2,5*60*1000))throw new Error('Too many OTP requests. Try again later');const now=new Date();const recent=await pool.query<RowDataPacket[]>('SELECT id FROM customer_otp_challenges WHERE mobile=? AND created_at>? LIMIT 1',[mobile,new Date(Date.now()-30000)]);if(recent[0].length)throw new Error('Please wait before requesting another OTP');const hourly=await pool.query<RowDataPacket[]>('SELECT COUNT(*) AS count FROM customer_otp_challenges WHERE mobile=? AND created_at>?',[mobile,new Date(Date.now()-3600000)]);if(Number((hourly[0][0] as {count:number}).count)>=5)throw new Error('Too many OTP requests. Try again later');const otp=String(randomInt(0,1000000)).padStart(6,'0');const challengeId=id('OTP');await transaction(async(connection:PoolConnection)=>{await connection.execute('UPDATE customer_otp_challenges SET consumed_at=? WHERE mobile=? AND consumed_at IS NULL',[now,mobile]);await connection.execute('INSERT INTO customer_otp_challenges(id,mobile,otp_hash,expires_at,attempts,created_at) VALUES (?,?,?,?,?,?)',[challengeId,mobile,hash(otp),new Date(Date.now()+OTP_TTL_MINUTES*60000),0,now]);});try{await sendOtpSms(mobile,otp);}catch(error){await pool.execute('UPDATE customer_otp_challenges SET consumed_at=? WHERE id=?',[new Date(),challengeId]);throw error;}return process.env.NODE_ENV!=='production'&&process.env.GENZ_OTP_DEV_MODE==='true'?{challengeId,devOtp:otp}:{challengeId};}
export async function verifyCustomerOtp(challengeId:string,rawMobile:string,otp:string,sourceKey='unknown'){const mobile=normalizeMobile(rawMobile);if(!/^OTP-[a-f0-9-]{30,}$/.test(challengeId)||!/^\d{6}$/.test(otp)||!mobile)throw new Error('Invalid verification request');if(!rateLimit(`verify:source:${sourceKey}`,30,15*60*1000)||!rateLimit(`verify:mobile:${mobile}`,15,15*60*1000))throw new Error('Too many OTP verification attempts. Try again later');return transaction(async(connection:PoolConnection)=>{const [rows]=await connection.query<(RowDataPacket & {id:string;mobile:string;otp_hash:string;expires_at:Date;attempts:number;consumed_at:Date|null})[]>('SELECT * FROM customer_otp_challenges WHERE id=? AND mobile=? FOR UPDATE',[challengeId,mobile]);const challenge=rows[0];if(!challenge||challenge.consumed_at||new Date(challenge.expires_at).getTime()<Date.now()||challenge.attempts>=MAX_ATTEMPTS)throw new Error('OTP expired or invalid');if(hash(otp)!==challenge.otp_hash){await connection.execute('UPDATE customer_otp_challenges SET attempts=attempts+1 WHERE id=?',[challengeId]);throw new Error('OTP expired or invalid');}await connection.execute('UPDATE customer_otp_challenges SET consumed_at=? WHERE id=?',[new Date(),challengeId]);const [members]=await connection.query<(RowDataPacket & {id:string;name:string;mobile:string;active:number})[]>('SELECT id,name,mobile,active FROM members WHERE mobile=? LIMIT 1',[mobile]);const member=members[0];const [existing]=await connection.query<(RowDataPacket & CustomerRow)[]>('SELECT id,mobile,name,member_id FROM customers WHERE mobile=? LIMIT 1',[mobile]);let customer:CustomerRow|undefined=existing[0] as CustomerRow|undefined;if(!customer){const customerId=id('CUS');const customerName=member?.name||null;const memberId=member?.id||null;await connection.execute('INSERT INTO customers(id,mobile,name,member_id,created_at,updated_at) VALUES (?,?,?,?,?,?)',[customerId,mobile,customerName,memberId,new Date(),new Date()]);customer={id:customerId,mobile,name:customerName,member_id:memberId};}else{const customerName=member?.name||customer.name;const memberId=member?.id||null;await connection.execute('UPDATE customers SET name=COALESCE(?,name),member_id=?,updated_at=? WHERE id=?',[member?.name||null,memberId,new Date(),customer.id]);customer={...customer,member_id:memberId,name:customerName};}const token=randomBytes(32).toString('hex');await connection.execute('INSERT INTO customer_sessions(id,customer_id,session_token_hash,expires_at,created_at,last_seen_at) VALUES (?,?,?,?,?,?)',[id('CS'),customer.id,hash(token),new Date(Date.now()+SESSION_DAYS*86400000),new Date(),new Date()]);return{token,customer:{id:customer.id,mobile:customer.mobile,name:customer.name,memberId:customer.member_id}};});}
export async function getCustomerByToken(token:string){if(!token)return null;const tokenHash=hash(token);const [rows]=await pool.query<(RowDataPacket & {id:string;mobile:string;name:string|null;member_id:string|null})[]>('SELECT c.id,c.mobile,c.name,c.member_id FROM customer_sessions cs JOIN customers c ON c.id=cs.customer_id WHERE cs.session_token_hash=? AND cs.expires_at>NOW() AND cs.last_seen_at>DATE_SUB(NOW(),INTERVAL 30 DAY) LIMIT 1',[tokenHash]);if(!rows[0])return null;await pool.execute('UPDATE customer_sessions SET last_seen_at=NOW(3) WHERE session_token_hash=?',[tokenHash]);return rows[0];}
export async function listCustomerSessions(customerId:string,currentToken:string){const tokenHash=hash(currentToken);const[rows]=await pool.query<RowDataPacket[]>('SELECT id,session_token_hash,expires_at,created_at,last_seen_at FROM customer_sessions WHERE customer_id=? AND expires_at>NOW() AND last_seen_at>DATE_SUB(NOW(),INTERVAL 30 DAY) ORDER BY last_seen_at DESC',[customerId]);return rows.map(r=>({id:String(r.id),current:String(r.session_token_hash)===tokenHash,expiresAt:new Date(r.expires_at).toISOString(),createdAt:new Date(r.created_at).toISOString(),lastSeenAt:new Date(r.last_seen_at).toISOString()}));}
export async function revokeCustomerSessions(customerId:string,currentToken:string,allOther=false){const tokenHash=hash(currentToken);if(allOther){const[result]=await pool.execute('DELETE FROM customer_sessions WHERE customer_id=? AND session_token_hash<>?',[customerId,tokenHash]);return Number((result as {affectedRows:number}).affectedRows);}const[result]=await pool.execute('DELETE FROM customer_sessions WHERE customer_id=? AND session_token_hash=?',[customerId,tokenHash]);return Number((result as {affectedRows:number}).affectedRows);}
