import {randomUUID} from 'node:crypto';
import type {PoolConnection,RowDataPacket} from 'mysql2/promise';
import {pool,transaction} from './mysql';
const id=()=>`RECON-${randomUUID()}`;
const money=(v:unknown)=>Number(v||0);
const ELIGIBLE=['REVENUE','EXPENSE'] as const;
export async function listReconciliationCandidates(limit=200){const safe=Math.min(Math.max(Math.floor(limit),1),500);const[rows]=await pool.query<RowDataPacket[]>(`SELECT f.id,f.type,f.category,f.method,f.amount,f.source_type,f.source_id,f.created_at,r.id reconciliation_id,r.external_provider,r.external_reference,r.external_amount,r.status reconciliation_status FROM finance_transactions f LEFT JOIN finance_reconciliations r ON r.finance_transaction_id=f.id WHERE f.type IN ('REVENUE','EXPENSE') ORDER BY f.created_at DESC,f.id DESC LIMIT ${safe}`);return rows.map(r=>({financeTransactionId:String(r.id),type:String(r.type),category:String(r.category),method:String(r.method),amount:money(r.amount),sourceType:r.source_type?String(r.source_type):undefined,sourceId:r.source_id?String(r.source_id):undefined,createdAt:new Date(r.created_at).toISOString(),reconciliation:r.reconciliation_id?{id:String(r.reconciliation_id),provider:String(r.external_provider),reference:String(r.external_reference),externalAmount:money(r.external_amount),status:String(r.reconciliation_status)}:null}));}
export async function reconcileFinanceTransaction(x:{financeTransactionId:string;provider:string;reference:string;externalAmount:number;notes?:string;staffId:string}){const provider=x.provider.trim().slice(0,80),reference=x.reference.trim().slice(0,160),amount=Number(x.externalAmount);if(!x.financeTransactionId||!provider||!reference||!Number.isSafeInteger(amount)||amount<0)throw Error('INVALID_RECONCILIATION');return transaction(async(c:PoolConnection)=>{const[f]=await c.query<RowDataPacket[]>('SELECT id,amount,type,method FROM finance_transactions WHERE id=? FOR UPDATE',[x.financeTransactionId]);if(!f[0])throw Error('FINANCE_TRANSACTION_NOT_FOUND');if(!ELIGIBLE.includes(String(f[0].type) as typeof ELIGIBLE[number]))throw Error('TRANSACTION_NOT_RECONCILABLE');const expected=money(f[0].amount),status=expected===amount?'MATCHED':'EXCEPTION';const rid=id();try{await c.execute('INSERT INTO finance_reconciliations(id,finance_transaction_id,external_provider,external_reference,external_amount,status,notes,reconciled_by,reconciled_at) VALUES(?,?,?,?,?,?,?,?,NOW(3))',[rid,x.financeTransactionId,provider,reference,amount,status,x.notes?.trim().slice(0,500)||null,x.staffId]);}catch(e){const[old]=await c.query<RowDataPacket[]>('SELECT id FROM finance_reconciliations WHERE finance_transaction_id=? LIMIT 1',[x.financeTransactionId]);if(old[0])throw Error('TRANSACTION_ALREADY_RECONCILED');throw e;}await c.execute('INSERT INTO audit_log(staff_id,action,entity_type,entity_id,details,created_at) VALUES(?,?,?,?,?,NOW(3))',[x.staffId,'FINANCE_RECONCILED','finance_transaction',x.financeTransactionId,JSON.stringify({provider,reference,externalAmount:amount,expected,status,type:String(f[0].type),method:String(f[0].method)})]);return{id:rid,status,expectedAmount:expected,externalAmount:amount};});}
export async function reconciliationSummary(){const[rows]=await pool.query<RowDataPacket[]>(`SELECT COUNT(*) total,COALESCE(SUM(CASE WHEN r.status='MATCHED' THEN 1 ELSE 0 END),0) matched,COALESCE(SUM(CASE WHEN r.status='EXCEPTION' THEN 1 ELSE 0 END),0) exceptions,COALESCE(SUM(CASE WHEN r.id IS NULL THEN CASE WHEN f.type='REVENUE' THEN f.amount ELSE 0 END ELSE 0 END),0) unreconciled_revenue,COALESCE(SUM(CASE WHEN r.id IS NULL THEN CASE WHEN f.type='EXPENSE' THEN f.amount ELSE 0 END ELSE 0 END),0) unreconciled_expense FROM finance_transactions f LEFT JOIN finance_reconciliations r ON r.finance_transaction_id=f.id WHERE f.type IN ('REVENUE','EXPENSE')`);return{total:Number(rows[0]?.total||0),matched:Number(rows[0]?.matched||0),exceptions:Number(rows[0]?.exceptions||0),unreconciledAmount:money(rows[0]?.unreconciled_revenue),unreconciledExpense:money(rows[0]?.unreconciled_expense)};}
