import {randomUUID} from 'node:crypto';
import type {PoolConnection,RowDataPacket} from 'mysql2/promise';
import {pool,transaction} from './mysql';
export const FOOD_PAYMENT_MODES=['PAY_NOW','COUNTER'] as const;export type FoodPaymentMode=typeof FOOD_PAYMENT_MODES[number];
const id=(p:string)=>`${p}-${randomUUID()}`,now=()=>new Date();

async function recordFoodRevenue(c:PoolConnection,orderId:string,amount:number,method:'CASH'|'RAZORPAY'){
  await c.execute('INSERT INTO finance_transactions(id,type,category,description,amount,method,source_type,source_id,created_at) VALUES(?,?,?,?,?,?,?,?,NOW(3)) ON DUPLICATE KEY UPDATE amount=VALUES(amount),method=VALUES(method)',[id('REV'),'REVENUE','FOOD','Food order '+orderId,amount,method,'FOOD_ORDER',orderId]);
}

export async function createFoodOrder(x:{sessionId:string;customerId:string;items:{itemId:string;qty:number}[];paymentMode:FoodPaymentMode}){if(!x.customerId||!FOOD_PAYMENT_MODES.includes(x.paymentMode)||!x.items.length)throw Error('Invalid order');return transaction(async(c:PoolConnection)=>{const[s]=await c.query<RowDataPacket[]>('SELECT id,station_id FROM sessions WHERE id=? AND status IN (\'ACTIVE\',\'PAUSED\') FOR UPDATE',[x.sessionId]);if(!s[0])throw Error('Active session required');const[cu]=await c.query<RowDataPacket[]>('SELECT id,name,member_id FROM customers WHERE id=?',[x.customerId]);if(!cu[0])throw Error('Customer not found');const[pa]=await c.query<RowDataPacket[]>('SELECT id FROM session_participants WHERE session_id=? AND customer_id=? AND active=TRUE LIMIT 1',[x.sessionId,x.customerId]);const pid=pa[0]?.id||id('PAR');if(!pa[0])await c.execute('INSERT INTO session_participants(id,session_id,customer_id,member_id,display_name,active,created_at) VALUES(?,?,?,?,?,?,?)',[pid,x.sessionId,cu[0].member_id||null,String(cu[0].name||'Guest').slice(0,120),1,now()]);const ids=[...new Set(x.items.map(i=>String(i.itemId)))];if(ids.length!==x.items.length)throw Error('Duplicate menu item');const ph=ids.map(()=>'?').join(',');const[m]=await c.query<(RowDataPacket&{id:string;name:string;member_price:number;non_member_price:number;active:number})[]>(`SELECT id,name,member_price,non_member_price,active FROM menu_items WHERE id IN (${ph}) FOR UPDATE`,ids);if(m.length!==ids.length||m.some(i=>!i.active))throw Error('Menu item unavailable');const map=new Map(m.map(i=>[i.id,i]));const items=x.items.map(i=>{const q=Number(i.qty),a=map.get(i.itemId);if(!a||!Number.isInteger(q)||q<1||q>99)throw Error('Invalid quantity');return{itemId:a.id,name:a.name,qty:q,unitPrice:Number(cu[0].member_id?a.member_price:a.non_member_price)};});const total=items.reduce((n,i)=>n+i.qty*i.unitPrice,0),oid=id('ORD'),ps=x.paymentMode==='PAY_NOW'?'PENDING':'UNPAID';await c.execute('INSERT INTO orders(id,session_id,station_id,status,payment_mode,payment_status,created_at,total) VALUES(?,?,?,?,?,?,?,?)',[oid,x.sessionId,s[0].station_id,'NEW',x.paymentMode,ps,now(),total]);for(const i of items)await c.execute('INSERT INTO order_items(order_id,item_id,name,qty,unit_price,participant_id) VALUES(?,?,?,?,?,?)',[oid,i.itemId,i.name,i.qty,i.unitPrice,pid]);return{id:oid,total,paymentMode:x.paymentMode,paymentStatus:ps};});}

export async function markCounterPaid(orderId:string){return transaction(async(c:PoolConnection)=>{const[r]=await c.query<RowDataPacket[]>('SELECT * FROM orders WHERE id=? FOR UPDATE',[orderId]);if(!r[0]||r[0].payment_mode!=='COUNTER')throw Error('Invalid counter order');if(r[0].payment_status==='PAID')return true;await c.execute('UPDATE orders SET payment_status=\'PAID\',paid_at=? WHERE id=?',[now(),orderId]);await c.execute('INSERT INTO payment_transactions(id,order_id,provider,status,amount,currency,created_at,updated_at,captured_at) VALUES(?,?,?,?,?,?,?,?,?)',[id('PAY'),orderId,'COUNTER','CAPTURED',r[0].total,'INR',now(),now(),now()]);await recordFoodRevenue(c,orderId,Number(r[0].total),'CASH');return true;});}

export async function markPaid(orderId:string,paymentId:string){return transaction(async(c:PoolConnection)=>{const[r]=await c.query<RowDataPacket[]>('SELECT * FROM orders WHERE id=? FOR UPDATE',[orderId]);if(!r[0])throw Error('Order not found');if(r[0].payment_status==='PAID'&&r[0].razorpay_payment_id===paymentId)return true;await c.execute('UPDATE orders SET payment_status=\'PAID\',paid_at=?,razorpay_payment_id=? WHERE id=?',[now(),paymentId,orderId]);await c.execute('UPDATE payment_transactions SET status=\'CAPTURED\',provider_payment_id=?,updated_at=?,captured_at=? WHERE order_id=? AND provider=\'RAZORPAY\' AND status IN (\'PENDING\',\'CREATED\') ORDER BY created_at DESC LIMIT 1',[paymentId,now(),now(),orderId]);await recordFoodRevenue(c,orderId,Number(r[0].total),'RAZORPAY');return true;});}
export async function belongsToCustomer(orderId:string,customerId:string){const[r]=await pool.query<RowDataPacket[]>('SELECT o.id FROM orders o JOIN order_items i ON i.order_id=o.id JOIN session_participants p ON p.id=i.participant_id WHERE o.id=? AND p.customer_id=? LIMIT 1',[orderId,customerId]);return !!r[0];}
