import {randomUUID} from 'node:crypto';
import type {PoolConnection,RowDataPacket} from 'mysql2/promise';
import {pool,transaction} from './mysql';

export type BillingParticipant={id:string;customerId?:string;displayName:string;memberId?:string;memberTier?:string;regularRate:number;memberRate:number;charge:number;joinedAt:string;leftAt?:string};
export type SessionBilling={sessionId:string;stationId:string;status:string;elapsedSeconds:number;billableSeconds:number;gamingTotal:number;participants:BillingParticipant[];currency:'INR';computedAt:string};
const id=(p:string)=>`${p}-${randomUUID()}`;
const activeMember=async(db:PoolConnection,memberId:string|null|undefined)=>{if(!memberId)return null;const[r]=await db.query<RowDataPacket[]>('SELECT id,tier FROM members WHERE id=? AND active=TRUE AND expires_at>=CURDATE() LIMIT 1',[memberId]);return r[0]||null};
function charge(seconds:number,rate:number){if(rate<=0||seconds<=0)return 0;const minutes=Math.ceil(seconds/60);return Math.ceil((minutes*rate)/60);}
function activeSeconds(start:string|Date,end:string|Date|null,pausedAt:string|Date|null,pausedTotal:number){const s=new Date(start).getTime(),e=new Date(end||new Date()).getTime();let p=Number(pausedTotal||0)*1000;if(pausedAt)p+=Math.max(0,e-new Date(pausedAt).getTime());return Math.max(0,Math.floor((e-s-p)/1000));}

export async function calculateSessionBilling(sessionId:string,db:PoolConnection|typeof pool=pool):Promise<SessionBilling>{
 const[s]=await db.query<RowDataPacket[]>('SELECT id,station_id,status,started_at,ended_at,paused_at,paused_total_seconds,member_id FROM sessions WHERE id=? LIMIT 1',[sessionId]);
 if(!s[0])throw Error('Session not found');
 const[st]=await db.query<RowDataPacket[]>('SELECT id,type,pc_tier,hourly_rate FROM stations WHERE id=? LIMIT 1',[s[0].station_id]);
 if(!st[0])throw Error('Station not found');
 const[ps]=await db.query<RowDataPacket[]>('SELECT id,customer_id,member_id,display_name,joined_at,left_at,billing_regular_rate,billing_member_rate,member_tier FROM session_participants WHERE session_id=? ORDER BY created_at',[sessionId]);
 const billable=activeSeconds(s[0].started_at,s[0].ended_at,s[0].paused_at,Number(s[0].paused_total_seconds));
 const participants:BillingParticipant[]=ps.map(p=>{const regular=Number(p.billing_regular_rate)||Number(st[0].hourly_rate);const member=Number(p.billing_member_rate)||regular;const rate=p.member_id&&p.member_tier?member:regular;return{id:String(p.id),customerId:p.customer_id?String(p.customer_id):undefined,displayName:String(p.display_name),memberId:p.member_id?String(p.member_id):undefined,memberTier:p.member_tier?String(p.member_tier):undefined,regularRate:regular,memberRate:member,charge:charge(billable,rate),joinedAt:new Date(p.joined_at||p.created_at).toISOString(),leftAt:p.left_at?new Date(p.left_at).toISOString():undefined};});
 let gamingTotal=participants.length?participants.reduce((n,p)=>n+p.charge,0):charge(billable,Number(st[0].hourly_rate));
 return{sessionId,stationId:String(s[0].station_id),status:String(s[0].status),elapsedSeconds:Math.max(0,Math.floor((new Date(s[0].ended_at||new Date()).getTime()-new Date(s[0].started_at).getTime())/1000)),billableSeconds:billable,gamingTotal,participants,currency:'INR',computedAt:new Date().toISOString()};
}

export async function addParticipant(input:{sessionId:string;customerId:string},actor='system'){return transaction(async(c)=>{const[s]=await c.query<RowDataPacket[]>('SELECT id,station_id,status FROM sessions WHERE id=? FOR UPDATE',[input.sessionId]);if(!s[0]||!['ACTIVE','PAUSED'].includes(String(s[0].status)))throw Error('Active session required');const[customer]=await c.query<RowDataPacket[]>('SELECT id,name,member_id FROM customers WHERE id=? LIMIT 1',[input.customerId]);if(!customer[0])throw Error('Customer not found');const[existing]=await c.query<RowDataPacket[]>('SELECT id FROM session_participants WHERE session_id=? AND customer_id=? AND active=TRUE LIMIT 1',[input.sessionId,input.customerId]);if(existing[0])return String(existing[0].id);const[station]=await c.query<RowDataPacket[]>('SELECT type,pc_tier,hourly_rate FROM stations WHERE id=? LIMIT 1',[s[0].station_id]);if(!station[0])throw Error('Station not found');let rate=Number(station[0].hourly_rate),memberRate=rate,memberTier:null|string=null;const[gr]=await c.query<RowDataPacket[]>('SELECT regular_price,member_price FROM gaming_rates WHERE station_type=? AND active=TRUE AND (pc_tier=? OR pc_tier IS NULL) ORDER BY (pc_tier IS NULL),id LIMIT 1',[station[0].type,station[0].pc_tier||null]);if(gr[0]){rate=Number(gr[0].regular_price);memberRate=Number(gr[0].member_price);}const member=await activeMember(c,customer[0].member_id);if(member)memberTier=String(member.tier);const pid=id('PAR');await c.execute('INSERT INTO session_participants(id,session_id,customer_id,member_id,display_name,active,created_at,joined_at,billing_regular_rate,billing_member_rate,member_tier) VALUES(?,?,?,?,?,?,NOW(3),NOW(3),?,?,?)',[pid,input.sessionId,customer[0].id,member?customer[0].member_id:null,String(customer[0].name||'Guest').slice(0,120),1,rate,memberRate,memberTier]);return pid;});}

export async function pauseSession(sessionId:string){return transaction(async(c)=>{const[r]=await c.query<RowDataPacket[]>('SELECT status,paused_at FROM sessions WHERE id=? FOR UPDATE',[sessionId]);if(!r[0])throw Error('Session not found');if(r[0].status==='PAUSED')return; if(r[0].status!=='ACTIVE')throw Error('Only active sessions can be paused');await c.execute("UPDATE sessions SET status='PAUSED',paused_at=? WHERE id=?",[new Date(),sessionId]);});}
export async function resumeSession(sessionId:string){return transaction(async(c)=>{const[r]=await c.query<RowDataPacket[]>('SELECT status,paused_at,paused_total_seconds FROM sessions WHERE id=? FOR UPDATE',[sessionId]);if(!r[0])throw Error('Session not found');if(r[0].status==='ACTIVE')return;if(r[0].status!=='PAUSED'||!r[0].paused_at)throw Error('Only paused sessions can be resumed');const extra=Math.max(0,Math.floor((Date.now()-new Date(r[0].paused_at).getTime())/1000));await c.execute("UPDATE sessions SET status='ACTIVE',paused_at=NULL,paused_total_seconds=paused_total_seconds+? WHERE id=?",[extra,sessionId]);});}

export async function finalizeSessionBilling(sessionId:string){return transaction(async(c)=>{const billing=await calculateSessionBilling(sessionId,c);await c.execute('UPDATE sessions SET gaming_balance=? WHERE id=?',[billing.gamingTotal,sessionId]);return billing;});}
