import {randomUUID} from 'node:crypto';
import type {PoolConnection, RowDataPacket} from 'mysql2/promise';
import {pool, transaction} from './mysql';

export type BillingParticipant={id:string;customerId?:string;displayName:string;memberId?:string;memberTier?:string;regularRate:number;memberRate:number;charge:number;joinedAt:string;leftAt?:string};
export type SessionBilling={sessionId:string;stationId:string;status:string;elapsedSeconds:number;billableSeconds:number;gamingTotal:number;participants:BillingParticipant[];currency:'INR';computedAt:string};
const id=(p:string)=>`${p}-${randomUUID()}`;
const activeMember=async(db:PoolConnection,memberId:string|null|undefined)=>{if(!memberId)return null;const[r]=await db.query<RowDataPacket[]>('SELECT id,tier FROM members WHERE id=? AND active=TRUE AND expires_at>=CURDATE() LIMIT 1',[memberId]);return r[0]||null};
function charge(seconds:number,rate:number){if(rate<=0||seconds<=0)return 0;return Math.ceil((Math.ceil(seconds/60)*rate)/60)}
function overlapPaused(start:number,end:number,periods:Array<{started_at:string|Date;ended_at:string|Date|null}>){return periods.reduce((total,p)=>{const ps=new Date(p.started_at).getTime(),pe=p.ended_at?new Date(p.ended_at).getTime():end;return total+Math.max(0,Math.min(end,pe)-Math.max(start,ps))},0)}
function secondsFor(start:string|Date,end:string|Date|null,periods:Array<{started_at:string|Date;ended_at:string|Date|null}>){const s=new Date(start).getTime(),e=new Date(end||new Date()).getTime();return Math.max(0,Math.floor((e-s-overlapPaused(s,e,periods))/1000))}

export async function calculateSessionBilling(sessionId:string,db:PoolConnection|typeof pool=pool):Promise<SessionBilling>{
 const[s]=await db.query<RowDataPacket[]>('SELECT id,station_id,status,started_at,ended_at,paused_at,paused_total_seconds FROM sessions WHERE id=? LIMIT 1',[sessionId]);
 if(!s[0])throw Error('Session not found');
 const[st]=await db.query<RowDataPacket[]>('SELECT id,type,pc_tier,hourly_rate FROM stations WHERE id=? LIMIT 1',[s[0].station_id]);
 if(!st[0])throw Error('Station not found');
 const[ps]=await db.query<RowDataPacket[]>('SELECT id,customer_id,member_id,display_name,created_at,joined_at,left_at,billing_regular_rate,billing_member_rate,member_tier FROM session_participants WHERE session_id=? ORDER BY created_at',[sessionId]);
 const[pauseRows]=await db.query<RowDataPacket[]>('SELECT started_at,ended_at FROM session_pause_periods WHERE session_id=? ORDER BY started_at',[sessionId]);
 const periods=pauseRows as Array<{started_at:string|Date;ended_at:string|Date|null}>;
 const sessionStart=new Date(s[0].started_at).getTime(),sessionEnd=new Date(s[0].ended_at||new Date()).getTime();
 const elapsedSeconds=Math.max(0,Math.floor((sessionEnd-sessionStart)/1000));
 const billableSeconds=periods.length?secondsFor(s[0].started_at,s[0].ended_at,periods):Math.max(0,elapsedSeconds-Number(s[0].paused_total_seconds||0));
 const participants:BillingParticipant[]=ps.map(p=>{const regular=Number(p.billing_regular_rate)||Number(st[0].hourly_rate);const member=Number(p.billing_member_rate)||regular;const rate=p.member_id&&p.member_tier?member:regular;const start=p.joined_at||p.created_at;const participantSeconds=periods.length?secondsFor(start,p.left_at||s[0].ended_at,periods):secondsFor(start,p.left_at||s[0].ended_at,[]);return{id:String(p.id),customerId:p.customer_id?String(p.customer_id):undefined,displayName:String(p.display_name),memberId:p.member_id?String(p.member_id):undefined,memberTier:p.member_tier?String(p.member_tier):undefined,regularRate:regular,memberRate:member,charge:charge(participantSeconds,rate),joinedAt:new Date(start).toISOString(),leftAt:p.left_at?new Date(p.left_at).toISOString():undefined}});
 const gamingTotal=participants.length?participants.reduce((n,p)=>n+p.charge,0):charge(billableSeconds,Number(st[0].hourly_rate));
 return{sessionId,stationId:String(s[0].station_id),status:String(s[0].status),elapsedSeconds,billableSeconds,gamingTotal,participants,currency:'INR',computedAt:new Date().toISOString()};
}

async function rateForStation(c:PoolConnection,station:{type:string;pc_tier?:string|null;hourly_rate:number}){let regular=Number(station.hourly_rate),memberRate=regular;const[gr]=await c.query<RowDataPacket[]>('SELECT regular_price,member_price FROM gaming_rates WHERE station_type=? AND active=TRUE AND (pc_tier=? OR pc_tier IS NULL) ORDER BY (pc_tier IS NULL),id LIMIT 1',[station.type,station.pc_tier||null]);if(gr[0]){regular=Number(gr[0].regular_price);memberRate=Number(gr[0].member_price)}return{regular,memberRate}}

export async function addParticipant(input:{sessionId:string;customerId:string},actor='system'){return transaction(async(c)=>{const[s]=await c.query<RowDataPacket[]>('SELECT id,station_id,status FROM sessions WHERE id=? FOR UPDATE',[input.sessionId]);if(!s[0]||!['ACTIVE','PAUSED'].includes(String(s[0].status)))throw Error('Active session required');const[customer]=await c.query<RowDataPacket[]>('SELECT id,name,member_id FROM customers WHERE id=? LIMIT 1',[input.customerId]);if(!customer[0])throw Error('Customer not found');const[existing]=await c.query<RowDataPacket[]>('SELECT id FROM session_participants WHERE session_id=? AND customer_id=? AND active=TRUE LIMIT 1',[input.sessionId,input.customerId]);if(existing[0])return String(existing[0].id);const[station]=await c.query<RowDataPacket[]>('SELECT type,pc_tier,hourly_rate FROM stations WHERE id=? LIMIT 1',[s[0].station_id]);if(!station[0])throw Error('Station not found');const rates=await rateForStation(c,station[0] as {type:string;pc_tier?:string|null;hourly_rate:number});const member=await activeMember(c,customer[0].member_id);const pid=id('PAR');await c.execute('INSERT INTO session_participants(id,session_id,customer_id,member_id,display_name,active,created_at,joined_at,billing_regular_rate,billing_member_rate,member_tier) VALUES(?,?,?,?,?,?,NOW(3),NOW(3),?,?,?)',[pid,input.sessionId,customer[0].id,member?customer[0].member_id:null,String(customer[0].name||'Guest').slice(0,120),1,rates.regular,rates.memberRate,member?String(member.tier):null]);return pid;});}

export async function leaveParticipant(sessionId:string,participantId:string){return transaction(async(c)=>{const[r]=await c.query<RowDataPacket[]>('SELECT id FROM session_participants WHERE id=? AND session_id=? AND active=TRUE FOR UPDATE',[participantId,sessionId]);if(!r[0])throw Error('Active participant not found');await c.execute('UPDATE session_participants SET active=FALSE,left_at=? WHERE id=?',[new Date(),participantId]);return true;});}

export async function pauseSession(sessionId:string){return transaction(async(c)=>{const[r]=await c.query<RowDataPacket[]>('SELECT status,paused_at FROM sessions WHERE id=? FOR UPDATE',[sessionId]);if(!r[0])throw Error('Session not found');if(r[0].status==='PAUSED')return;if(r[0].status!=='ACTIVE')throw Error('Only active sessions can be paused');const pauseId=id('PAUSE');await c.execute('UPDATE sessions SET status=\'PAUSED\',paused_at=? WHERE id=?',[new Date(),sessionId]);await c.execute('INSERT INTO session_pause_periods(id,session_id,started_at,created_at) VALUES(?,?,?,?)',[pauseId,sessionId,new Date(),new Date()]);});}
export async function resumeSession(sessionId:string){return transaction(async(c)=>{const[r]=await c.query<RowDataPacket[]>('SELECT status,paused_at,paused_total_seconds FROM sessions WHERE id=? FOR UPDATE',[sessionId]);if(!r[0])throw Error('Session not found');if(r[0].status==='ACTIVE')return;if(r[0].status!=='PAUSED'||!r[0].paused_at)throw Error('Only paused sessions can be resumed');const resumedAt=new Date();const extra=Math.max(0,Math.floor((resumedAt.getTime()-new Date(r[0].paused_at).getTime())/1000));await c.execute("UPDATE sessions SET status='ACTIVE',paused_at=NULL,paused_total_seconds=paused_total_seconds+? WHERE id=?",[extra,sessionId]);await c.execute('UPDATE session_pause_periods SET ended_at=? WHERE session_id=? AND ended_at IS NULL',[resumedAt,sessionId]);});}

export async function reconcileBookingDeposit(sessionId:string){return transaction(async(c)=>{const[b]=await c.query<RowDataPacket[]>('SELECT id,deposit FROM bookings WHERE session_id=? FOR UPDATE',[sessionId]);if(!b[0]||Number(b[0].deposit)<=0)return {bookingId:null,applied:0,refundable:0};const[paid]=await c.query<RowDataPacket[]>("SELECT id,amount FROM booking_deposit_payments WHERE booking_id=? AND status='CAPTURED' ORDER BY created_at,id FOR UPDATE",[b[0].id]);if(!paid.length)return {bookingId:String(b[0].id),applied:0,refundable:0};const[appliedRows]=await c.query<RowDataPacket[]>('SELECT COALESCE(SUM(amount),0) total FROM booking_deposit_applications WHERE booking_id=?',[b[0].id]);let remainingDeposit=Math.max(0,Number(paid.reduce((n,r)=>n+Number(r.amount),0))-Number(appliedRows[0]?.total||0));if(!remainingDeposit)return {bookingId:String(b[0].id),applied:0,refundable:0};const billing=await calculateSessionBilling(sessionId,c);let remainingBill=billing.gamingTotal;let appliedNow=0;for(const payment of paid){if(remainingDeposit<=0||remainingBill<=0)break;const[already]=await c.query<RowDataPacket[]>('SELECT COALESCE(SUM(amount),0) total FROM booking_deposit_applications WHERE payment_id=?',[payment.id]);const available=Math.max(0,Number(payment.amount)-Number(already[0]?.total||0));const amount=Math.min(available,remainingDeposit,remainingBill);if(amount>0){await c.execute('INSERT INTO booking_deposit_applications(id,booking_id,session_id,payment_id,amount,created_at) VALUES(?,?,?,?,?,NOW(3))',[id('BDA'),b[0].id,sessionId,payment.id,amount]);appliedNow+=amount;remainingDeposit-=amount;remainingBill-=amount;}}
 return {bookingId:String(b[0].id),applied:appliedNow,refundable:remainingDeposit};});}

export async function finalizeSessionBilling(sessionId:string){return transaction(async(c)=>{const billing=await calculateSessionBilling(sessionId,c);await c.execute('UPDATE sessions SET gaming_balance=? WHERE id=?',[billing.gamingTotal,sessionId]);return billing;});}
