import {randomBytes} from 'node:crypto';
import type {RowDataPacket} from 'mysql2/promise';
import {pool} from './mysql';

export type GovernmentIdType='AADHAAR'|'PAN'|'PASSPORT'|'DRIVING_LICENSE'|'VOTER_ID'|'OTHER';
export type Member={id:string;name:string;mobile:string;active:boolean};
const id=()=>`GENZFAM${String(Math.floor(Math.random()*900)+100)}`;
const map=(r:any):Member=>({id:r.id,name:r.name,mobile:r.mobile,active:Boolean(r.active)});
export async function findMember(memberId:string){const [rows]=await pool.query<(RowDataPacket&{id:string;name:string;mobile:string;active:number})[]>('SELECT id,name,mobile,active FROM members WHERE id=? LIMIT 1',[memberId.trim()]);return rows[0]?map(rows[0]):null;}
export async function findMemberByMobile(mobile:string){const [rows]=await pool.query<(RowDataPacket&{id:string;name:string;mobile:string;active:number})[]>('SELECT id,name,mobile,active FROM members WHERE mobile=? LIMIT 1',[mobile.trim()]);return rows[0]?map(rows[0]):null;}
export async function listMembers(search=''){const q=search.trim();const values=q?[`%${q}%`,`%${q}%`,`%${q}%`]:[];const sql='SELECT id,name,mobile,active FROM members '+(q?'WHERE id LIKE ? OR name LIKE ? OR mobile LIKE ? ':'')+'ORDER BY active DESC,name LIMIT 200';const [rows]=await pool.query<(RowDataPacket&{id:string;name:string;mobile:string;active:number})[]>(sql,values);return rows.map(map);}
export async function createMember(input:{id?:string;name:string;mobile:string;governmentIdType:GovernmentIdType;governmentIdNumber:string}){const memberId=(input.id||id()).trim();if(!/^GENZFAM\d{3}$/.test(memberId))throw new Error('INVALID_MEMBER_ID');if(!input.name.trim()||!/^[0-9+() -]{7,20}$/.test(input.mobile.trim()))throw new Error('INVALID_MEMBER_DETAILS');if(!['AADHAAR','PAN','PASSPORT','DRIVING_LICENSE','VOTER_ID','OTHER'].includes(input.governmentIdType)||input.governmentIdNumber.trim().length<3||input.governmentIdNumber.trim().length>120)throw new Error('INVALID_GOVERNMENT_ID');await pool.execute('INSERT INTO members(id,name,mobile,government_id_type,government_id_number,active,created_at,updated_at) VALUES(?,?,?,?,?,TRUE,NOW(3),NOW(3))',[memberId,input.name.trim(),input.mobile.trim(),input.governmentIdType,input.governmentIdNumber.trim()]);return findMember(memberId);}
export async function updateMember(memberId:string,input:{name?:string;mobile?:string;governmentIdType?:GovernmentIdType;governmentIdNumber?:string;active?:boolean}){const fields:string[]=[];const values:Array<string|number|boolean>=[];if(input.name!==undefined){if(!input.name.trim())throw new Error('INVALID_NAME');fields.push('name=?');values.push(input.name.trim())}if(input.mobile!==undefined){if(!/^[0-9+() -]{7,20}$/.test(input.mobile.trim()))throw new Error('INVALID_MOBILE');fields.push('mobile=?');values.push(input.mobile.trim())}if(input.governmentIdType!==undefined){if(!['AADHAAR','PAN','PASSPORT','DRIVING_LICENSE','VOTER_ID','OTHER'].includes(input.governmentIdType))throw Error('INVALID_GOVERNMENT_ID');fields.push('government_id_type=?');values.push(input.governmentIdType)}if(input.governmentIdNumber!==undefined){if(input.governmentIdNumber.trim().length<3||input.governmentIdNumber.trim().length>120)throw Error('INVALID_GOVERNMENT_ID');fields.push('government_id_number=?');values.push(input.governmentIdNumber.trim())}if(input.active!==undefined){fields.push('active=?');values.push(input.active)}if(!fields.length)throw new Error('NO_CHANGES');fields.push('updated_at=NOW(3)');values.push(memberId.trim());const [result]=await pool.execute('UPDATE members SET '+fields.join(',')+' WHERE id=?',values);if((result as {affectedRows:number}).affectedRows!==1)throw new Error('MEMBER_NOT_FOUND');return findMember(memberId);}
