import { createHmac } from 'node:crypto';

const keyId=()=>process.env.GENZ_RAZORPAY_KEY_ID||'';
const keySecret=()=>process.env.GENZ_RAZORPAY_KEY_SECRET||'';
export function razorpayConfigured(){return Boolean(keyId()&&keySecret());}
export function getRazorpayKeyId(){if(!keyId())throw new Error('Payment gateway is not configured');return keyId();}
export type RazorpayOrder={id:string;amount:number;currency:'INR'};
export type RazorpayPayment={id:string;orderId:string;amount:number;currency:'INR';status:string;createdAt?:string;method?:string};
export type RazorpayRefund={id:string;paymentId:string;amount:number;currency:'INR';status:string;createdAt?:string};
export type RazorpaySettlement={id:string;amount:number;status:string;createdAt?:string;reference?:string;utr?:string};
async function razorpayRequest(path:string,init?:RequestInit){const secret=keySecret();if(!keyId()||!secret)throw new Error('Payment gateway is not configured');const response=await fetch(`https://api.razorpay.com/v1/${path}`,{...init,headers:{Authorization:`Basic ${Buffer.from(`${keyId()}:${secret}`).toString('base64')}`,'Content-Type':'application/json',...(init?.headers||{})},cache:'no-store'});if(!response.ok)throw new Error(`Razorpay API error ${response.status}`);return response.json() as Promise<Record<string,unknown>>;}
async function razorpayFetch(path:string){return razorpayRequest(path,{method:'GET'});}
export async function createRazorpayOrder(input:{amountRupees:number;receipt:string}):Promise<RazorpayOrder>{if(!Number.isSafeInteger(input.amountRupees)||input.amountRupees<1)throw new Error('Invalid payment amount');const data=await razorpayRequest('orders',{method:'POST',body:JSON.stringify({amount:input.amountRupees*100,currency:'INR',receipt:input.receipt})});if(typeof data.id!=='string'||data.amount!==input.amountRupees*100||data.currency!=='INR')throw new Error('Invalid payment gateway response');return{id:data.id,amount:data.amount as number,currency:'INR'};}
export async function fetchRazorpayPayment(paymentId:string):Promise<RazorpayPayment>{if(!/^pay_[A-Za-z0-9]+$/.test(paymentId))throw new Error('Invalid payment id');const data=await razorpayFetch(`payments/${encodeURIComponent(paymentId)}`);if(typeof data.id!=='string'||typeof data.order_id!=='string'||typeof data.amount!=='number'||data.currency!=='INR'||typeof data.status!=='string')throw new Error('Invalid payment gateway response');return{id:data.id,orderId:data.order_id,amount:data.amount,currency:'INR',status:data.status,createdAt:typeof data.created_at==='number'?new Date(data.created_at*1000).toISOString():undefined,method:typeof data.method==='string'?data.method:undefined};}
export async function fetchRazorpayRefund(refundId:string):Promise<RazorpayRefund>{if(!/^rfnd_[A-Za-z0-9]+$/.test(refundId))throw new Error('Invalid refund id');const data=await razorpayFetch(`refunds/${encodeURIComponent(refundId)}`);if(typeof data.id!=='string'||typeof data.payment_id!=='string'||typeof data.amount!=='number'||data.currency!=='INR'||typeof data.status!=='string')throw new Error('Invalid payment gateway response');return{id:data.id,paymentId:data.payment_id,amount:data.amount,currency:'INR',status:data.status,createdAt:typeof data.created_at==='number'?new Date(data.created_at*1000).toISOString():undefined};}
export async function fetchRazorpayPayments(count=100){const safe=Math.min(Math.max(Math.floor(count),1),100);const data=await razorpayFetch(`payments?count=${safe}`);return(Array.isArray(data.items)?data.items:[]).map((x:any)=>({id:String(x.id),orderId:String(x.order_id||''),amount:Number(x.amount||0),currency:String(x.currency||'INR'),status:String(x.status||''),createdAt:typeof x.created_at==='number'?new Date(x.created_at*1000).toISOString():undefined,method:typeof x.method==='string'?x.method:undefined}));}
export async function fetchRazorpayRefunds(count=100){const safe=Math.min(Math.max(Math.floor(count),1),100);const data=await razorpayFetch(`refunds?count=${safe}`);return(Array.isArray(data.items)?data.items:[]).map((x:any)=>({id:String(x.id),paymentId:String(x.payment_id||''),amount:Number(x.amount||0),currency:String(x.currency||'INR'),status:String(x.status||''),createdAt:typeof x.created_at==='number'?new Date(x.created_at*1000).toISOString():undefined}));}
export async function fetchRazorpaySettlements(count=100){const safe=Math.min(Math.max(Math.floor(count),1),100);const data=await razorpayFetch(`settlements?count=${safe}`);return(Array.isArray(data.items)?data.items:[]).map((x:any)=>({id:String(x.id),amount:Number(x.amount||0),status:String(x.status||''),createdAt:typeof x.created_at==='number'?new Date(x.created_at*1000).toISOString():undefined,reference:typeof x.reference==='string'?x.reference:undefined,utr:typeof x.utr==='string'?x.utr:undefined}));}
export async function createRazorpayRefund(paymentId:string,amountRupees:number,receipt?:string){if(!/^pay_[A-Za-z0-9]+$/.test(paymentId)||!Number.isSafeInteger(amountRupees)||amountRupees<1)throw new Error('Invalid refund request');const data=await razorpayRequest(`payments/${encodeURIComponent(paymentId)}/refund`,{method:'POST',body:JSON.stringify({amount:amountRupees*100,speed:'normal',...(receipt?{receipt}: {})})});if(typeof data.id!=='string'||typeof data.payment_id!=='string'||typeof data.amount!=='number'||data.currency!=='INR'||typeof data.status!=='string')throw new Error('Invalid refund gateway response');return{id:data.id,paymentId:data.payment_id,amount:data.amount,currency:'INR',status:data.status,createdAt:typeof data.created_at==='number'?new Date(data.created_at*1000).toISOString():undefined};}
export function verifyRazorpaySignature(orderId:string,paymentId:string,signature:string){const secret=keySecret();if(!secret)throw new Error('Payment gateway is not configured');const expected=createHmac('sha256',secret).update(`${orderId}|${paymentId}`).digest('hex');if(expected.length!==signature.length)return false;return createHmac('sha256',secret).update(expected).digest().equals(createHmac('sha256',secret).update(signature).digest());}
export function verifyRazorpayWebhook(rawBody:string,signature:string){const secret=process.env.GENZ_RAZORPAY_WEBHOOK_SECRET||'';if(!secret||!signature)return false;const expected=createHmac('sha256',secret).update(rawBody).digest('hex');if(expected.length!==signature.length)return false;return createHmac('sha256',secret).update(expected).digest().equals(createHmac('sha256',secret).update(signature).digest());}
