import { createHmac } from 'node:crypto';

const keyId=()=>process.env.GENZ_RAZORPAY_KEY_ID||'';
const keySecret=()=>process.env.GENZ_RAZORPAY_KEY_SECRET||'';
export function razorpayConfigured(){return Boolean(keyId()&&keySecret());}
export function getRazorpayKeyId(){if(!keyId())throw new Error('Payment gateway is not configured');return keyId();}
export type RazorpayOrder={id:string;amount:number;currency:'INR'};
export type RazorpayPayment={id:string;orderId:string;amount:number;currency:'INR';status:string};
async function razorpayFetch(path:string){const secret=keySecret();if(!keyId()||!secret)throw new Error('Payment gateway is not configured');const response=await fetch(`https://api.razorpay.com/v1/${path}`,{method:'GET',headers:{Authorization:`Basic ${Buffer.from(`${keyId()}:${secret}`).toString('base64')}`},cache:'no-store'});if(!response.ok)throw new Error('Unable to verify payment with gateway');return response.json() as Promise<Record<string,unknown>>;}
export async function createRazorpayOrder(input:{amountRupees:number;receipt:string}):Promise<RazorpayOrder>{const secret=keySecret();if(!keyId()||!secret)throw new Error('Payment gateway is not configured');if(!Number.isSafeInteger(input.amountRupees)||input.amountRupees<1)throw new Error('Invalid payment amount');const response=await fetch('https://api.razorpay.com/v1/orders',{method:'POST',headers:{Authorization:`Basic ${Buffer.from(`${keyId()}:${secret}`).toString('base64')}`,'Content-Type':'application/json'},body:JSON.stringify({amount:input.amountRupees*100,currency:'INR',receipt:input.receipt}),cache:'no-store'});if(!response.ok)throw new Error('Unable to create payment order');const data=await response.json() as {id?:unknown;amount?:unknown;currency?:unknown};if(typeof data.id!=='string'||!data.id||data.amount!==input.amountRupees*100||data.currency!=='INR')throw new Error('Invalid payment gateway response');return{id:data.id,amount:input.amountRupees*100,currency:'INR'};}
export async function fetchRazorpayPayment(paymentId:string):Promise<RazorpayPayment>{if(!/^pay_[A-Za-z0-9]+$/.test(paymentId))throw new Error('Invalid payment id');const data=await razorpayFetch(`payments/${encodeURIComponent(paymentId)}`);if(typeof data.id!=='string'||typeof data.order_id!=='string'||typeof data.amount!=='number'||data.currency!=='INR'||typeof data.status!=='string')throw new Error('Invalid payment gateway response');return{id:data.id,orderId:data.order_id,amount:data.amount,currency:'INR',status:data.status};}
export function verifyRazorpaySignature(orderId:string,paymentId:string,signature:string){const secret=keySecret();if(!secret)throw new Error('Payment gateway is not configured');const expected=createHmac('sha256',secret).update(`${orderId}|${paymentId}`).digest('hex');if(expected.length!==signature.length)return false;return createHmac('sha256',secret).update(expected).digest().equals(createHmac('sha256',secret).update(signature).digest());}
export function verifyRazorpayWebhook(rawBody:string,signature:string){const secret=process.env.GENZ_RAZORPAY_WEBHOOK_SECRET||'';if(!secret||!signature)return false;const expected=createHmac('sha256',secret).update(rawBody).digest('hex');if(expected.length!==signature.length)return false;return createHmac('sha256',secret).update(expected).digest().equals(createHmac('sha256',secret).update(signature).digest());}
