import {randomUUID} from 'node:crypto';
import type {PoolConnection,RowDataPacket} from 'mysql2/promise';
import {pool,transaction} from './mysql';

export type SessionGroup={id:string;name:string;sessionIds:string[];total:number;createdAt:string};
const id=()=>`GRP-${randomUUID()}`;

export async function createSessionGroup(sessionIds:string[],name?:string){const ids=[...new Set(sessionIds.map(String))];if(ids.length<2||ids.length>20)throw new Error('Select 2 to 20 sessions');return transaction(async(c:PoolConnection)=>{const p=ids.map(()=>'?').join(',');const [rows]=await c.query<RowDataPacket[]>(`SELECT id,status,station_id FROM sessions WHERE id IN (${p}) FOR UPDATE`,ids);if(rows.length!==ids.length)throw new Error('One or more sessions not found');if(rows.some(r=>!['ACTIVE','PAUSED'].includes(String(r.status))))throw new Error('Only active sessions can be grouped');const [existing]=await c.query<RowDataPacket[]>(`SELECT s.id FROM sessions s JOIN session_group_members gm ON gm.session_id=s.id JOIN session_groups g ON g.id=gm.group_id WHERE s.id IN (${p}) AND g.status='OPEN' LIMIT 1`,ids);if(existing.length)throw new Error('A session is already in another open group');const groupId=id();const groupName=(name||`Group ${groupId.slice(-6)}`).trim().slice(0,100);await c.execute('INSERT INTO session_groups(id,name,status,created_at) VALUES(?,?,\'OPEN\',?)',[groupId,groupName,new Date()]);for(const sessionId of ids)await c.execute('INSERT INTO session_group_members(group_id,session_id,created_at) VALUES(?,?,?)',[groupId,sessionId,new Date()]);return getSessionGroupOn(c,groupId);});}

async function getSessionGroupOn(c:PoolConnection,groupId:string):Promise<SessionGroup>{const [groups]=await c.query<RowDataPacket[]>('SELECT id,name,created_at FROM session_groups WHERE id=? LIMIT 1',[groupId]);if(!groups.length)throw new Error('Group not found');const [members]=await c.query<RowDataPacket[]>('SELECT session_id FROM session_group_members WHERE group_id=? ORDER BY created_at',[groupId]);const ids=members.map(r=>String(r.session_id));if(!ids.length)return{id:groupId,name:String(groups[0].name),sessionIds:[],total:0,createdAt:new Date(groups[0].created_at).toISOString()};const p=ids.map(()=>'?').join(',');const [sessions]=await c.query<RowDataPacket[]>(`SELECT COALESCE(SUM(gaming_balance+food_balance),0) total FROM sessions WHERE id IN (${p})`,ids);return{id:groupId,name:String(groups[0].name),sessionIds:ids,total:Number(sessions[0]?.total||0),createdAt:new Date(groups[0].created_at).toISOString()};}

export async function listSessionGroups(){const [groups]=await pool.query<RowDataPacket[]>(`SELECT g.id,g.name,g.created_at,COALESCE(SUM(s.gaming_balance+s.food_balance),0) total,COUNT(gm.session_id) session_count FROM session_groups g JOIN session_group_members gm ON gm.group_id=g.id JOIN sessions s ON s.id=gm.session_id WHERE g.status='OPEN' GROUP BY g.id,g.name,g.created_at ORDER BY g.created_at DESC`);return groups.map(g=>({id:String(g.id),name:String(g.name),sessionIds:[],total:Number(g.total),sessionCount:Number(g.session_count),createdAt:new Date(g.created_at).toISOString()}));}

export async function getSessionGroup(groupId:string){return transaction(async(c)=>getSessionGroupOn(c,groupId));}
export async function closeSessionGroup(groupId:string){return transaction(async(c)=>{const [result]=await c.execute('UPDATE session_groups SET status=\'CLOSED\',closed_at=? WHERE id=? AND status=\'OPEN\'',[new Date(),groupId]);if((result as {affectedRows:number}).affectedRows!==1)throw new Error('Group is already closed or not found');return getSessionGroupOn(c,groupId);});}
