import {createHash,createHmac,randomBytes,scrypt as scryptCallback,timingSafeEqual} from 'node:crypto';
import {promisify} from 'node:util';
import type {RowDataPacket} from 'mysql2/promise';
import {pool} from './mysql';
const scrypt=promisify(scryptCallback),COOKIE='genz_staff',ROLE_COOKIE='genz_staff_role',TTL_MS=12*60*60*1000,IDLE_MS=45*60*1000,LOGIN_RATE_KEY='__genz_staff_login_rate__';
const loginStore=globalThis as typeof globalThis & {[LOGIN_RATE_KEY]?:Map<string,number[]>};const loginRates=loginStore[LOGIN_RATE_KEY]??(loginStore[LOGIN_RATE_KEY]=new Map());
export type StaffRole='OWNER'|'MANAGER'|'DEVELOPER';export type Staff={id:string;username:string;name:string;role:StaffRole};
const hashToken=(v:string)=>createHash('sha256').update(v).digest('hex'),id=()=>`STF-${randomBytes(12).toString('hex')}`;
const sessionSigningSecret=()=>{const secret=process.env.GENZ_SESSION_SIGNING_SECRET||'';if(!secret)throw new Error('GENZ_SESSION_SIGNING_SECRET is required');return secret};
export function signStaffRole(role:StaffRole){const payload=Buffer.from(role).toString('base64url');const signature=createHmac('sha256',sessionSigningSecret()).update(payload).digest('base64url');return `${payload}.${signature}`}
export function verifyStaffRole(value:string|undefined|null):StaffRole|null{if(!value)return null;const [payload,signature]=value.split('.');if(!payload||!signature)return null;const expected=createHmac('sha256',sessionSigningSecret()).update(payload).digest('base64url');if(expected.length!==signature.length||!timingSafeEqual(Buffer.from(expected),Buffer.from(signature)))return null;const role=Buffer.from(payload,'base64url').toString('utf8');return role==='OWNER'||role==='MANAGER'||role==='DEVELOPER'?role:null}
const loginAllowed=(key:string)=>{const now=Date.now(),values=(loginRates.get(key)||[]).filter((t:number)=>t>now-15*60*1000);if(values.length>=10){loginRates.set(key,values);return false}values.push(now);loginRates.set(key,values);if(loginRates.size>5000)for(const[k,v]of loginRates)if(!v.some((t:number)=>t>now-60*60*1000))loginRates.delete(k);return true};const loginSuccess=(key:string)=>loginRates.delete(key);
async function passwordHash(password:string){const salt=randomBytes(16).toString('hex');const derived=await scrypt(password,salt,64) as Buffer;return `scrypt$${salt}$${derived.toString('hex')}`};async function passwordMatches(password:string,stored:string){const[kind,salt,hex]=stored.split('$');if(kind!=='scrypt'||!salt||!hex)return false;const derived=await scrypt(password,salt,64) as Buffer,expected=Buffer.from(hex,'hex');return expected.length===derived.length&&timingSafeEqual(expected,derived)}
export async function ensureInitialOwner(){const[rows]=await pool.query<RowDataPacket[]>('SELECT id FROM staff_users LIMIT 1');if(rows.length)return;const username=(process.env.GENZ_STAFF_INITIAL_USERNAME||'owner').trim().toLowerCase(),password=process.env.GENZ_STAFF_INITIAL_PASSWORD;if(!password)return;const name=process.env.GENZ_STAFF_INITIAL_NAME||'Owner',hash=await passwordHash(password);await pool.execute('INSERT IGNORE INTO staff_users(id,username,name,password_hash,role,active,created_at,updated_at) VALUES(?,?,?,?,?,?,NOW(3),NOW(3))',[id(),username,name,hash,'OWNER',true])}
export async function loginStaff(username:string,password:string,sourceKey='unknown'){const normalized=username.trim().toLowerCase(),userKey=`user:${normalized}`,source=sourceKey&&sourceKey!=='unknown'?sourceKey:'unknown';if(!loginAllowed(`source:${source}`)||!loginAllowed(userKey))throw new Error('STAFF_RATE_LIMITED');await ensureInitialOwner();const[recent]=await pool.query<RowDataPacket[]>('SELECT id FROM staff_login_attempts WHERE username=? AND succeeded=FALSE AND created_at>=DATE_SUB(NOW(3),INTERVAL 10 MINUTE) LIMIT 8',[normalized]);if(recent.length>=8)throw new Error('STAFF_RATE_LIMITED');const[rows]=await pool.query<(RowDataPacket&{id:string;username:string;name:string;password_hash:string;role:StaffRole})[]>('SELECT id,username,name,password_hash,role FROM staff_users WHERE username=? AND active=TRUE LIMIT 1',[normalized]);const user=rows[0],ok=user?await passwordMatches(password,user.password_hash):false;await pool.execute('INSERT INTO staff_login_attempts(username,succeeded,created_at) VALUES(?,?,NOW(3))',[normalized,ok]);if(!user||!ok)return null;loginSuccess(userKey);return await createStaffSession(user)}
async function createStaffSession(user:{id:string;username:string;name:string;role:StaffRole}){const token=randomBytes(32).toString('hex'),expires=new Date(Date.now()+TTL_MS);await pool.execute('INSERT INTO staff_sessions(id,staff_id,token_hash,expires_at,created_at,last_seen_at) VALUES(?,?,?,?,NOW(3),NOW(3))',[id(),user.id,hashToken(token),expires]);return{token,staff:{id:user.id,username:user.username,name:user.name,role:user.role},roleCookie:signStaffRole(user.role),expiresAt:expires.toISOString()}}
export async function getStaffByToken(token?:string|null):Promise<Staff|null>{if(!token)return null;const tokenHash=hashToken(token);const[rows]=await pool.query<(RowDataPacket&Staff&{expires_at:string;last_seen_at:string})[]>('SELECT u.id,u.username,u.name,u.role,s.expires_at,s.last_seen_at FROM staff_sessions s JOIN staff_users u ON u.id=s.staff_id WHERE s.token_hash=? AND s.expires_at>NOW(3) AND s.last_seen_at>DATE_SUB(NOW(3),INTERVAL 45 MINUTE) AND u.active=TRUE LIMIT 1',[tokenHash]);const row=rows[0];if(!row){await pool.execute('DELETE FROM staff_sessions WHERE token_hash=?',[tokenHash]);return null}await pool.execute('UPDATE staff_sessions SET last_seen_at=NOW(3) WHERE token_hash=?',[tokenHash]);return{id:row.id,username:row.username,name:row.name,role:row.role}}
export const roleAllows=(role:StaffRole,permission:string)=>({OWNER:['*'],MANAGER:['sessions:read','sessions:write','orders:read','orders:write','bookings:read','bookings:write','members:read','finance:read','daily_close:count','inventory:read','inventory:write','payments:read','payments:write','credit:read'],DEVELOPER:['*']}[role]||[]).some(p=>p==='*'||p===permission);
export async function requireStaff(token:string|undefined|null,permission?:string){const staff=await getStaffByToken(token);if(!staff)throw new Error('STAFF_UNAUTHORIZED');if(permission&&!roleAllows(staff.role,permission))throw new Error('STAFF_FORBIDDEN');return staff}
export async function logoutStaff(token?:string|null){if(token)await pool.execute('DELETE FROM staff_sessions WHERE token_hash=?',[hashToken(token)])}
export async function listStaff(){const[rows]=await pool.query<(RowDataPacket&Staff&{active:boolean;created_at:string;updated_at:string})[]>('SELECT id,username,name,role,active,created_at,updated_at FROM staff_users ORDER BY active DESC,role,username');return rows}
export async function createStaff(input:{username:string;name:string;role:StaffRole;password:string}){const username=input.username.trim().toLowerCase();if(!/^[a-z0-9._-]{3,80}$/.test(username))throw new Error('INVALID_USERNAME');if(input.password.length<10)throw new Error('PASSWORD_TOO_SHORT');if(!['OWNER','MANAGER','DEVELOPER'].includes(input.role))throw new Error('INVALID_ROLE');const hash=await passwordHash(input.password),staffId=id();await pool.execute('INSERT INTO staff_users(id,username,name,password_hash,role,active,created_at,updated_at) VALUES(?,?,?,?,?,TRUE,NOW(3),NOW(3))',[staffId,username,input.name.trim(),hash,input.role]);return{id:staffId,username,name:input.name.trim(),role:input.role,active:true}}
export async function updateStaff(idValue:string,input:{name?:string;role?:StaffRole;active?:boolean;password?:string}){if(input.password!==undefined&&input.password.length<10)throw Error('PASSWORD_TOO_SHORT');const fields:string[]=[],values:(string|number|boolean)[]=[];if(input.name!==undefined){fields.push('name=?');values.push(input.name.trim())}if(input.role!==undefined){if(!['OWNER','MANAGER','DEVELOPER'].includes(input.role))throw Error('INVALID_ROLE');fields.push('role=?');values.push(input.role)}if(input.active!==undefined){fields.push('active=?');values.push(input.active);if(!input.active)await pool.execute('DELETE FROM staff_sessions WHERE staff_id=?',[idValue])}if(input.password!==undefined){fields.push('password_hash=?');values.push(await passwordHash(input.password));await pool.execute('DELETE FROM staff_sessions WHERE staff_id=?',[idValue])}if(!fields.length)throw Error('NO_CHANGES');fields.push('updated_at=NOW(3)');values.push(idValue);const[result]=await pool.execute('UPDATE staff_users SET '+fields.join(',')+' WHERE id=?',[...values]);if((result as{affectedRows:number}).affectedRows!==1)throw Error('STAFF_NOT_FOUND');return true}
export async function audit(staffId:string|undefined,action:string,entityType?:string,entityId?:string,details?:unknown){await pool.execute('INSERT INTO audit_log(staff_id,action,entity_type,entity_id,details,created_at) VALUES(?,?,?,?,?,NOW(3))',[staffId||null,action,entityType||null,entityId||null,details===undefined?null:JSON.stringify(details)])}
export {COOKIE,ROLE_COOKIE,IDLE_MS};
