import {createHash,randomBytes,randomUUID,timingSafeEqual} from 'node:crypto';
import type {PoolConnection,RowDataPacket} from 'mysql2/promise';
import {pool,transaction} from './mysql';
const TTL_MS=60_000;
const hash=(value:string)=>createHash('sha256').update(value,'utf8').digest('hex');
const agentSecrets=():Record<string,string>=>{try{const raw=process.env.GENZ_STATION_AGENT_SECRETS_JSON||'{}';const parsed=JSON.parse(raw);return parsed&&typeof parsed==='object'?parsed as Record<string,string>:{};}catch{return {};}};
function secretsMatch(a:string,b:string){const bufA=createHash('sha256').update(a,'utf8').digest();const bufB=createHash('sha256').update(b,'utf8').digest();return timingSafeEqual(bufA,bufB);}
export function authorizeStationAgent(stationId:string,secret:string){const configured=agentSecrets()[stationId];return Boolean(configured&&secret&&configured.length>=32&&secret.length>=32&&secretsMatch(configured,secret));}
export async function issueStationChallenge(stationId:string){return transaction(async(c:PoolConnection)=>{const[stations]=await c.query<RowDataPacket[]>('SELECT id,status FROM stations WHERE id=? LIMIT 1',[stationId]);if(!stations[0])throw new Error('Station not found');const[sessions]=await c.query<RowDataPacket[]>("SELECT id FROM sessions WHERE station_id=? AND status IN ('ACTIVE','PAUSED') ORDER BY started_at DESC LIMIT 1",[stationId]);const sessionId=sessions[0]?.id?String(sessions[0].id):null;const challenge=randomBytes(32).toString('base64url');const id=randomUUID();const expires=new Date(Date.now()+TTL_MS);await c.execute('UPDATE station_challenges SET used_at=COALESCE(used_at,NOW(3)) WHERE station_id=? AND used_at IS NULL',[stationId]);await c.execute('INSERT INTO station_challenges(id,station_id,session_id,challenge_hash,expires_at,created_at) VALUES(?,?,?,?,?,NOW(3))',[id,stationId,sessionId,hash(challenge),expires]);return{id,stationId,sessionId,challenge,expiresAt:expires.toISOString()};});}
export async function consumeStationChallenge(stationId:string,challenge:string,customerId:string){if(!/^[A-Za-z0-9_-]{40,64}$/.test(challenge))throw new Error('Invalid station challenge');return transaction(async(c:PoolConnection)=>{const[rows]=await c.query<RowDataPacket[]>('SELECT id,station_id,session_id,expires_at,used_at FROM station_challenges WHERE station_id=? AND challenge_hash=? FOR UPDATE',[stationId,hash(challenge)]);const row=rows[0];if(!row)throw new Error('Station challenge invalid or expired');if(row.used_at)throw new Error('Station challenge already used');if(new Date(row.expires_at).getTime()<=Date.now())throw new Error('Station challenge invalid or expired');const[sessions]=await c.query<RowDataPacket[]>("SELECT id FROM sessions WHERE station_id=? AND status IN ('ACTIVE','PAUSED') ORDER BY started_at DESC LIMIT 1 FOR UPDATE",[stationId]);const session=sessions[0];if(!session)throw new Error('No active session is available for this station');if(row.session_id&&String(row.session_id)!==String(session.id))throw new Error('Station challenge is no longer valid');const[customers]=await c.query<RowDataPacket[]>('SELECT id,name,member_id FROM customers WHERE id=? LIMIT 1',[customerId]);if(!customers[0])throw new Error('Customer not found');const[existing]=await c.query<RowDataPacket[]>('SELECT id FROM session_participants WHERE session_id=? AND customer_id=? AND active=TRUE LIMIT 1',[session.id,customerId]);let participantId=existing[0]?.id?String(existing[0].id):'';if(!participantId){const[station]=await c.query<RowDataPacket[]>('SELECT type,pc_tier,hourly_rate FROM stations WHERE id=? LIMIT 1',[stationId]);if(!station[0])throw new Error('Station not found');let regular=Number(station[0].hourly_rate),memberRate=regular;const[rates]=await c.query<RowDataPacket[]>('SELECT regular_price,member_price FROM gaming_rates WHERE station_type=? AND active=TRUE AND (pc_tier=? OR pc_tier IS NULL) ORDER BY (pc_tier IS NULL),id LIMIT 1',[station[0].type,station[0].pc_tier||null]);if(rates[0]){regular=Number(rates[0].regular_price);memberRate=Number(rates[0].member_price)}const[memberRows]=await c.query<RowDataPacket[]>('SELECT id,tier FROM members WHERE id=? AND active=TRUE AND expires_at>=CURDATE() LIMIT 1',[customers[0].member_id||'']);const member=memberRows[0];participantId=`PAR-${randomUUID()}`;await c.execute('INSERT INTO session_participants(id,session_id,customer_id,member_id,display_name,active,created_at,joined_at,billing_regular_rate,billing_member_rate,member_tier) VALUES(?,?,?,?,?,?,NOW(3),NOW(3),?,?,?)',[participantId,session.id,customerId,member?String(member.id):null,String(customers[0].name||'Guest').slice(0,120),true,regular,memberRate,member?String(member.tier):null]);}await c.execute('UPDATE station_challenges SET used_at=NOW(3) WHERE id=? AND used_at IS NULL',[row.id]);return{sessionId:String(session.id),participantId};});}
export async function cleanupExpiredStationChallenges(){await pool.execute('DELETE FROM station_challenges WHERE expires_at < DATE_SUB(NOW(3),INTERVAL 1 DAY) OR used_at < DATE_SUB(NOW(3),INTERVAL 1 DAY)');}
