import { createHash, randomUUID } from 'node:crypto';
import type { PoolConnection, RowDataPacket } from 'mysql2/promise';
import { pool, transaction } from './mysql';

export type StationType = 'PC' | 'PS5' | 'PS4' | 'PSVR' | 'MOZA';
export type StationStatus = 'AVAILABLE' | 'BOOKED' | 'ACTIVE' | 'MAINTENANCE' | 'BLOCKED';
export type SessionStatus = 'ACTIVE' | 'PAUSED' | 'ENDED';
export type OrderStatus = 'NEW' | 'ACCEPTED' | 'PREPARING' | 'READY' | 'DELIVERED' | 'CANCELLED';
export type PaymentMode = 'PAY_NOW' | 'COUNTER';
export type PaymentStatus = 'UNPAID' | 'PENDING' | 'PAID' | 'FAILED' | 'REFUNDED';

export type Station = { id:string; name:string; type:StationType; status:StationStatus; hourlyRate:number; slotMinutes:number; };
export type Session = { id:string; stationId:string; customerName:string; memberId?:string; status:SessionStatus; startedAt:string; scheduledEndAt?:string; pausedAt?:string; endedAt?:string; token?:string; balance:number; };
export type OrderItem = { itemId:string; name:string; qty:number; unitPrice:number; participantId?:string; };
export type Order = { id:string; sessionId:string; stationId:string; items:OrderItem[]; status:OrderStatus; paymentMode:PaymentMode; paymentStatus:PaymentStatus; createdAt:string; total:number; };

type StationRow = RowDataPacket & {id:string;name:string;type:StationType;status:StationStatus;hourly_rate:number;slot_minutes:number};
type SessionRow = RowDataPacket & {id:string;station_id:string;customer_name:string;member_id:string|null;status:SessionStatus;started_at:string;scheduled_end_at:string|null;paused_at:string|null;ended_at:string|null;token_hash:string;gaming_balance:number;food_balance:number};
type OrderRow = RowDataPacket & {id:string;session_id:string;station_id:string;status:OrderStatus;payment_mode:PaymentMode;payment_status:PaymentStatus;created_at:string;total:number;razorpay_order_id?:string|null};
type ItemRow = RowDataPacket & {order_id:string;item_id:string;name:string;qty:number;unit_price:number;participant_id:string|null};

const now=()=>new Date();
const makeId=(prefix:string)=>`${prefix}-${randomUUID()}`;
const hashToken=(token:string)=>createHash('sha256').update(token).digest('hex');
const mapStation=(r:StationRow):Station=>({id:r.id,name:r.name,type:r.type,status:r.status,hourlyRate:Number(r.hourly_rate),slotMinutes:Number(r.slot_minutes)});
const mapSession=(r:SessionRow,token?:string):Session=>({id:r.id,stationId:r.station_id,customerName:r.customer_name,memberId:r.member_id||undefined,status:r.status,startedAt:new Date(r.started_at).toISOString(),scheduledEndAt:r.scheduled_end_at?new Date(r.scheduled_end_at).toISOString():undefined,pausedAt:r.paused_at?new Date(r.paused_at).toISOString():undefined,endedAt:r.ended_at?new Date(r.ended_at).toISOString():undefined,token,balance:Number(r.gaming_balance)+Number(r.food_balance)});
const mapOrder=(row:OrderRow,items:ItemRow[]):Order=>({id:row.id,sessionId:row.session_id,stationId:row.station_id,items:items.filter(i=>i.order_id===row.id).map(i=>({itemId:i.item_id,name:i.name,qty:Number(i.qty),unitPrice:Number(i.unit_price),participantId:i.participant_id||undefined})),status:row.status,paymentMode:row.payment_mode,paymentStatus:row.payment_status,createdAt:new Date(row.created_at).toISOString(),total:Number(row.total)});

export async function listStations():Promise<Station[]>{const [rows]=await pool.query<StationRow[]>('SELECT * FROM stations ORDER BY type,name');return rows.map(mapStation);}
export async function listSessions():Promise<Session[]>{const [rows]=await pool.query<SessionRow[]>('SELECT * FROM sessions ORDER BY started_at DESC');return rows.map(r=>mapSession(r));}
export async function listOrders():Promise<Order[]>{const [rows]=await pool.query<OrderRow[]>('SELECT * FROM orders ORDER BY created_at DESC');if(!rows.length)return[];const ids=rows.map(r=>r.id);const p=ids.map(()=>'?').join(',');const [items]=await pool.query<ItemRow[]>(`SELECT order_id,item_id,name,qty,unit_price,participant_id FROM order_items WHERE order_id IN (${p}) ORDER BY id`,ids);return rows.map(r=>mapOrder(r,items));}

export async function startSession(input:{stationId:string;customerName:string;memberId?:string}){const customerName=input.customerName.trim().slice(0,120)||'Walk-in';const memberId=input.memberId?.trim().slice(0,64)||undefined;return transaction(async(c:PoolConnection)=>{const [rows]=await c.query<StationRow[]>('SELECT * FROM stations WHERE id=? FOR UPDATE',[input.stationId]);const station=rows[0];if(!station)throw new Error('Station not found');if(station.status!=='AVAILABLE')throw new Error('Station is not available');const [active]=await c.query<RowDataPacket[]>('SELECT id FROM sessions WHERE station_id=? AND status IN (\'ACTIVE\',\'PAUSED\') LIMIT 1',[station.id]);if(active.length)throw new Error('Station already has an active session');const token=randomUUID();const started=new Date();const scheduledEnd=new Date(started.getTime()+Number(station.slot_minutes)*60_000);const session:Session={id:makeId('SES'),stationId:station.id,customerName,memberId,status:'ACTIVE',startedAt:started.toISOString(),scheduledEndAt:scheduledEnd.toISOString(),token,balance:0};await c.execute('INSERT INTO sessions(id,station_id,customer_name,member_id,status,started_at,scheduled_end_at,token_hash,gaming_balance,food_balance) VALUES (?,?,?,?,?,?,?,?,?,?)',[session.id,session.stationId,session.customerName,session.memberId||null,session.status,session.startedAt,session.scheduledEndAt||null,hashToken(token),0,0]);await c.execute('UPDATE stations SET status=\'ACTIVE\' WHERE id=?',[station.id]);return session;});}

export async function extendSession(input:{sessionId:string;customerId:string;extensionMinutes:number}){const minutes=Number(input.extensionMinutes);if(!Number.isInteger(minutes)||![15,30,60].includes(minutes))throw new Error('Invalid extension duration');return transaction(async(c:PoolConnection)=>{const [rows]=await c.query<SessionRow[]>('SELECT * FROM sessions WHERE id=? FOR UPDATE',[input.sessionId]);const session=rows[0];if(!session||!['ACTIVE','PAUSED'].includes(session.status))throw new Error('Active session required');const [participant]=await c.query<RowDataPacket[]>('SELECT id FROM session_participants WHERE session_id=? AND customer_id=? AND active=TRUE LIMIT 1',[input.sessionId,input.customerId]);if(!participant.length)throw new Error('You are not authorized for this session');const currentEnd=session.scheduled_end_at?new Date(session.scheduled_end_at):new Date(Date.now());const proposedEnd=new Date(currentEnd.getTime()+minutes*60_000);const [next]=await c.query<RowDataPacket[]>('SELECT id,starts_at FROM bookings WHERE station_id=? AND status NOT IN (\'CANCELLED\',\'NO_SHOW\') AND starts_at>=? AND starts_at< ? ORDER BY starts_at ASC LIMIT 1',[session.station_id,currentEnd,proposedEnd]);if(next.length)throw new Error(`NEXT_SESSION_BOOKED:${new Date(next[0].starts_at).toISOString()}`);const [any]=await c.query<RowDataPacket[]>('SELECT id,starts_at FROM bookings WHERE station_id=? AND status NOT IN (\'CANCELLED\',\'NO_SHOW\') AND starts_at>=? ORDER BY starts_at ASC LIMIT 1',[session.station_id,currentEnd]);if(any.length)throw new Error(`NEXT_SESSION_BOOKED:${new Date(any[0].starts_at).toISOString()}`);await c.execute('UPDATE sessions SET scheduled_end_at=? WHERE id=?',[proposedEnd,input.sessionId]);const [fresh]=await c.query<SessionRow[]>('SELECT * FROM sessions WHERE id=?',[input.sessionId]);return mapSession(fresh[0]);});}

export async function endSession(sessionId:string){return transaction(async(c:PoolConnection)=>{const [rows]=await c.query<SessionRow[]>('SELECT * FROM sessions WHERE id=? FOR UPDATE',[sessionId]);const row=rows[0];if(!row)throw new Error('Session not found');if(row.status!=='ENDED'){await c.execute('UPDATE sessions SET status=\'ENDED\',ended_at=? WHERE id=?',[now(),sessionId]);await c.execute('UPDATE stations SET status=\'AVAILABLE\' WHERE id=? AND status=\'ACTIVE\'',[row.station_id]);}const [fresh]=await c.query<SessionRow[]>('SELECT * FROM sessions WHERE id=?',[sessionId]);return mapSession(fresh[0]);});}
export async function authorizeSession(sessionId:string,token:string){const [rows]=await pool.query<SessionRow[]>('SELECT * FROM sessions WHERE id=? AND token_hash=? AND status IN (\'ACTIVE\',\'PAUSED\') LIMIT 1',[sessionId,hashToken(token)]);return rows[0]?mapSession(rows[0]):null;}

export async function ensureSessionParticipant(sessionId:string,customerId:string,c?:PoolConnection){const run=async(db:PoolConnection)=>{const [customers]=await db.query<RowDataPacket[]>('SELECT id,name,member_id FROM customers WHERE id=? LIMIT 1',[customerId]);const customer=customers[0];if(!customer)throw new Error('Customer not found');const [sessions]=await db.query<RowDataPacket[]>('SELECT id,status FROM sessions WHERE id=? LIMIT 1',[sessionId]);if(!sessions[0]||!['ACTIVE','PAUSED'].includes(String(sessions[0].status)))throw new Error('Active session required');const [existing]=await db.query<RowDataPacket[]>('SELECT id FROM session_participants WHERE session_id=? AND customer_id=? AND active=TRUE LIMIT 1',[sessionId,customerId]);if(existing[0])return String(existing[0].id);const id=makeId('PAR');await db.execute('INSERT INTO session_participants(id,session_id,customer_id,member_id,display_name,active,created_at) VALUES(?,?,?,?,?,?,?)',[id,sessionId,customer.id,customer.member_id||null,String(customer.name||'Guest').slice(0,120),true,now()]);return id;};return c?run(c):transaction(run);}

export async function createOrder(input:{sessionId:string;items:OrderItem[];paymentMode:PaymentMode;customerId?:string}){if(!['PAY_NOW','COUNTER'].includes(input.paymentMode))throw new Error('Invalid payment mode');if(!Array.isArray(input.items)||input.items.length<1||input.items.length>50)throw new Error('Invalid order items');return transaction(async(c:PoolConnection)=>{const [sessions]=await c.query<SessionRow[]>('SELECT * FROM sessions WHERE id=? AND status IN (\'ACTIVE\',\'PAUSED\') FOR UPDATE',[input.sessionId]);const session=sessions[0];if(!session)throw new Error('Active session required');const participantId=input.customerId?await ensureSessionParticipant(session.id,input.customerId,c):undefined;const ids=[...new Set(input.items.map(i=>String(i.itemId||'').trim()))];if(ids.some(x=>!x)||ids.length!==input.items.length)throw new Error('Invalid menu item');const p=ids.map(()=>'?').join(',');const [menu]=await c.query<(RowDataPacket&{id:string;name:string;member_price:number;non_member_price:number;active:number})[]>(`SELECT id,name,member_price,non_member_price,active FROM menu_items WHERE id IN (${p}) FOR UPDATE`,ids);if(menu.length!==ids.length||menu.some(m=>!m.active))throw new Error('Menu item unavailable');const memberId=input.customerId?(await c.query<RowDataPacket[]>('SELECT member_id FROM customers WHERE id=? LIMIT 1',[input.customerId]))[0][0]?.member_id||null:null;const byId=new Map(menu.map(m=>[m.id,m]));const items=input.items.map(i=>{const m=byId.get(String(i.itemId));const qty=Number(i.qty);if(!m||!Number.isInteger(qty)||qty<1||qty>99)throw new Error('Invalid order item');const price=Number(memberId?m.member_price:m.non_member_price);return{itemId:m.id,name:m.name,qty,unitPrice:price,participantId};});const total=items.reduce((s,i)=>s+i.qty*i.unitPrice,0);const paymentStatus:PaymentStatus=input.paymentMode==='PAY_NOW'?'PENDING':'UNPAID';const order:Order={id:makeId('ORD'),sessionId:session.id,stationId:session.station_id,items,status:'NEW',paymentMode:input.paymentMode,paymentStatus,createdAt:new Date().toISOString(),total};await c.execute('INSERT INTO orders(id,session_id,station_id,status,payment_mode,payment_status,created_at,total) VALUES (?,?,?,?,?,?,?,?)',[order.id,order.sessionId,order.stationId,order.status,order.paymentMode,order.paymentStatus,order.createdAt,total]);for(const item of items)await c.execute('INSERT INTO order_items(order_id,item_id,name,qty,unit_price,participant_id) VALUES (?,?,?,?,?,?)',[order.id,item.itemId,item.name,item.qty,item.unitPrice,item.participantId||null]);return order;});}

export async function markOrderCounterPaid(orderId:string){return transaction(async(c:PoolConnection)=>{const [rows]=await c.query<OrderRow[]>('SELECT * FROM orders WHERE id=? FOR UPDATE',[orderId]);const order=rows[0];if(!order)throw new Error('Order not found');if(order.paymentMode!=='COUNTER')throw new Error('Only counter orders can be marked paid');if(order.paymentStatus==='PAID')return mapOrder(order,[]);await c.execute('UPDATE orders SET payment_status=\'PAID\',paid_at=? WHERE id=?',[now(),orderId]);const [items]=await c.query<ItemRow[]>('SELECT order_id,item_id,name,qty,unit_price,participant_id FROM order_items WHERE order_id=? ORDER BY id',[orderId]);await c.execute('INSERT INTO payment_transactions(id,order_id,provider,status,amount,currency,created_at,updated_at,captured_at) VALUES(?,?,?,?,?,?,?,?,?)',[makeId('PAY'),orderId,'COUNTER','CAPTURED',order.total,'INR',now(),now(),now()]);const [fresh]=await c.query<OrderRow[]>('SELECT * FROM orders WHERE id=?',[orderId]);return mapOrder(fresh[0],items);});}
export async function setOnlinePaymentPending(orderId:string,razorpayOrderId:string){return transaction(async(c:PoolConnection)=>{const [rows]=await c.query<OrderRow[]>('SELECT * FROM orders WHERE id=? FOR UPDATE',[orderId]);const order=rows[0];if(!order)throw new Error('Order not found');if(order.paymentMode!=='PAY_NOW')throw new Error('Order is not online-payable');if(order.paymentStatus==='PAID')return order;await c.execute('UPDATE orders SET payment_status=\'PENDING\',razorpay_order_id=? WHERE id=?',[razorpayOrderId,orderId]);await c.execute('INSERT INTO payment_transactions(id,order_id,provider,provider_order_id,status,amount,currency,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)',[makeId('PAY'),orderId,'RAZORPAY',razorpayOrderId,'PENDING',order.total,'INR',now(),now()]);const [fresh]=await c.query<OrderRow[]>('SELECT * FROM orders WHERE id=?',[orderId]);return fresh[0];});}
export async function confirmOnlinePayment(orderId:string,razorpayOrderId:string,razorpayPaymentId:string,signature:string){return transaction(async(c:PoolConnection)=>{const [rows]=await c.query<OrderRow[]>('SELECT * FROM orders WHERE id=? FOR UPDATE',[orderId]);const order=rows[0];if(!order)throw new Error('Order not found');if(order.razorpay_order_id!==razorpayOrderId)throw new Error('Payment order mismatch');if(order.paymentStatus==='PAID')return order;await c.execute('UPDATE orders SET payment_status=\'PAID\',paid_at=?,razorpay_payment_id=?,razorpay_signature=? WHERE id=?',[now(),razorpayPaymentId,signature,orderId]);await c.execute('UPDATE payment_transactions SET status=\'CAPTURED\',provider_payment_id=?,updated_at=?,captured_at=? WHERE provider_order_id=? AND order_id=?',[razorpayPaymentId,now(),now(),razorpayOrderId,orderId]);const [fresh]=await c.query<OrderRow[]>('SELECT * FROM orders WHERE id=?',[orderId]);return fresh[0];});}
export async function advanceOrder(orderId:string){return transaction(async(c:PoolConnection)=>{const [rows]=await c.query<OrderRow[]>('SELECT * FROM orders WHERE id=? FOR UPDATE',[orderId]);const order=rows[0];if(!order)throw new Error('Order not found');const flow:OrderStatus[]=['NEW','ACCEPTED','PREPARING','READY','DELIVERED'];const i=flow.indexOf(order.status);if(i<0||i>=flow.length-1)throw new Error('Invalid order transition');const next=flow[i+1];const [result]=await c.execute('UPDATE orders SET status=? WHERE id=? AND status=?',[next,orderId,order.status]);if((result as {affectedRows:number}).affectedRows!==1)throw new Error('Order changed; retry');const [fresh]=await c.query<OrderRow[]>('SELECT * FROM orders WHERE id=?',[orderId]);const [items]=await c.query<ItemRow[]>('SELECT order_id,item_id,name,qty,unit_price,participant_id FROM order_items WHERE order_id=? ORDER BY id',[orderId]);return mapOrder(fresh[0],items);});}
