import {NextResponse} from 'next/server';
import {randomUUID} from 'node:crypto';
import {cookies} from 'next/headers';
import {COOKIE,requireStaff,audit} from '../../../../lib/staff-auth';
import {transaction} from '../../../../lib/mysql';
import {getSessionSettlement} from '../../../../lib/session-settlement';
const id=(p:string)=>`${p}-${randomUUID()}`;
const str=(v:unknown)=>typeof v==='string'?v.trim():'';
export async function POST(req:Request){try{const staff=await requireStaff((await cookies()).get(COOKIE)?.value,'payments:write');const b=await req.json();const sessionId=str(b?.sessionId),reason=str(b?.reason),kind=str(b?.kind)||'MANUAL',amount=Number(b?.amount);if(!sessionId||sessionId.length>64||!reason||!Number.isSafeInteger(amount)||amount===0||Math.abs(amount)>10000000||!['DISCOUNT','SURCHARGE','ROUNDING','MANUAL'].includes(kind))return NextResponse.json({ok:false,error:'Invalid billing adjustment'},{status:400});const result=await transaction(async(c)=>{const[s]=await c.query<{id:string;status:string}[]>('SELECT id,status FROM sessions WHERE id=? FOR UPDATE',[sessionId]);if(!s[0])throw Error('SESSION_NOT_FOUND');if(s[0].status!=='ENDED')throw Error('SESSION_MUST_BE_ENDED');const adjustmentId=id('ADJ');await c.execute('INSERT INTO billing_adjustments(id,session_id,kind,amount,reason,created_by,created_at) VALUES(?,?,?,?,?,?,NOW(3))',[adjustmentId,sessionId,kind,amount,reason,staff.id]);return{adjustmentId,sessionId,amount,kind,reason};});await audit(staff.id,'SESSION_BILLING_ADJUSTED','session',sessionId,result);return NextResponse.json({ok:true,result,settlement:await getSessionSettlement(sessionId)},{status:201});}catch(e){const m=e instanceof Error?e.message:'';if(m==='STAFF_UNAUTHORIZED'||m==='STAFF_FORBIDDEN')return NextResponse.json({ok:false,error:m==='STAFF_FORBIDDEN'?'Permission denied':'Staff authorization required'},{status:m==='STAFF_FORBIDDEN'?403:401});return NextResponse.json({ok:false,error:m||'Unable to adjust billing'},{status:m==='SESSION_NOT_FOUND'?404:400});}}
