import {NextResponse} from 'next/server';
import {cookies} from 'next/headers';
import type {RowDataPacket} from 'mysql2/promise';
import {listSessions,startSession} from '../../../lib/store';
import {COOKIE,requireStaff,audit} from '../../../lib/staff-auth';
import {pool} from '../../../lib/mysql';
import {calculateSessionBilling,reconcileBookingDeposit} from '../../../lib/gaming-billing';
import {endSessionForSettlement} from '../../../lib/session-lifecycle';
import {attachCustomerToSession} from '../../../lib/session-customer';
import {getSessionSettlement} from '../../../lib/session-settlement';
import {publish} from '../../../lib/realtime';
const authError=(e:unknown)=>{const m=e instanceof Error?e.message:'';return NextResponse.json({ok:false,error:m==='STAFF_FORBIDDEN'?'Permission denied':'Staff authorization required'},{status:m==='STAFF_FORBIDDEN'?403:401});};
export async function GET(){try{await requireStaff((await cookies()).get(COOKIE)?.value,'sessions:read');const sessions=await listSessions();const live=await Promise.all(sessions.map(async s=>{const billing=await calculateSessionBilling(s.id);const[foodRows]=await pool.query<RowDataPacket[]>('SELECT food_balance,customer_id FROM sessions WHERE id=? LIMIT 1',[s.id]);return {...s,customerId:foodRows[0]?.customer_id?String(foodRows[0].customer_id):undefined,balance:billing.gamingTotal+Number(foodRows[0]?.food_balance||0),settlement:s.status==='ENDED'?await getSessionSettlement(s.id):null};}));return NextResponse.json({ok:true,sessions:live},{headers:{'Cache-Control':'no-store'}});}catch(e){return authError(e);}}
export async function POST(request:Request){try{const staff=await requireStaff((await cookies()).get(COOKIE)?.value,'sessions:write');const body=await request.json();const stationId=typeof body?.stationId==='string'?body.stationId:'';const customerName=typeof body?.customerName==='string'?body.customerName:'';const memberId=typeof body?.memberId==='string'?body.memberId.trim():undefined;const customerId=typeof body?.customerId==='string'?body.customerId.trim():undefined;if(stationId.length<1||stationId.length>64||customerName.length>120||memberId&&memberId.length>64||customerId&&customerId.length>64)return NextResponse.json({ok:false,error:'Invalid request'},{status:400});if(memberId){const[members]=await pool.query('SELECT id FROM members WHERE id=? AND active=TRUE AND expires_at>=CURDATE() LIMIT 1',[memberId]);if(!(members as unknown[]).length)return NextResponse.json({ok:false,error:'Membership ID is invalid or expired'},{status:400});}const session=await startSession({stationId,customerName,memberId});if(customerId){try{await attachCustomerToSession(session.id,customerId);}catch(e){await import('../../../lib/store').then(m=>m.endSession(session.id));throw e;}}await audit(staff.id,'SESSION_STARTED','session',session.id,{stationId,memberId:memberId||null,customerId:customerId||null});publish('SESSION_CREATED',{sessionId:session.id,stationId});return NextResponse.json({ok:true,session},{status:201});}catch(e){if(e instanceof Error&&(e.message==='STAFF_UNAUTHORIZED'||e.message==='STAFF_FORBIDDEN'))return authError(e);return NextResponse.json({ok:false,error:e instanceof Error?e.message:'Unable to start session'},{status:400});}}
export async function PATCH(request:Request){try{const staff=await requireStaff((await cookies()).get(COOKIE)?.value,'sessions:write');const body=await request.json();const sessionId=typeof body?.sessionId==='string'?body.sessionId.trim():'';if(!sessionId||sessionId.length>64)return NextResponse.json({ok:false,error:'Invalid request'},{status:400});const ended=await endSessionForSettlement(sessionId);const reconciliation=await reconcileBookingDeposit(sessionId);const settlement=await getSessionSettlement(sessionId);await audit(staff.id,'SESSION_ENDED','session',sessionId,{outstanding:settlement.outstanding,settlementStatus:settlement.settlementStatus,bookingDepositApplied:reconciliation.applied,bookingDepositRefundable:reconciliation.refundable});publish('SESSION_ENDED',{sessionId,stationId:ended.stationId});return NextResponse.json({ok:true,sessionId,stationId:ended.stationId,settlement,reconciliation});}catch(e){if(e instanceof Error&&(e.message==='STAFF_UNAUTHORIZED'||e.message==='STAFF_FORBIDDEN'))return authError(e);return NextResponse.json({ok:false,error:e instanceof Error?e.message:'Unable to end session'},{status:400})}}
