import {NextResponse} from 'next/server';
import {cookies} from 'next/headers';
import {listSessions,startSession,endSession} from '../../../lib/store';
import {COOKIE,requireStaff,audit} from '../../../lib/staff-auth';
import {pool} from '../../../lib/mysql';
import {calculateSessionBilling,finalizeSessionBilling} from '../../../lib/gaming-billing';
const authError=(e:unknown)=>{const m=e instanceof Error?e.message:'';return NextResponse.json({ok:false,error:m==='STAFF_FORBIDDEN'?'Permission denied':'Staff authorization required'},{status:m==='STAFF_FORBIDDEN'?403:401});};
export async function GET(){try{await requireStaff((await cookies()).get(COOKIE)?.value,'sessions:read');const sessions=await listSessions();const live=await Promise.all(sessions.map(async s=>{if(s.status==='ENDED')return s;const[b]=await Promise.all([calculateSessionBilling(s.id),pool.query('SELECT food_balance FROM sessions WHERE id=? LIMIT 1',[s.id])]);const food=Number((b[1][0] as {food_balance?:number})?.food_balance||0);return {...s,balance:b[0].gamingTotal+food};}));return NextResponse.json({ok:true,sessions:live},{headers:{'Cache-Control':'no-store'}});}catch(e){return authError(e);}}
export async function POST(request:Request){try{const staff=await requireStaff((await cookies()).get(COOKIE)?.value,'sessions:write');const body=await request.json();const stationId=typeof body?.stationId==='string'?body.stationId:'';const customerName=typeof body?.customerName==='string'?body.customerName:'';const memberId=typeof body?.memberId==='string'?body.memberId.trim():undefined;if(stationId.length<1||stationId.length>64||customerName.length>120||memberId&&memberId.length>64)return NextResponse.json({ok:false,error:'Invalid request'},{status:400});if(memberId){const[members]=await pool.query('SELECT id FROM members WHERE id=? AND active=TRUE AND expires_at>=CURDATE() LIMIT 1',[memberId]);if(!(members as unknown[]).length)return NextResponse.json({ok:false,error:'Membership ID is invalid or expired'},{status:400});}const session=await startSession({stationId,customerName,memberId});await audit(staff.id,'SESSION_STARTED','session',session.id,{stationId,memberId:memberId||null});return NextResponse.json({ok:true,session},{status:201});}catch(e){if(e instanceof Error&&(e.message==='STAFF_UNAUTHORIZED'||e.message==='STAFF_FORBIDDEN'))return authError(e);return NextResponse.json({ok:false,error:e instanceof Error?e.message:'Unable to start session'},{status:400});}}
export async function PATCH(request:Request){try{const staff=await requireStaff((await cookies()).get(COOKIE)?.value,'sessions:write');const body=await request.json();const sessionId=typeof body?.sessionId==='string'?body.sessionId:'';if(!sessionId||sessionId.length>64)return NextResponse.json({ok:false,error:'Invalid request'},{status:400});await finalizeSessionBilling(sessionId);const session=await endSession(sessionId);await audit(staff.id,'SESSION_ENDED','session',sessionId,{gamingBalance:session.balance});return NextResponse.json({ok:true,session});}catch(e){if(e instanceof Error&&(e.message==='STAFF_UNAUTHORIZED'||e.message==='STAFF_FORBIDDEN'))return authError(e);return NextResponse.json({ok:false,error:e instanceof Error?e.message:'Unable to end session'},{status:400})}}
