'use client';
import {useEffect,useState} from 'react';

type Feature={feature_key:string;enabled:boolean;description:string;updated_by:string|null;updated_at:string};
type Log={id:number;username:string|null;name:string|null;role:string|null;action:string;entity_type:string|null;entity_id:string|null;details:string|null;created_at:string};
type Check={key:string;name:string;status:'PASS'|'WARN'|'FAIL';message:string;details?:unknown};
type TestResponse={environment:string;destructiveActionsAllowed:boolean;checks:Check[];passed:number;warnings:number;failed:number};
const title=(key:string)=>key.split('_').map(x=>x[0].toUpperCase()+x.slice(1)).join(' ');
const statusClass=(s:Check['status'])=>s==='PASS'?'success':s==='FAIL'?'danger':'warning';

export default function Developer(){
 const[features,setFeatures]=useState<Feature[]>([]),[logs,setLogs]=useState<Log[]>([]),[tests,setTests]=useState<TestResponse|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState('');
 async function load(){const r=await fetch('/api/developer/features',{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error||'Developer access required');setFeatures(d.features);setLogs(d.logs)}
 async function loadTests(){const r=await fetch('/api/developer/testing',{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error||'Unable to load testing center');const checks=d.checks||[];setTests({environment:d.environment,destructiveActionsAllowed:Boolean(d.destructiveActionsAllowed),checks,passed:checks.filter((c:Check)=>c.status==='PASS').length,warnings:checks.filter((c:Check)=>c.status==='WARN').length,failed:checks.filter((c:Check)=>c.status==='FAIL').length})}
 useEffect(()=>{Promise.all([load(),loadTests()]).catch(e=>setError(e instanceof Error?e.message:'Unable to load developer console'))},[]);
 async function toggle(f:Feature){setBusy(f.feature_key);setError('');try{const r=await fetch('/api/developer/features',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({feature:f.feature_key,enabled:!f.enabled})});const d=await r.json();if(!r.ok)throw Error(d.error||'Unable to change feature');await load()}catch(e){setError(e instanceof Error?e.message:'Update failed')}finally{setBusy('')}}
 async function runTests(){setBusy('tests');setError('');try{const r=await fetch('/api/developer/testing',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'run-safe-checks'})});const d=await r.json();if(!r.ok)throw Error(d.error||'Test run failed');const checks=d.checks||[];setTests({environment:d.environment||tests?.environment||'production',destructiveActionsAllowed:Boolean(d.destructiveActionsAllowed),checks,passed:Number(d.passed||0),warnings:Number(d.warnings||0),failed:Number(d.failed||0)});await load()}catch(e){setError(e instanceof Error?e.message:'Test run failed')}finally{setBusy('')}}
 return <main><div className="top"><div><div className="eyebrow">DEVELOPER CONTROL</div><div className="title">Developer Console</div><div className="muted">Developer-only diagnostics, feature controls and an operational audit trail. Destructive test actions will remain staging-only.</div></div></div>
 {error&&<div className="card danger" style={{marginBottom:16}}>{error}</div>}
 <section className="card"><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:16,flexWrap:'wrap'}}><div><div className="sectionTitle">Testing center</div><p className="muted">Run safe, non-destructive checks against the currently connected environment. Results are also recorded in the audit log.</p></div><button className="btn" disabled={busy==='tests'} onClick={runTests}>{busy==='tests'?'Running…':'Run diagnostics'}</button></div>
 {tests&&<><div style={{display:'grid',gridTemplateColumns:'repeat(4,minmax(0,1fr))',gap:10,marginTop:16}}><div className="card"><b>Environment</b><div style={{marginTop:6}}>{tests.environment}</div></div><div className="card"><b>Passed</b><div style={{marginTop:6}}>{tests.passed}</div></div><div className="card"><b>Warnings</b><div style={{marginTop:6}}>{tests.warnings}</div></div><div className="card"><b>Failed</b><div style={{marginTop:6}}>{tests.failed}</div></div></div>
 <div style={{display:'grid',gap:8,marginTop:16}}>{tests.checks.map(c=><div key={c.key} className="card" style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:16,padding:12}}><div><b>{c.name}</b><div className="muted" style={{marginTop:3}}>{c.message}</div></div><span className={'badge '+statusClass(c.status)}>{c.status}</span></div>)}</div>
 <div className="muted" style={{marginTop:12,fontSize:12}}>Destructive actions available in this environment: {tests.destructiveActionsAllowed?'YES — staging only':'NO — protected'}</div></>}
 </section>
 <section className="card" style={{marginTop:16}}><div className="sectionTitle">Feature switches</div><p className="muted">Disable a feature temporarily for maintenance or incident containment. Existing database records are not deleted when a feature is disabled.</p><div style={{display:'grid',gap:10,marginTop:16}}>{features.map(f=><div key={f.feature_key} className="card" style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:20,padding:14}}><div><b>{title(f.feature_key)}</b><div className="muted" style={{marginTop:4}}>{f.description}</div><div className="muted" style={{marginTop:4,fontSize:12}}>Last changed: {f.updated_at}{f.updated_by?` · ${f.updated_by}`:''}</div></div><button className={'btn '+(f.enabled?'':'danger')} disabled={busy===f.feature_key} onClick={()=>toggle(f)}>{busy===f.feature_key?'Saving…':f.enabled?'ENABLED':'DISABLED'}</button></div>)}</div></section>
 <section className="card" style={{marginTop:16}}><div className="sectionTitle">Audit log</div><p className="muted">Latest 500 audit events, newest first. Actor, action, entity and structured details are retained for troubleshooting and accountability.</p><div className="tableWrap" style={{marginTop:12}}><table><thead><tr><th>Time</th><th>Actor</th><th>Role</th><th>Action</th><th>Entity</th><th>Details</th></tr></thead><tbody>{logs.map(l=><tr key={l.id}><td>{l.created_at}</td><td>{l.name||l.username||'System'}</td><td>{l.role||'SYSTEM'}</td><td><b>{l.action}</b></td><td>{l.entity_type||'—'}{l.entity_id?` / ${l.entity_id}`:''}</td><td><code style={{whiteSpace:'pre-wrap'}}>{l.details||'—'}</code></td></tr>)}</tbody></table></div></section></main>}
