'use client';
import {useEffect,useState} from 'react';

type Feature={feature_key:string;enabled:boolean;description:string;updated_by:string|null;updated_at:string};
type Log={id:number;username:string|null;name:string|null;role:string|null;action:string;entity_type:string|null;entity_id:string|null;details:string|null;created_at:string};
const title=(key:string)=>key.split('_').map(x=>x[0].toUpperCase()+x.slice(1)).join(' ');
export default function Developer(){const[features,setFeatures]=useState<Feature[]>([]);const[logs,setLogs]=useState<Log[]>([]);const[error,setError]=useState('');const[busy,setBusy]=useState('');
 async function load(){const r=await fetch('/api/developer/features',{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error||'Developer access required');setFeatures(d.features);setLogs(d.logs)}
 useEffect(()=>{load().catch(e=>setError(e.message))},[]);
 async function toggle(f:Feature){setBusy(f.feature_key);setError('');try{const r=await fetch('/api/developer/features',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({feature:f.feature_key,enabled:!f.enabled})});const d=await r.json();if(!r.ok)throw Error(d.error||'Unable to change feature');await load()}catch(e){setError(e instanceof Error?e.message:'Update failed')}finally{setBusy('')}}
 return <main><div className="top"><div><div className="eyebrow">OWNER / DEVELOPER CONTROL</div><div className="title">Developer Console</div><div className="muted">Feature switches and a read-only operational audit trail. Changes are attributed to the signed-in owner/developer account.</div></div></div>
 {error&&<div className="card danger" style={{marginBottom:16}}>{error}</div>}
 <section className="card"><div className="sectionTitle">Feature switches</div><p className="muted">Disable a feature temporarily for maintenance or incident containment. Existing database records are not deleted when a feature is disabled. Keep critical production features enabled unless you are deliberately performing maintenance.</p><div style={{display:'grid',gap:10,marginTop:16}}>{features.map(f=><div key={f.feature_key} className="card" style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:20,padding:14}}><div><b>{title(f.feature_key)}</b><div className="muted" style={{marginTop:4}}>{f.description}</div><div className="muted" style={{marginTop:4,fontSize:12}}>Last changed: {f.updated_at}{f.updated_by?` · ${f.updated_by}`:''}</div></div><button className={'btn '+(f.enabled?'':'danger')} disabled={busy===f.feature_key} onClick={()=>toggle(f)}>{busy===f.feature_key?'Saving…':f.enabled?'ENABLED':'DISABLED'}</button></div>)}</div></section>
 <section className="card" style={{marginTop:16}}><div className="sectionTitle">Audit log</div><p className="muted">Latest 500 audit events, newest first. Actor, action, entity and structured details are retained for troubleshooting and accountability.</p><div className="tableWrap" style={{marginTop:12}}><table><thead><tr><th>Time</th><th>Actor</th><th>Role</th><th>Action</th><th>Entity</th><th>Details</th></tr></thead><tbody>{logs.map(l=><tr key={l.id}><td>{l.created_at}</td><td>{l.name||l.username||'System'}</td><td>{l.role||'SYSTEM'}</td><td><b>{l.action}</b></td><td>{l.entity_type||'—'}{l.entity_id?` / ${l.entity_id}`:''}</td><td><code style={{whiteSpace:'pre-wrap'}}>{l.details||'—'}</code></td></tr>)}</tbody></table></div></section></main>}
