'use client';

import { useEffect, useMemo, useState } from 'react';

type Pricing={isMember:boolean;tier?:string;gaming:Array<{id:string;label:string;stationType:string;pcTier?:string;specs?:string;regularPrice:number;memberPrice:number;unitLabel:string}>;food:Array<{id:string;name:string;category:string;regularPrice:number;memberPrice:number}>};
const money=(n:number)=>`₹${Math.round(n).toLocaleString('en-IN')}`;
const mask=(m:string)=>m.length>4?`${m.slice(0,3)}••••${m.slice(-3)}`:m;

export default function Customer(){
 const [mobile,setMobile]=useState(''); const [otp,setOtp]=useState(''); const [challengeId,setChallengeId]=useState(''); const [devOtp,setDevOtp]=useState('');
 const [pricing,setPricing]=useState<Pricing|null>(null); const [authenticated,setAuthenticated]=useState(false); const [tab,setTab]=useState<'gaming'|'food'>('gaming'); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
 const loadPricing=async()=>{const r=await fetch('/api/customer/pricing',{cache:'no-store'});const j=await r.json();if(j.ok){setPricing(j.pricing);setAuthenticated(!!j.authenticated);}};
 useEffect(()=>{loadPricing().catch(()=>{});},[]);
 const requestOtp=async()=>{setError('');setBusy(true);try{const r=await fetch('/api/customer/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'request',mobile})});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||'Unable to send OTP');setChallengeId(j.challengeId);setDevOtp(j.devOtp||'');}catch(e){setError(e instanceof Error?e.message:'Unable to send OTP');}finally{setBusy(false);}};
 const verify=async()=>{setError('');setBusy(true);try{const r=await fetch('/api/customer/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'verify',mobile,otp,challengeId})});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||'Invalid OTP');await loadPricing();}catch(e){setError(e instanceof Error?e.message:'Unable to verify OTP');}finally{setBusy(false);}};
 const groups=useMemo(()=>pricing?(tab==='gaming'?pricing.gaming:pricing.food):[],[pricing,tab]);
 if(!authenticated)return <main className="customerPage"><section className="customerHero"><div className="eyebrow">GENZ CAFE · CUSTOMER ACCESS</div><div className="title">Login with mobile</div><p className="muted">Sign in with OTP to unlock your customer profile, member pricing and café services.</p><div className="loginCard card"><label>Mobile number</label><input className="customerInput" value={mobile} onChange={e=>setMobile(e.target.value)} inputMode="tel" maxLength={15} placeholder="10-digit mobile number" disabled={!!challengeId}/>{challengeId&&<><label>One-time password</label><input className="customerInput" value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,'').slice(0,6))} inputMode="numeric" maxLength={6} placeholder="6-digit OTP" autoFocus />{devOtp&&<div className="devOtp">DEV OTP: {devOtp}</div>}</>}{error&&<div className="loginError">{error}</div>}<button className="btn primary" style={{width:'100%',marginTop:12}} onClick={challengeId?verify:requestOtp} disabled={busy}>{busy?'Please wait…':challengeId?'Verify & continue':'Send OTP'}</button>{challengeId&&<button className="btn" style={{width:'100%',marginTop:8}} onClick={()=>{setChallengeId('');setOtp('');setDevOtp('');}}>Change number</button>}</div><div className="muted" style={{fontSize:11}}>Your number is used for customer login and membership matching.</div></section></main>;
 return <main className="customerPage"><section className="customerHero"><div className="eyebrow">GENZ CAFE · CUSTOMER PROFILE</div><div className="title">Your GenZ prices</div><div className="customerStatus card"><div><div className="statLabel">Account</div><strong>{mask(mobile)}</strong></div>{pricing?.isMember?<div className="memberPill">{pricing.tier||'MEMBER'} · MEMBER PRICING</div>:<div className="guestPill">NON-MEMBER</div>}</div>{pricing&&!pricing.isMember&&<div className="upsell card"><div><div className="sectionTitle">Play more. Pay less.</div><p className="muted">Members get the lower prices shown beside eligible gaming and food items.</p></div><button className="btn primary">Get Membership</button></div>}<div className="priceTabs"><button className={tab==='gaming'?'active':''} onClick={()=>setTab('gaming')}>Gaming</button><button className={tab==='food'?'active':''} onClick={()=>setTab('food')}>Food & Beverages</button></div><div className="pricingGrid">{groups.length===0?<div className="card muted">No active {tab==='gaming'?'gaming rates':'menu items'} configured yet. Staff can add them from the admin system.</div>:groups.map((item:any)=><article className="priceCard card" key={item.id}><div className="priceTop"><div><div className="eyebrow">{item.stationType||item.category}{item.pcTier?` · ${item.pcTier}`:''}</div><div className="priceName">{item.label||item.name}</div></div>{item.specs&&<span className="badge cyan">SPECS</span>}</div>{item.specs&&<div className="specs">{item.specs.split(/\n|\|/).map((s:string,i:number)=><span key={i}>{s.trim()}</span>)}</div>}<div className="priceLine"><span>Regular</span><span className={pricing?.isMember?'strike':''}>{money(item.regularPrice)}</span></div><div className="priceLine member"><span>{pricing?.isMember?'Your member price':'Member price'}</span><span>{money(item.memberPrice)} {pricing?.isMember&&item.regularPrice>item.memberPrice&&<small>SAVE {money(item.regularPrice-item.memberPrice)}</small>}</span></div><div className="unit">{item.unitLabel||'per item'}</div></article>)}</div></section></main>;
}
