import {NextResponse} from 'next/server';
import {cookies} from 'next/headers';
import {createBooking,listBookings,cancelBooking,checkInBooking,markNoShow,startBookedSession} from '../../../lib/bookings';
import {COOKIE,requireStaff,audit} from '../../../lib/staff-auth';
const auth=async(p:string)=>requireStaff((await cookies()).get(COOKIE)?.value,p);
const authError=(e:unknown)=>{const m=e instanceof Error?e.message:'';return NextResponse.json({ok:false,error:m==='STAFF_FORBIDDEN'?'Permission denied':'Staff authorization required'},{status:m==='STAFF_FORBIDDEN'?403:401});};
export async function GET(){try{await auth('bookings:read');return NextResponse.json({ok:true,bookings:await listBookings()},{headers:{'Cache-Control':'no-store'}})}catch(e){return authError(e)}}
export async function POST(request:Request){try{const staff=await auth('bookings:write');const body=await request.json();if(typeof body?.stationId!=='string'||body.stationId.length>64||typeof body?.startsAt!=='string'||typeof body?.endsAt!=='string')return NextResponse.json({ok:false,error:'Invalid request'},{status:400});const booking=await createBooking({stationId:body.stationId,customerName:typeof body.customerName==='string'?body.customerName:'Walk-in',customerId:typeof body.customerId==='string'?body.customerId:undefined,memberId:typeof body.memberId==='string'?body.memberId:undefined,startsAt:body.startsAt,endsAt:body.endsAt,deposit:Number.isSafeInteger(body.deposit)&&body.deposit>=0?body.deposit:0,notes:typeof body.notes==='string'?body.notes:undefined,status:body.status==='PENDING'?'PENDING':undefined});await audit(staff.id,'BOOKING_CREATED','booking',booking.id,{stationId:booking.stationId,customerId:booking.customerId||null});return NextResponse.json({ok:true,booking},{status:201})}catch(e){if(e instanceof Error&&(e.message==='STAFF_UNAUTHORIZED'||e.message==='STAFF_FORBIDDEN'))return authError(e);return NextResponse.json({ok:false,error:e instanceof Error?e.message:'Unable to create booking'},{status:400})}}
export async function PATCH(request:Request){try{const staff=await auth('bookings:write');const body=await request.json();if(typeof body?.bookingId!=='string'||!body.bookingId)return NextResponse.json({ok:false,error:'Invalid request'},{status:400});if(body.action==='START_SESSION'){const started=await startBookedSession(body.bookingId);await audit(staff.id,'BOOKING_SESSION_STARTED','booking',body.bookingId,{sessionId:started.sessionId});return NextResponse.json({ok:true,started},{status:201});}let booking;if(body.action==='CHECK_IN')booking=await checkInBooking(body.bookingId);else if(body.action==='NO_SHOW')booking=await markNoShow(body.bookingId);else booking=await cancelBooking(body.bookingId);const action=body.action==='CHECK_IN'?'BOOKING_CHECKED_IN':body.action==='NO_SHOW'?'BOOKING_NO_SHOW':'BOOKING_CANCELLED';await audit(staff.id,action,'booking',body.bookingId);return NextResponse.json({ok:true,booking})}catch(e){if(e instanceof Error&&(e.message==='STAFF_UNAUTHORIZED'||e.message==='STAFF_FORBIDDEN'))return authError(e);return NextResponse.json({ok:false,error:e instanceof Error?e.message:'Unable to update booking'},{status:400})}}
