import {NextResponse} from 'next/server';
import {cookies} from 'next/headers';
import {COOKIE,requireStaff,audit} from '../../../lib/staff-auth';
import {getDailyCloseReport,recordDailyCashCount,approveDailyClose,reopenDailyClose,listDailyCloseEvents} from '../../../lib/daily-close-report';
import {reportCsv,getFinanceReport} from '../../../lib/finance-reports';
const date=(v:string|null)=>v&&/^\d{4}-\d{2}-\d{2}$/.test(v)?v:new Date().toISOString().slice(0,10);const str=(v:unknown)=>typeof v==='string'?v.trim():'';
const auth=(e:unknown)=>{const m=e instanceof Error?e.message:'';return NextResponse.json({ok:false,error:m==='STAFF_FORBIDDEN'?'Permission denied':'Staff authorization required'},{status:m==='STAFF_FORBIDDEN'?403:401})};
export async function GET(req:Request){try{await requireStaff((await cookies()).get(COOKIE)?.value,'finance:read');const q=new URL(req.url).searchParams,d=date(q.get('date'))!,action=q.get('action')||'report';if(action==='events')return NextResponse.json({ok:true,events:await listDailyCloseEvents(d)});if(q.get('format')==='csv'){const r=await getFinanceReport(d,'day');return new Response(reportCsv(r),{headers:{'Content-Type':'text/csv; charset=utf-8','Content-Disposition':`attachment; filename="genz-daily-close-${d}.csv"`}})}return NextResponse.json({ok:true,report:await getDailyCloseReport(d)},{headers:{'Cache-Control':'no-store'}})}catch(e){if(e instanceof Error&&(e.message==='STAFF_UNAUTHORIZED'||e.message==='STAFF_FORBIDDEN'))return auth(e);return NextResponse.json({ok:false,error:e instanceof Error?e.message:'Unable to load daily close'},{status:400})}}
export async function POST(req:Request){try{const body=await req.json(),action=str(body?.action)||'count',staff=await requireStaff((await cookies()).get(COOKIE)?.value,'finance:write'),d=date(str(body?.date)||null)!;if(action==='approve'){await approveDailyClose(d,staff.id);await audit(staff.id,'DAILY_CLOSE_APPROVED','daily_close',d,{});return NextResponse.json({ok:true,report:await getDailyCloseReport(d)})}if(action==='reopen'){await reopenDailyClose(d,staff.id,str(body?.notes)||undefined);await audit(staff.id,'DAILY_CLOSE_REOPENED','daily_close',d,{notes:str(body?.notes)});return NextResponse.json({ok:true,report:await getDailyCloseReport(d)})}const result=await recordDailyCashCount({date:d,countedCash:Number(body?.countedCash),notes:str(body?.notes)||undefined,staffId:staff.id});await audit(staff.id,'DAILY_CASH_COUNT_RECORDED','daily_close',d,{countedCash:Number(body?.countedCash)});return NextResponse.json({ok:true,count:result,report:await getDailyCloseReport(d)})}catch(e){if(e instanceof Error&&(e.message==='STAFF_UNAUTHORIZED'||e.message==='STAFF_FORBIDDEN'))return auth(e);return NextResponse.json({ok:false,error:e instanceof Error?e.message:'Unable to update daily close'},{status:400})}}
