import {NextResponse} from 'next/server';
import {cookies} from 'next/headers';
import {getCustomerByToken} from '../../../lib/customer-auth';
import {createFoodOrder,markCounterPaid} from '../../../lib/food-orders';
import {createRazorpayOrder,getRazorpayKeyId} from '../../../lib/razorpay';
import {advanceOrder,listOrders} from '../../../lib/store';
import {pool} from '../../../lib/mysql';
import {COOKIE,requireStaff,audit} from '../../../lib/staff-auth';
import {publish} from '../../../lib/realtime';
const customer=async()=>{const t=(await cookies()).get('genz_customer')?.value;return t?getCustomerByToken(t):null};
const staffAuth=async(permission:string)=>requireStaff((await cookies()).get(COOKIE)?.value,permission);
export async function GET(){try{await staffAuth('orders:read');return NextResponse.json({ok:true,orders:await listOrders()},{headers:{'Cache-Control':'no-store'}})}catch(e){const forbidden=e instanceof Error&&e.message==='STAFF_FORBIDDEN';return NextResponse.json({ok:false,error:forbidden?'Permission denied':'Staff authorization required'},{status:forbidden?403:401})}}
export async function POST(req:Request){try{const c=await customer();if(!c)return NextResponse.json({ok:false,error:'Login required'},{status:401});const b=await req.json();if(typeof b?.sessionId!=='string'||!Array.isArray(b?.items)||!['PAY_NOW','COUNTER'].includes(b?.paymentMode))return NextResponse.json({ok:false,error:'Invalid request'},{status:400});const o=await createFoodOrder({sessionId:b.sessionId,customerId:c.id,items:b.items,paymentMode:b.paymentMode});publish('ORDER_CREATED',{orderId:o.id,sessionId:o.sessionId,stationId:o.stationId,paymentMode:o.paymentMode});if(o.paymentMode==='COUNTER')return NextResponse.json({ok:true,order:o},{status:201});const rp=await createRazorpayOrder({amountRupees:o.total,receipt:o.id});await pool.execute('UPDATE orders SET razorpay_order_id=?,payment_status=\'PENDING\' WHERE id=?',[rp.id,o.id]);await pool.execute('INSERT INTO payment_transactions(id,order_id,provider,provider_order_id,status,amount,currency,created_at,updated_at) VALUES(UUID(),?,\'RAZORPAY\',?,\'PENDING\',?,\'INR\',NOW(3),NOW(3))',[o.id,rp.id,o.total]);return NextResponse.json({ok:true,order:o,razorpay:{keyId:getRazorpayKeyId(),orderId:rp.id,amount:rp.amount,currency:'INR'}},{status:201})}catch(e){return NextResponse.json({ok:false,error:e instanceof Error?e.message:'Unable to create order'},{status:400})}}
export async function PATCH(req:Request){try{const staff=await staffAuth('orders:write');const b=await req.json();if(b?.action==='counter-paid'&&typeof b.orderId==='string'){const paid=await markCounterPaid(b.orderId);await audit(staff.id,'ORDER_PAYMENT_CAPTURED','order',b.orderId,{mode:'COUNTER'});publish('PAYMENT_CAPTURED',{orderId:b.orderId,mode:'COUNTER'});return NextResponse.json({ok:true,paid})}if(typeof b?.orderId==='string'){const order=await advanceOrder(b.orderId);await audit(staff.id,'ORDER_STATUS_ADVANCED','order',b.orderId,{status:order.status});publish('ORDER_STATUS_CHANGED',{orderId:b.orderId,status:order.status});return NextResponse.json({ok:true,order})}return NextResponse.json({ok:false,error:'Invalid request'},{status:400})}catch(e){const m=e instanceof Error?e.message:'';if(m==='STAFF_UNAUTHORIZED'||m==='STAFF_FORBIDDEN')return NextResponse.json({ok:false,error:m==='STAFF_FORBIDDEN'?'Permission denied':'Staff authorization required'},{status:m==='STAFF_FORBIDDEN'?403:401});return NextResponse.json({ok:false,error:e instanceof Error?e.message:'Unable to update order'},{status:400})}}
