import {NextResponse} from 'next/server';
import {cookies} from 'next/headers';
import {getCustomerByToken} from '../../../lib/customer-auth';
import {createFoodOrder,markCounterPaid,cancelFoodOrder,deliverFoodOrder,setOnlinePaymentPending,failOnlinePaymentCreation} from '../../../lib/food-orders';
import {createRazorpayOrder,getRazorpayKeyId} from '../../../lib/razorpay';
import {advanceOrder,listOrders} from '../../../lib/store';
import {COOKIE,requireStaff,audit} from '../../../lib/staff-auth';
import {publish} from '../../../lib/realtime';
const customer=async()=>{const t=(await cookies()).get('genz_customer')?.value;return t?getCustomerByToken(t):null};
const staffAuth=async(permission:string)=>requireStaff((await cookies()).get(COOKIE)?.value,permission);
const jsonBody=async(req:Request)=>{const len=Number(req.headers.get('content-length')||0);if(len>32_768)throw new Error('Request body too large');return req.json()};
export async function GET(){try{await staffAuth('orders:read');return NextResponse.json({ok:true,orders:await listOrders()},{headers:{'Cache-Control':'no-store'}})}catch(e){const forbidden=e instanceof Error&&e.message==='STAFF_FORBIDDEN';return NextResponse.json({ok:false,error:forbidden?'Permission denied':'Staff authorization required'},{status:forbidden?403:401})}}
export async function POST(req:Request){let createdId:string|undefined;try{const c=await customer();if(!c)return NextResponse.json({ok:false,error:'Login required'},{status:401});const b=await jsonBody(req);if(typeof b?.sessionId!=='string'||b.sessionId.length>64||!Array.isArray(b?.items)||b.items.length<1||b.items.length>50||!['PAY_NOW','COUNTER'].includes(b?.paymentMode))return NextResponse.json({ok:false,error:'Invalid request'},{status:400});const idem=req.headers.get('Idempotency-Key')?.trim()||undefined;if(idem&&idem.length>100)return NextResponse.json({ok:false,error:'Invalid idempotency key'},{status:400});let o;try{o=await createFoodOrder({sessionId:b.sessionId,customerId:c.id,items:b.items,paymentMode:b.paymentMode,idempotencyKey:idem});}catch(e){if((e as {code?:string})?.code!=='ER_DUP_ENTRY')throw e;o=await createFoodOrder({sessionId:b.sessionId,customerId:c.id,items:b.items,paymentMode:b.paymentMode,idempotencyKey:idem});}createdId=o.id;if(o.paymentMode==='COUNTER'){if(!o.existing)publish('ORDER_CREATED',{orderId:o.id,sessionId:o.sessionId,paymentMode:o.paymentMode});return NextResponse.json({ok:true,order:o},{status:o.existing?200:201});}if(o.existing&&o.razorpayOrderId){return NextResponse.json({ok:true,order:o,razorpay:{keyId:getRazorpayKeyId(),orderId:o.razorpayOrderId,amount:o.total*100,currency:'INR'}},{status:200});}const rp=await createRazorpayOrder({amountRupees:o.total,receipt:o.id});await setOnlinePaymentPending(o.id,rp.id);publish('ORDER_CREATED',{orderId:o.id,sessionId:o.sessionId,paymentMode:o.paymentMode});return NextResponse.json({ok:true,order:{...o,razorpayOrderId:rp.id},razorpay:{keyId:getRazorpayKeyId(),orderId:rp.id,amount:rp.amount,currency:'INR'}},{status:o.existing?200:201});}catch(e){if(createdId){try{await failOnlinePaymentCreation(createdId)}catch{}}const code=(e as {code?:string})?.code;if(code==='IDEMPOTENCY_CONFLICT')return NextResponse.json({ok:false,error:'This idempotency key was already used for different order details.'},{status:409});if(code==='ER_DUP_ENTRY')return NextResponse.json({ok:false,error:'The order is already being processed. Please retry.'},{status:409});return NextResponse.json({ok:false,error:e instanceof Error?e.message:'Unable to create order'},{status:400})}}
export async function PATCH(req:Request){try{const staff=await staffAuth('orders:write');const b=await jsonBody(req);if(typeof b?.orderId!=='string')return NextResponse.json({ok:false,error:'Invalid request'},{status:400});if(b.action==='counter-paid'){const paid=await markCounterPaid(b.orderId);await audit(staff.id,'ORDER_PAYMENT_CAPTURED','order',b.orderId,{mode:'COUNTER'});publish('PAYMENT_CAPTURED',{orderId:b.orderId,mode:'COUNTER'});return NextResponse.json({ok:true,paid})}if(b.action==='cancel'){await cancelFoodOrder(b.orderId,staff.id);publish('ORDER_STATUS_CHANGED',{orderId:b.orderId,status:'CANCELLED'});return NextResponse.json({ok:true,status:'CANCELLED'})}if(b.action==='deliver'){await deliverFoodOrder(b.orderId,staff.id);publish('ORDER_STATUS_CHANGED',{orderId:b.orderId,status:'DELIVERED'});return NextResponse.json({ok:true,status:'DELIVERED'})}const order=await advanceOrder(b.orderId);await audit(staff.id,'ORDER_STATUS_ADVANCED','order',b.orderId,{status:order.status});publish('ORDER_STATUS_CHANGED',{orderId:b.orderId,status:order.status});return NextResponse.json({ok:true,order})}catch(e){const m=e instanceof Error?e.message:'';if(m==='STAFF_UNAUTHORIZED'||m==='STAFF_FORBIDDEN')return NextResponse.json({ok:false,error:m==='STAFF_FORBIDDEN'?'Permission denied':'Staff authorization required'},{status:m==='STAFF_FORBIDDEN'?403:401});return NextResponse.json({ok:false,error:e instanceof Error?e.message:'Unable to update order'},{status:400})}}
